
-- OBTENER LAS DEBITACIONES APLICADAS POR SEMANA CONSIDERACION DE LA HORA UTC SE LE RESTAN 6 HORAS
SELECT TO_CHAR(TRUNC(FECHAPROCESADO - (6/24) ), 'dd/MM/yyyy') AS FECHA_PROCESADO,
       COUNT(*)
FROM SINCRONIZADOR.AJUSTEDEB t1
WHERE bProcesado = 1
and (FECHAPROCESADO - (6/24)) >= '13/07/2025'
GROUP BY TO_CHAR(TRUNC(FECHAPROCESADO - (6/24)), 'dd/MM/yyyy')
order by TO_CHAR(TRUNC(FECHAPROCESADO - (6/24)), 'dd/MM/yyyy') desc;