CREATE TABLE dbo.Reportes_Configuraciones_Mensuales (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Nombre_archivo NVARCHAR(100),
    Ruta_Sftp nVarchar(100),
	Sql_query nvarchar(MAX)
);

-- CONSULTAS X REPORTE
---------------------------

INSERT INTO DBO.Reportes_Configuraciones_Mensuales (Nombre_archivo, Ruta_Sftp, Sql_query)
VALUES
('014.01 DATA REPORTE DE CONCESIONES MENSUALES [NOMBRE_MES]', '[NO_DEFINIDO]', 'SELECT VALIDADOR,
RUTA,
ORIGEN,
FECHAOPERACION,
HORAOPERACION,
EMPRESA,
SNUMEROMONEDERO AS MONEDERO,
SNOTARJETA AS NUMTARJETA
,MONTOCOBRADO AS MONTO
,NUMTRX AS TRX
,NUMTRANSBORDO  AS TRANSBORDO
,TIPOTARIFA AS TIPOTARIFA
FROM vwAbordos WITH (NOLOCK)
WHERE YEAR(FECHAOPERACION) = [REPORTE_ANIO] AND MONTH(FECHAOPERACION) = [REPORTE_MES] AND EMPRESA IS NOT NULL AND RUTA IS NOT NULL'),
('014.02 DATA REPORTE DE PARADEROS [NOMBRE_MES]', '[NO_DEFINIDO]', 'SELECT VALIDADOR,
RUTA,
ORIGEN,
FECHAOPERACION,
HORAOPERACION,
EMPRESA,
SNUMEROMONEDERO AS MONEDERO,
SNOTARJETA AS NUMTARJETA
,MONTOCOBRADO AS MONTO
,NUMTRX AS TRX
,NUMTRANSBORDO  AS TRANSBORDO
,TIPOTARIFA AS TIPOTARIFA,
PARADERO AS PARADERO
,SLATITUD AS LATITUD
, SLONGITUD AS LONGITUD
, TIPOTRANSACCION AS TIPODEBITACION
FROM vwAbordos
WHERE YEAR(FECHAOPERACION) = [REPORTE_ANIO] AND MONTH(FECHAOPERACION) = [REPORTE_MES] AND EMPRESA IS NOT NULL AND RUTA IS NOT NULL'),
('014.03 DATA REPORTE POR TIPO DE TARJETA [NOMBRE_MES]', '[NO_DEFINIDO]', 'SELECT VALIDADOR,
RUTA,
ORIGEN,
FECHAOPERACION,
HORAOPERACION,
EMPRESA,
SNUMEROMONEDERO AS MONEDERO,
SNOTARJETA AS NUMTARJETA
,MONTOCOBRADO AS MONTO
,NUMTRX AS TRX
,NUMTRANSBORDO  AS TRANSBORDO
,TIPOTARIFA AS TIPOTARIFA
FROM vwAbordos WITH (NOLOCK)
WHERE YEAR(FECHAOPERACION) = [REPORTE_ANIO] AND MONTH(FECHAOPERACION) = [REPORTE_MES] AND EMPRESA IS NOT NULL AND RUTA IS NOT NULL'),
('014.04 DATA REPORTE DE RECAUDO DE RUTAS DIARIO - MENSUAL [NOMBRE_MES]', '[NO_DEFINIDO]', 'SELECT VALIDADOR, RUTA,NUMCOMERCIAL, FECHAOPERACION,TIPOTARIFA,sum(MONTOCOBRADO)MONTOCOBRADO, sum(NUMTRX)NUMTRX
FROM vwAbordos
WHERE YEAR(FECHAOPERACION) = [REPORTE_ANIO] AND MONTH(FECHAOPERACION) = [REPORTE_MES] AND EMPRESA IS NOT NULL AND RUTA IS NOT NULL
GROUP BY VALIDADOR, RUTA,NUMCOMERCIAL, FECHAOPERACION,TIPOTARIFA'),
('014.05 DATA REPORTE DE RECAUDO POR COMERCIO [NOMBRE_MES]', '[NO_DEFINIDO]', 'select TIPOTRANSACCION AS TIPOCARGO
, GRUPOCOMERCIAL AS COMERCIO
, FECHA AS FECHAOPERACION
, HORA AS HORAOPERACION
, TIPOMONEDERO AS TIPOTARJETA
, INUMMONEDERO AS MONEDERO
, FOLIO AS FOLIOCOMERCIO
, MONTO AS MONTO
, NUMTRX AS TRX
, METODO AS DATA1
 from [dbo].[vwIngresosCargos]
where YEAR(fecha) = [REPORTE_ANIO] and month(fecha) = [REPORTE_MES] and TIPOMOVIMIENTO = ''Cargo'''),
('014.06 DATA REPORTE DE SALDOS POR MONEDERO [NOMBRE_MES]', '[NO_DEFINIDO]', 'SELECT TIPOMONEDERO as TIPOTARJETA
, TIPOMOVIMIENTO as TIPOMOVIMIENTO
, ORIGEN_MOVIMIENTO as ORIGENMOVIMIENTO
, INUMMONEDERO as MONEDERO
, NUMTARJETA as NUMTARJETA
, TIPOTARIFA as TIPOTARIFA
, MONTO as MONTO
, NUMTRX as TRX
, FECHA as FECHAOPERACION
, SLATITUD as LATITUD
, SLONGITUD as LONGITUD
, METODOPAGO as ORIGENCOMERCIO
, SALDO  as SALDOMONEDERO
FROM [dbo].[vwMovimientosEdoCuenta] WITH (NOLOCK)
WHERE SALDO > -12 AND YEAR(FECHA) = [REPORTE_ANIO] AND MONTH(FECHA) =[REPORTE_MES]'),
('014.07 DATA REPORTE DE CONSULTA RAPIDA COMERCIOS [NOMBRE_MES]', '[NO_DEFINIDO]', 'select TIPOTRANSACCION AS TIPOCARGO
, GRUPOCOMERCIAL AS COMERCIO
, FECHA AS FECHAOPERACION
, HORA AS HORAOPERACION
, TIPOMONEDERO AS TIPOTARJETA
, INUMMONEDERO AS MONEDERO
, FOLIO AS FOLIOCOMERCIO
, MONTO AS MONTO
, NUMTRX AS TRX
, METODO AS DATA1
 from [dbo].[vwIngresosCargos]
where YEAR(fecha) = [REPORTE_ANIO] and month(fecha) = [REPORTE_MES] and TIPOMOVIMIENTO = ''Cargo'''),
('014.07 DATA REPORTE DE CONSULTA RAPIDA DEBITACIONES [NOMBRE_MES]', '[NO_DEFINIDO]', 'SELECT VALIDADOR,
RUTA,
ORIGEN,
FECHAOPERACION,
HORAOPERACION,
EMPRESA,
SNUMEROMONEDERO AS MONEDERO,
SNOTARJETA AS NUMTARJETA
,MONTOCOBRADO AS MONTO
,NUMTRX AS TRX
,NUMTRANSBORDO  AS TRANSBORDO
,TIPOTARIFA AS TIPOTARIFA
FROM vwAbordos WITH (NOLOCK)
WHERE YEAR(FECHAOPERACION) = [REPORTE_ANIO] AND MONTH(FECHAOPERACION) = [REPORTE_MES] AND EMPRESA IS NOT NULL AND RUTA IS NOT NULL
');






