-- 1. Scripts de DB

-- CATÁLOGOS.CAJEROS

-- -- ALTER TABLE CATALOGOS.CAJEROS ADD (SUBICACION VARCHAR2(70));
-- -- COMMENT ON COLUMN CATALOGOS.CAJEROS.SUBICACION IS 'Etiqueta de la ubicacion del cajero';

-- -- ALTER TABLE CATALOGOS.CAJEROS ADD (ILIMITQR NUMERIC(10,0));
-- -- COMMENT ON COLUMN CATALOGOS.CAJEROS.ILIMITQR IS 'Limite de Qr vendidos por unidad';

-- -- UPDATE CATALOGOS.CAJEROS SET ILIMITQR = 1;
---catalogos.configuracion_productos


-- CATÁLOGOS.COMERCIOS

-- -- ALTER TABLE CATALOGOS.COMERCIOS ADD (ILIMITQR NUMERIC(10,0));
-- -- COMMENT ON COLUMN CATALOGOS.COMERCIOS.ILIMITQR IS 'Limite de Qr vendidos por unidad';

-- -- ALTER TABLE CATALOGOS.COMERCIOS ADD (SHORACONCILIACION VARCHAR2(10));
-- -- COMMENT ON COLUMN CATALOGOS.COMERCIOS.SHORACONCILIACION IS 'Horario asignado para conciliar el comercio';

-- -- UPDATE CATALOGOS.COMERCIOS SET ILIMITQR = 1;


-- COMERCIO.COMERCIOS

ALTER TABLE COMERCIO.COMERCIOS ADD (LIMITQR NUMERIC(10,0));
COMMENT ON COLUMN COMERCIO.COMERCIOS.LIMITQR IS 'Limite de QR';

ALTER TABLE COMERCIO.COMERCIOS ADD (SHORACONCILIACION VARCHAR2(10));
COMMENT ON COLUMN COMERCIO.COMERCIOS.SHORACONCILIACION IS 'Hora diaria asignada para el proceso de conciliación';

ALTER TABLE COMERCIO.COMERCIOS ADD (DTULTIMACONCILIACION TIMESTAMP);
COMMENT ON COLUMN COMERCIO.COMERCIOS.DTULTIMACONCILIACION IS 'Fecha de la ultima vez que se aplico conciliación a este comercio';


-- COMERCIOCONSULTAS.ESTADODECUENTA

ALTER TABLE COMERCIOCONSULTAS.ESTADODECUENTA ADD (SDIRECCIONFISCAL VARCHAR2(100));
COMMENT ON COLUMN COMERCIOCONSULTAS.ESTADODECUENTA.SDIRECCIONFISCAL IS 'Etiqueta de la ubicacion del cajero';


-- COMERCIOCONSULTAS.OPERACIONES

ALTER TABLE COMERCIOCONSULTAS.OPERACIONES ADD UIDESTATUSCONCILIACION VARCHAR2(50) NULL;
COMMENT ON COLUMN COMERCIOCONSULTAS.OPERACIONES.UIDESTATUSCONCILIACION IS 'RELACION CON ESTATUSCONCILIACION DE COMO FINALIZO SU CONCILIACION';

ALTER TABLE COMERCIOCONSULTAS.OPERACIONES ADD DTFECHACONCILIACION TIMESTAMP NULL;
COMMENT ON COLUMN COMERCIOCONSULTAS.OPERACIONES.DTFECHACONCILIACION IS 'Fecha y Hora en la que el comercio indica que se vendio';

ALTER TABLE COMERCIOCONSULTAS.OPERACIONES ADD DTFECHACONCILIADO TIMESTAMP NULL;
COMMENT ON COLUMN COMERCIOCONSULTAS.OPERACIONES.DTFECHACONCILIADO IS 'Fecha y Hora en la que se aplico la conciliación';

ALTER TABLE COMERCIOCONSULTAS.OPERACIONES MODIFY UIDESTATUSCONCILIACION VARCHAR2(50) DEFAULT '3533957a-dfad-46eb-b8a2-bfb5340dda82' NOT NULL;

ALTER TABLE COMERCIOCONSULTAS.OPERACIONES ADD UIDPRODUCTO VARCHAR2(50);
COMMENT ON COLUMN COMERCIOCONSULTAS.OPERACIONES.UIDPRODUCTO IS 'Identificador del producto';

ALTER TABLE COMERCIOCONSULTAS.OPERACIONES ADD SUBICACION VARCHAR2(50);
COMMENT ON COLUMN COMERCIOCONSULTAS.OPERACIONES.SUBICACION IS 'Ubicación del momento de la operación para el cajero';


-- COMERCIOCONSULTAS.ESTATUSCONCILIACION

CREATE TABLE COMERCIOCONSULTAS.ESTATUSCONCILIACION (
	IDESTATUSCONCILIACION VARCHAR2(50),
	NOMBRE VARCHAR2(250),
	DESCRIPCION VARCHAR2(500),
	DTFECHACREACION TIMESTAMP,
	DTFECHAMODIFICACION TIMESTAMP,
	CONSTRAINT ESTATUSCONCILIACION_PK PRIMARY KEY (IDESTATUSCONCILIACION),
	CONSTRAINT SYS_C0024416 CHECK ("IDESTATUSCONCILIACION" IS NOT NULL)
);

COMMENT ON COLUMN COMERCIOCONSULTAS.ESTATUSCONCILIACION.IDESTATUSCONCILIACION IS 'IDENTIFICADOR DEL ESTATUS';
COMMENT ON COLUMN COMERCIOCONSULTAS.ESTATUSCONCILIACION.NOMBRE IS 'NOMBRE DEL ESTATUS DE CONCILIACIÓN';
COMMENT ON COLUMN COMERCIOCONSULTAS.ESTATUSCONCILIACION.DESCRIPCION IS 'DESCRIPCIÓN DEL ESTATUS';
COMMENT ON COLUMN COMERCIOCONSULTAS.ESTATUSCONCILIACION.DTFECHACREACION IS 'FECHA EN LA QUE SE CREA EL ESTATUS';
COMMENT ON COLUMN COMERCIOCONSULTAS.ESTATUSCONCILIACION.DTFECHAMODIFICACION IS 'FECHA EN LA QUE SE ACTUALIZA ALGUN CAMPO';


-- INSERTS DE ESTATUS

INSERT INTO COMERCIOCONSULTAS.ESTATUSCONCILIACION 
(IDESTATUSCONCILIACION, NOMBRE, DESCRIPCION, DTFECHACREACION, DTFECHAMODIFICACION)
VALUES 
('3533957a-dfad-46eb-b8a2-bfb5340dda82', 'SIN CONCILIACIÓN', 'NO SE HA BUSCADO DURANTE NINGUNA CONCILIACIÓN', CURRENT_TIMESTAMP, SYSDATE);

INSERT INTO COMERCIOCONSULTAS.ESTATUSCONCILIACION 
(IDESTATUSCONCILIACION, NOMBRE, DESCRIPCION, DTFECHACREACION, DTFECHAMODIFICACION)
VALUES 
('318840df-8136-4936-aab7-09718ecbf6a1', 'FILTRADO POR FECHAS', 'FUE BUSCADO PARA CONCILIAR UNA FECHA PERO EL COMERCIO NO LO TIENE', CURRENT_TIMESTAMP, SYSDATE);

INSERT INTO COMERCIOCONSULTAS.ESTATUSCONCILIACION 
(IDESTATUSCONCILIACION, NOMBRE, DESCRIPCION, DTFECHACREACION, DTFECHAMODIFICACION)
VALUES 
('b8df635c-d18e-4c36-8d7e-4d7c8b278d1b', 'CONCILIADO FECHA DIFERENTE', 'FUE ENCONTRADO EN UNA FECHA DE CONCILIACIÓN DIFERENTE', CURRENT_TIMESTAMP, SYSDATE);

INSERT INTO COMERCIOCONSULTAS.ESTATUSCONCILIACION 
(IDESTATUSCONCILIACION, NOMBRE, DESCRIPCION, DTFECHACREACION, DTFECHAMODIFICACION)
VALUES 
('6364bcfd-4483-4cf4-943f-ecb2400fba3f', 'CONCILIADO', 'FUE CONCILIADO DE FORMA CORRECTA', CURRENT_TIMESTAMP, SYSDATE);

INSERT INTO COMERCIOCONSULTAS.ESTATUSCONCILIACION 
(IDESTATUSCONCILIACION, NOMBRE, DESCRIPCION, DTFECHACREACION, DTFECHAMODIFICACION)
VALUES 
('f9560f48-bf48-4f4e-8e47-8b0f38f4dd92', 'CONCILIADO MONTO INCORRECTO', 'FUE CONCILIADO CON UN MONTO INCORRECTO', CURRENT_TIMESTAMP, SYSDATE);

INSERT INTO COMERCIOCONSULTAS.ESTATUSCONCILIACION 
(IDESTATUSCONCILIACION, NOMBRE, DESCRIPCION, DTFECHACREACION, DTFECHAMODIFICACION)
VALUES 
('ed48a5cf-aee7-496b-927a-9c045d5c62e4', 'CONCILIADO ESTATUS NO CONCRETADO', 'FUE CONCILIADO POR ELLOS PERO NUNCA FUE CONFIRMADA POR NOSOTROS', CURRENT_TIMESTAMP, SYSDATE);


-- ACTUALIZACIONES

UPDATE COMERCIOCONSULTAS.OPERACIONES SET UIDESTATUSCONCILIACION = '3533957a-dfad-46eb-b8a2-bfb5340dda82';
COMMIT;


-- MERGE DE DATOS UIDPRODUCTO

MERGE INTO comercioconsultas.operaciones cc
USING (
  SELECT uidoperacion, uidproducto
  FROM comercio.operaciones
) c
ON (cc.uidoperacion = c.uidoperacion AND cc.uidproducto IS NULL)
WHEN MATCHED THEN
UPDATE SET cc.uidproducto = c.uidproducto;

/*Creacion del campo telefono*/
ALTER TABLE COMERCIO.MONEDEROSTARJETAS
ADD STELEFONO VARCHAR2(20) NULL;

COMMENT ON COLUMN MONEDEROSTARJETAS.STELEFONO IS 'Telefono asociado a la tarjeta/monedero';


/*Actualizar valores*/

UPDATE COMERCIO.MONEDEROSTARJETAS e
SET e.STELEFONO = (
    SELECT t.STELEFONO
    FROM MONEDEROCONSULTAS.ESTADODECUENTA t
    WHERE t.UIDTARJETA = e.UIDTARJETA
      AND t.UIDMONEDERO= e.UIDMONEDERO
)
WHERE EXISTS (
    SELECT 1
    FROM MONEDEROCONSULTAS.ESTADODECUENTA t
    WHERE t.UIDTARJETA = e.UIDTARJETA
      AND t.UIDMONEDERO= e.UIDMONEDERO
);













MERGE INTO comercioconsultas.operaciones cc
USING (
 SELECT uidoperacion,
 uidproducto,
   ROW_NUMBER() OVER (ORDER BY DTFECHACREACION DESC) AS RN
 FROM comercio.operaciones
 order by RN asc
) c
ON (cc.uidoperacion = c.uidoperacion AND cc.uidproducto IS NULL)
WHEN MATCHED THEN
UPDATE SET cc.uidproducto = c.uidproducto where c.RN <=1000000 and cc.UIDPRODUCTO is null;




















-----------------14-07-2025


UPDATE prep_comercio.MONEDEROSTARJETAS e
SET e.STELEFONO = (
    SELECT t.STELEFONO
    FROM prep_monederoconsultas.ESTADODECUENTA t
    WHERE t.UIDMONEDERO = e.UIDMONEDERO
    AND t.STELEFONO IS NOT NULL
    FETCH FIRST 1 ROWS ONLY
)
WHERE e.STELEFONO IS NULL
AND EXISTS (
    SELECT 1
    FROM prep_monederoconsultas.ESTADODECUENTA t
    WHERE t.UIDMONEDERO = e.UIDMONEDERO
    AND t.STELEFONO IS NOT NULL
);


--------------------------
UPDATE comercio.MONEDEROSTARJETAS e
SET e.STELEFONO = (
    SELECT t.STELEFONO
    FROM monederoconsultas.ESTADODECUENTA t
    WHERE t.UIDMONEDERO= e.UIDMONEDERO
)
WHERE EXISTS (
    SELECT 1
    FROM monederoconsultas.ESTADODECUENTA t
    WHERE t.UIDMONEDERO= e.UIDMONEDERO
);