-- COMERCIO.COMERCIOS
------------------
ALTER TABLE COMERCIO.COMERCIOS ADD (LIMITQR NUMERIC(10,0));
COMMENT ON COLUMN COMERCIO.COMERCIOS.LIMITQR IS 'Limite de QR';

ALTER TABLE COMERCIO.COMERCIOS ADD (SHORACONCILIACION VARCHAR2(10));
COMMENT ON COLUMN COMERCIO.COMERCIOS.SHORACONCILIACION IS 'Hora diaria asignada para el proceso de conciliación';

ALTER TABLE COMERCIO.COMERCIOS ADD (DTULTIMACONCILIACION TIMESTAMP);
COMMENT ON COLUMN COMERCIO.COMERCIOS.DTULTIMACONCILIACION IS 'Fecha de la ultima vez que se aplico conciliación a este comercio';

-- COMERCIOCONSULTAS.ESTADODECUENTA
--------------------------------
ALTER TABLE COMERCIOCONSULTAS.ESTADODECUENTA ADD (SDIRECCIONFISCAL VARCHAR2(100));
COMMENT ON COLUMN COMERCIOCONSULTAS.ESTADODECUENTA.SDIRECCIONFISCAL IS 'Etiqueta de la ubicacion del cajero';

-- COMERCIOCONSULTAS.OPERACIONES
-----------------------------
ALTER TABLE COMERCIOCONSULTAS.OPERACIONES ADD UIDESTATUSCONCILIACION VARCHAR2(50) NULL;
COMMENT ON COLUMN COMERCIOCONSULTAS.OPERACIONES.UIDESTATUSCONCILIACION IS 'RELACION CON ESTATUSCONCILIACION DE COMO FINALIZO SU CONCILIACION';

ALTER TABLE COMERCIOCONSULTAS.OPERACIONES ADD DTFECHACONCILIACION TIMESTAMP NULL;
COMMENT ON COLUMN COMERCIOCONSULTAS.OPERACIONES.DTFECHACONCILIACION IS 'Fecha y Hora en la que el comercio indica que se vendio';

ALTER TABLE COMERCIOCONSULTAS.OPERACIONES ADD DTFECHACONCILIADO TIMESTAMP NULL;
COMMENT ON COLUMN COMERCIOCONSULTAS.OPERACIONES.DTFECHACONCILIADO IS 'Fecha y Hora en la que se aplico la conciliación';

UPDATE COMERCIOCONSULTAS.OPERACIONES SET UIDESTATUSCONCILIACION = '3533957a-dfad-46eb-b8a2-bfb5340dda82';
COMMIT;

ALTER TABLE COMERCIOCONSULTAS.OPERACIONES MODIFY UIDESTATUSCONCILIACION VARCHAR2(50) DEFAULT '3533957a-dfad-46eb-b8a2-bfb5340dda82' NOT NULL;

ALTER TABLE COMERCIOCONSULTAS.OPERACIONES ADD UIDPRODUCTO VARCHAR2(50);
COMMENT ON COLUMN COMERCIOCONSULTAS.OPERACIONES.UIDPRODUCTO IS 'Identificador del producto';

ALTER TABLE COMERCIOCONSULTAS.OPERACIONES ADD SUBICACION VARCHAR2(50);
COMMENT ON COLUMN COMERCIOCONSULTAS.OPERACIONES.SUBICACION IS 'Ubicación del momento de la operación para el cajero';



-- MERGE INTO comercioconsultas.operaciones cc PENDIENTE
-- USING (
--   SELECT uidoperacion, uidproducto
--   FROM comercio.operaciones
-- ) c
-- ON (cc.uidoperacion = c.uidoperacion AND cc.uidproducto IS NULL)
-- WHEN MATCHED THEN
-- UPDATE SET cc.uidproducto = c.uidproducto;
-- COMMIT;
-- COMERCIOCONSULTAS.ESTATUSCONCILIACION
-------------------------------------
CREATE TABLE COMERCIOCONSULTAS.ESTATUSCONCILIACION (
    IDESTATUSCONCILIACION VARCHAR2(50),
    NOMBRE VARCHAR2(250),
    DESCRIPCION VARCHAR2(500),
    DTFECHACREACION TIMESTAMP,
    DTFECHAMODIFICACION TIMESTAMP,
    CONSTRAINT ESTATUSCONCILIACION_PK PRIMARY KEY (IDESTATUSCONCILIACION),
    CONSTRAINT SYS_C0024416 CHECK ("IDESTATUSCONCILIACION" IS NOT NULL)
);
COMMIT;

-- Comentarios por cada columna agregados
-- 6 inserts:

INSERT INTO COMERCIOCONSULTAS.ESTATUSCONCILIACION 
VALUES ('3533957a-dfad-46eb-b8a2-bfb5340dda82', 'SIN CONCILIACIÓN', 'NO SE HA BUSCADO DURANTE NINGUNA CONCILIACIÓN', CURRENT_TIMESTAMP, SYSDATE);
COMMIT;

INSERT INTO COMERCIOCONSULTAS.ESTATUSCONCILIACION 
VALUES ('318840df-8136-4936-aab7-09718ecbf6a1', 'FILTRADO POR FECHAS', 'FUE BUSCADO PARA CONCILIAR UNA FECHA PERO EL COMERCIO NO LO TIENE', CURRENT_TIMESTAMP, SYSDATE);
COMMIT;

INSERT INTO COMERCIOCONSULTAS.ESTATUSCONCILIACION 
VALUES ('b8df635c-d18e-4c36-8d7e-4d7c8b278d1b', 'CONCILIADO FECHA DIFERENTE', 'FUE ENCONTRADO EN UNA FECHA DE CONCILIACIÓN DIFERENTE', CURRENT_TIMESTAMP, SYSDATE);
COMMIT;

INSERT INTO COMERCIOCONSULTAS.ESTATUSCONCILIACION 
VALUES ('6364bcfd-4483-4cf4-943f-ecb2400fba3f', 'CONCILIADO', 'FUE CONCILIADO DE FORMA CORRECTA', CURRENT_TIMESTAMP, SYSDATE);
COMMIT;

INSERT INTO COMERCIOCONSULTAS.ESTATUSCONCILIACION 
VALUES ('f9560f48-bf48-4f4e-8e47-8b0f38f4dd92', 'CONCILIADO MONTO INCORRECTO', 'FUE CONCILIADO CON UN MONTO INCORRECTO', CURRENT_TIMESTAMP, SYSDATE);
COMMIT;

INSERT INTO COMERCIOCONSULTAS.ESTATUSCONCILIACION 
VALUES ('ed48a5cf-aee7-496b-927a-9c045d5c62e4', 'CONCILIADO ESTATUS NO CONCRETADO', 'FUE CONCILIADO POR ELLOS PERO NUNCA FUE CONFIRMADA POR NOSOTROS', CURRENT_TIMESTAMP, SYSDATE);
COMMIT;



/*Creacion del campo telefono*/
ALTER TABLE COMERCIO.MONEDEROSTARJETAS
ADD STELEFONO VARCHAR2(20) NULL;

COMMENT ON COLUMN MONEDEROSTARJETAS.STELEFONO IS 'Telefono asociado a la tarjeta/monedero';    

--Actualizar monederosTarjetas
-- UPDATE COMERCIO.MONEDEROSTARJETAS e   PENDIENTE
-- SET e.STELEFONO = (
--     SELECT t.STELEFONO
--     FROM MONEDEROCONSULTAS.ESTADODECUENTA t
--     WHERE t.UIDTARJETA = e.UIDTARJETA
--       AND t.UIDMONEDERO= e.UIDMONEDERO
-- )
-- WHERE EXISTS (
--     SELECT 1
--     FROM MONEDEROCONSULTAS.ESTADODECUENTA t
--     WHERE t.UIDTARJETA = e.UIDTARJETA
--       AND t.UIDMONEDERO= e.UIDMONEDERO
-- );
-- COMMIT;
