UPDATE prep_comercio.MONEDEROSTARJETAS e
SET e.STELEFONO = (
    SELECT t.STELEFONO
    FROM prep_monederoconsultas.ESTADODECUENTA t
    WHERE t.UIDMONEDERO = e.UIDMONEDERO
    AND t.STELEFONO IS NOT NULL
    FETCH FIRST 1 ROWS ONLY
)
WHERE e.STELEFONO IS NULL
AND EXISTS (
    SELECT 1
    FROM prep_monederoconsultas.ESTADODECUENTA t
    WHERE t.UIDMONEDERO = e.UIDMONEDERO
    AND t.STELEFONO IS NOT NULL
);