

-----crear bk

CREATE TABLE "NOTIFICACIONES"."HISTORIAL_RESP" 
   (	"UIDHISTORIAL" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"STITULO" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"BENVIADO" NUMBER(1,0), 
	"DTFECHA" DATE, 
	"SDESTINATARIO" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"SCONTENIDO" CLOB COLLATE "USING_NLS_COMP", 
	"SERROR" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"BLEIDO" NUMBER(1,0), 
	"UIDUSUARIO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"UIDTIPO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"UIDMETODO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"BACTIVO" NUMBER(1,0), 
	"BBAJA" NUMBER(1,0), 
	 CHECK ("UIDMETODO" IS NOT NULL) ENABLE, 
	 CHECK ("DTFECHA" IS NOT NULL) ENABLE, 
	 CHECK ("SDESTINATARIO" IS NOT NULL) ENABLE, 
	 CHECK ("UIDHISTORIAL" IS NOT NULL) ENABLE, 
	 CONSTRAINT "HISTORIAL_PK" PRIMARY KEY ("UIDHISTORIAL")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE, 
	 CHECK ("BENVIADO" IS NOT NULL) ENABLE, 
	 CONSTRAINT "FK_METODOS_UIDMETODO" FOREIGN KEY ("UIDMETODO")
	  REFERENCES "NOTIFICACIONES"."METODOS" ("UIDMETODO") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"   NO INMEMORY 
 LOB ("SCONTENIDO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;


  GRANT SELECT ON "NOTIFICACIONES"."HISTORIAL" TO "VISORTESTER";
  GRANT SELECT ON "NOTIFICACIONES"."HISTORIAL" TO "USR_DBA";
  GRANT UPDATE ON "NOTIFICACIONES"."HISTORIAL" TO "USR_DBA";


INSERT INTO notificaciones.historial_BK
SELECT * FROM notificaciones.historial;