--SOLICITUD PEDIDA POR DAVID REALPOZO A DISPOSICION DE BENIGNO
SELECT     
    'ORDENES no replicadas (PAGOS vs PAGOSCONSULTAS)' AS fuente,
    COUNT(0) AS discrepancias
FROM  PAGOS.ORDENES t1
LEFT JOIN PAGOSCONSULTAS.ORDENES t2 ON t1.UIDORDEN = t2.UIDORDEN 
WHERE t2.UIDORDEN IS NULL AND t1.UIDORDEN = '5eda6d23-9b0e-4079-a817-0a83f01394a0';
--------------
INSERT INTO PAGOSCONSULTAS.ORDENES (
    UIDORDEN, SORDEN_REF, DMONTO, SCONCEPTO, DTFECHA, IOPCION_PAGO, BACTIVO, BPAGADO, UIDUSUARIO, UIDPAQUETE,
    UIDMONEDERO, SEMAILUSUARIO, SNUMMONEDERO, SNUMTARJETA, IORIGEN
)
SELECT t1.UIDORDEN,t1.SORDEN_REF, t1.DMONTO, t1.SCONCEPTO, t1.DTFECHA, t1.IOPCION_PAGO, t1.BACTIVO, t1.BPAGADO, t1.UIDUSUARIO, t1.UIDPAQUETE,
    t1.UIDMONEDERO, t1.SEMAILUSUARIO, e.INUMMONEDERO, e.INUMEROTARJETA, t1.IORIGEN
FROM  PAGOS.ORDENES t1
LEFT JOIN PAGOSCONSULTAS.ORDENES t2 ON t1.UIDORDEN = t2.UIDORDEN
LEFT JOIN APPMONEDEROCOMMAND.ESTADODECUENTA e ON t1.UIDMONEDERO = e.UIDMONEDERO 
WHERE t2.UIDORDEN IS NULL AND t1.UIDORDEN = '5eda6d23-9b0e-4079-a817-0a83f01394a0';
COMMIT;


UPDATE PAGOSCONSULTAS.ORDENES
SET SESTATUS = 'COMPLETADA'
WHERE UIDORDEN = '5eda6d23-9b0e-4079-a817-0a83f01394a0';




INSERT INTO PAGOSCONSULTAS.ESTATUSORDEN (
UIDESTATUSORDEN,UIDORDEN, SESTATUS, DTFECHA, IORDEN
)
SELECT 
'd0586cd1-a683-4a75-b61f-1dd8f20ddbb2' as UIDESTATUSORDEN
,t1.UIDORDEN,
'CREADA',
t1.DTFECHA, 
1
FROM PAGOS.ORDENES t1
WHERE t1.UIDORDEN = '5eda6d23-9b0e-4079-a817-0a83f01394a0';
COMMIT;











