-- PARA VALIDAR EN COMMAND
SELECT 
    'TARJETAS diferencias de campo UIDESTATUSTARJETA (APPMONEDEROCOMMAND vs CREDENCIALIZACION)' AS fuente, 
    COUNT(0) AS discrepancias
FROM APPMONEDEROCOMMAND.ESTADODECUENTA e 
INNER JOIN CREDENCIALIZACION.TARJETAS t ON (e.UIDMONEDERO = t.UIDMONEDERO) 
WHERE t.BACTIVO = 1 AND t.BBAJA = 0 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.BASOCIADA = 1 
AND t.UIDTARJETA IN ('1752d30a-bd34-42c6-96bb-08dd42ec9e63','6fb987d6-d193-405e-96c2-08dd42ec9e63')
AND e.UIDESTATUSTARJETA <> t.UIDESTATUSTARJETA;

-- ACTUALIZAR EL UIDESATUSTARJETA APPMONEDEROCOMMAND
MERGE INTO APPMONEDEROCOMMAND.ESTADODECUENTA D
USING (
    SELECT T.UIDTARJETA, T.UIDESTATUSTARJETA
        FROM APPMONEDEROCOMMAND.ESTADODECUENTA E 
    INNER JOIN CREDENCIALIZACION.TARJETAS T ON (E.UIDMONEDERO = T.UIDMONEDERO) 
    WHERE t.BACTIVO = 1 AND t.BBAJA = 0 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.BASOCIADA = 1
    AND t.UIDTARJETA IN ('1752d30a-bd34-42c6-96bb-08dd42ec9e63','6fb987d6-d193-405e-96c2-08dd42ec9e63')
    AND e.UIDESTATUSTARJETA <> t.UIDESTATUSTARJETA
    )
) O
ON (D.UIDTARJETA = O.UIDTARJETA)
WHEN MATCHED THEN
  UPDATE SET D.UIDESTATUSTARJETA = O.UIDESTATUSTARJETA;





-- PARA VALIDAR EN QUERY
SELECT 
    'TARJETAS diferencias de campo UIDESTATUSTARJETA (APPMONEDEROCOMMAND vs CREDENCIALIZACION)' AS fuente, 
    COUNT(0) AS discrepancias
FROM APPMONEDEROQUERY.ESTADODECUENTA e 
INNER JOIN CREDENCIALIZACION.TARJETAS t ON (e.UIDMONEDERO = t.UIDMONEDERO) 
WHERE t.BACTIVO = 1 AND t.BBAJA = 0 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.BASOCIADA = 1 
AND t.UIDTARJETA IN ('1752d30a-bd34-42c6-96bb-08dd42ec9e63','6fb987d6-d193-405e-96c2-08dd42ec9e63')
AND e.UIDESTATUSTARJETA <> t.UIDESTATUSTARJETA;

-- ACTUALIZAR EL UIDESATUSTARJETA APPMONEDEROQUERY
MERGE INTO APPMONEDEROQUERY.ESTADODECUENTA D
USING (
    SELECT T.UIDTARJETA, T.UIDESTATUSTARJETA
        FROM APPMONEDEROQUERY.ESTADODECUENTA E 
    INNER JOIN CREDENCIALIZACION.TARJETAS T ON (E.UIDMONEDERO = T.UIDMONEDERO) 
    WHERE t.BACTIVO = 1 AND t.BBAJA = 0 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.BASOCIADA = 1
    AND t.UIDTARJETA IN ('1752d30a-bd34-42c6-96bb-08dd42ec9e63','6fb987d6-d193-405e-96c2-08dd42ec9e63')
    AND e.UIDESTATUSTARJETA <> t.UIDESTATUSTARJETA
    )
) O
ON (D.UIDTARJETA = O.UIDTARJETA)
WHEN MATCHED THEN
  UPDATE SET D.UIDESTATUSTARJETA = O.UIDESTATUSTARJETA;