select dtfechaoperacion,
       dtfechacreacion,
--        INUMEROTARJETA,
       INUMEROTRANSBORDO NUM_TRANSBORDO,
       DMONTO          SALDO_COBRADO,
       DSALDO          SALDO_DESPUES,
       DSALDO + DMONTO SALDO_ANTES
from SINCRONIZADOR.DETALLETRANSACCIONQRDINAMICO t1
where 1 = 1
  and t1.INUMEROTARJETA = '1000000000996797'
  and to_char(t1.DTFECHAOPERACION, 'MM') = 9
  and to_char(t1.DTFECHAOPERACION, 'DD') = 22
order by t1.DTFECHAOPERACION desc



select
    UIDMOVIMIENTOS,
    DTFECHAOPERACION,
    INUMMONEDERO,
    DMONTO,
    DSALDOACTUAL,
    DSALDOANTERIOR
    from MONEDEROCONSULTAS.MOVIMIENTOS t1
where 1 = 1
  and t1.INUMMONEDERO = '1000000000996797'
  and to_char(t1.DTFECHAOPERACION, 'MM') = 9
  and to_char(t1.DTFECHAOPERACION, 'DD') = 22
order by t1.DTFECHAOPERACION desc

