
--PREP_CATALOGOS - PREP_CATALOGOS.PREP_COMERCIO.Creacion 
--PREP_CATALOGOS - PREP_CATALOGOS.PREP_COMERCIO.Bloqueo
--PREP_CATALOGOS - PREP_CATALOGOS.PREP_COMERCIO.Reactivar
--PREP_CATALOGOS - PREP_CATALOGOS.PREP_COMERCIO.Borrado
SELECT C.SCOMERCIO, C.UIDCOMERCIO ,c2.UIDCOMERCIO ,c.UIDESTATUS, c2.UIDESTATUS   FROM PREP_CATALOGOS.COMERCIOS C
LEFT JOIN PREP_COMERCIO.COMERCIOS c2  ON C.UIDCOMERCIO = c2.UIDCOMERCIO 
    --estatus baja
    --WHERE c.UIDESTATUS= 'f43af446-9abb-44f6-aaa5-b95cf1fcc124'
    --ACTIVOS
    --WHERE c.UIDESTATUS= 'e1087a82-86a9-4032-a1a7-4da120f9dbb8'
    --WHERE c.SCOMERCIO='TESTING 4'
;

--PREP_CATALOGOS - PREP_CATALOGOS.Motivos.Creacion200 
--PREP_CATALOGOS - PREP_CATALOGOS.Motivos.Creacion500 
 --PREP_CATALOGOS - PREP_CATALOGOS.Motivos.Actualización200 
 --PREP_CATALOGOS - PREP_CATALOGOS.Motivos.Actualización500 
SELECT m.BACTIVO ,m.BBAJA ,m.* FROM PREP_APPTICKETS.MOTIVOS m WHERE m.SMOTIVO IN ('BAJA ADMINISTRATIVA' ,'Montos incorrectos')
;
SELECT m.SMOTIVO , m.UIDMOTIVO ,m2.UIDMOTIVO  , m.BACTIVO ,m2.BACTIVO, m.IMODULO FROM PREP_CATALOGOS.MOTIVOS m  
LEFT JOIN PREP_APPTICKETS.MOTIVOS m2  ON m.UIDMOTIVO =m2.UIDMOTIVO 
WHERE m.SMOTIVO IN ('BAJA ADMINISTRATIVA' ,'Montos incorrectos')
;


--catálogos - PREP_CATALOGOS.Productos.Actualizacion 
--Monedero PREP_CATALOGOS - PREP_CATALOGOS.Productos.Actualizacion 

SELECT m.SNOMBRE ,m2.SNOMBRE , m.SDESCRIPCION , m.SDESCRIPCION ,m.dtfechaultmod
FROM PREP_CATALOGOS.PRODUCTOS m
LEFT JOIN PREP_monederocomandos.PRODUCTOS  m2  ON m.UIDPRODUCTO =m2.UIDPRODUCTO
;


--Monedero PREP_CATALOGOS - PREP_CATALOGOS.Productos.Actualizacion 
--Monedero PREP_CATALOGOS - PREP_CATALOGOS.paquetes.Creacion 
--Monedero PREP_CATALOGOS - PREP_CATALOGOS.paquetes.Actualizacion 
--Monedero PREP_CATALOGOS - PREP_CATALOGOS.paquetes.Borrado 


SELECT m.UIDPAQUETE,m2.UIDPAQUETE, m.SNOMBRE ,m2.SNOMBRE , m.SDESCRIPCION , m.SDESCRIPCION ,m.dtfechaultmod
FROM PREP_CATALOGOS.PAQUETES m
LEFT JOIN PREP_monederocomandos.PAQUETES  m2  ON m.UIDPRODUCTO =m2.UIDPRODUCTO
WHERE m2.UIDPAQUETE IS NULL AND m.BBAJA = 0 AND m.BACTIVO = 1
;

--PREP_COMERCIO PREP_CATALOGOS - PREP_CATALOGOS.paquetes.Creacion 
--PREP_COMERCIO PREP_CATALOGOS - PREP_CATALOGOS.paquetes.Borrado
SELECT  m.UIDPAQUETE,m2.UIDPAQUETE, m.UIDPRODUCTO,m.SNOMBRE ,m2.SNOMBRE ,m.BACTIVO ,m2.BACTIVO 
FROM PREP_CATALOGOS.PAQUETES m
LEFT JOIN PREP_COMERCIO.PAQUETES  m2  ON m.UIDPAQUETE =m2.UIDPRODUCTO
 WHERE m2.UIDPAQUETE IS NULL AND m.BBAJA = 0 AND m.BACTIVO = 1
 ;

 
 
--PREP_CATALOGOS.TipoTarifas.Actualizacion 
--PREP_CATALOGOS.TipoTarifas.Borrado 
 
SELECT t.DTFECHAULTMOD ,t.* FROM PREP_SINCRONIZADOR.TIPOTARIFAS   t WHERE t.STIPOTARIFA ='Héroe Ciudadano  REP';
SELECT t.* FROM PREP_APPTICKETS.TIPOSTARIFA   t WHERE t.STIPOTARIFA ='Héroe Ciudadano  REP';

SELECT m.STIPOTARIFA , m.UIDTIPOTARIFA ,m2.UIDTIPOTARIFA FROM PREP_CATALOGOS.TIPOTARIFAS  m 
LEFT JOIN PREP_APPTICKETS.TIPOSTARIFA m2  ON m.UIDTIPOTARIFA =m2.UIDTIPOTARIFA 
WHERE m.STIPOTARIFA IN ('Héroe Ciudadano  REP');

SELECT m.STIPOTARIFA , m.UIDTIPOTARIFA ,m2.UIDTIPOTARIFA  FROM PREP_CATALOGOS.TIPOTARIFAS  m 
LEFT JOIN PREP_SINCRONIZADOR.TIPOTARIFAS  m2  ON m.UIDTIPOTARIFA =m2.UIDTIPOTARIFA 
WHERE m.STIPOTARIFA IN ('Héroe Ciudadano  REP');

SELECT m.STIPOTARIFA , m.UIDTIPOTARIFA ,m2.UIDTIPOTARIFA  FROM PREP_CATALOGOS.TIPOTARIFAS  m 
LEFT JOIN PREP_monederoconsultas.TIPOTARIFAS  m2  ON m.UIDTIPOTARIFA =m2.UIDTIPOTARIFA 
WHERE m.STIPOTARIFA IN ('Héroe Ciudadano  REP');

SELECT m.STIPOTARIFA , m.UIDTIPOTARIFA ,m2.UIDTIPOTARIFA  FROM PREP_CATALOGOS.TIPOTARIFAS  m 
LEFT JOIN PREP_monederocomandos.TIPOTARIFAS  m2  ON m.UIDTIPOTARIFA =m2.UIDTIPOTARIFA 
WHERE m.STIPOTARIFA IN ('Héroe Ciudadano  REP');

SELECT m.STIPOTARIFA , m.UIDTIPOTARIFA ,m2.UIDTIPOTARIFA  FROM PREP_CATALOGOS.TIPOTARIFAS  m 
LEFT JOIN PREP_TARIFAS.TIPOTARIFAS  m2  ON m.UIDTIPOTARIFA =m2.UIDTIPOTARIFA 
WHERE m.STIPOTARIFA IN ('Héroe Ciudadano  REP');

SELECT m.STIPOTARIFA , m.UIDTIPOTARIFA ,m2.UIDTIPOTARIFA  FROM PREP_CATALOGOS.TIPOTARIFAS  m 
LEFT JOIN PREP_credencializacion.TIPOTARIFA  m2  ON m.UIDTIPOTARIFA =m2.UIDTIPOTARIFA 
WHERE m.STIPOTARIFA IN ('Héroe Ciudadano  REP');


-- PREP_CATALOGOS.Vsam.cracion 
-- PREP_CATALOGOS.Vsam.actualización 
--PREP_CATALOGOS.Vsam.BORRADO 

SELECT 
m.UIDVSAM ,m2.UIDVSAM , m.SCSN , m2.SCSN 
FROM PREP_CATALOGOS.VSAM  m 
LEFT JOIN PREP_SINCRONIZADOR.VSAM  m2  ON m.UIDVSAM =m2.UIDVSAM 
WHERE m.SCSN IN ('');

SELECT 
m.UIDVSAM ,m2.UIDVSAM , m.SCSN , m2.SCSN 
FROM PREP_CATALOGOS.VSAM  m 
LEFT JOIN PREP_OPENLOOP.VSAM  m2  ON m.UIDVSAM =m2.UIDVSAM 
WHERE m.SCSN IN ('');

-- PREP_CATALOGOS.Validador.Creacion 
-- PREP_CATALOGOS.Validador.ACTUALIZADO
-- PREP_CATALOGOS.Validado.Borrado
 

 SELECT 
m.UIDVALIDADOR ,m2.UIDVALIDADOR , m.SVALIDADOR , m2.SVALIDADOR 
FROM PREP_CATALOGOS.VALIDADORES  m 
LEFT JOIN PREP_SINCRONIZADOR.VALIDADORES  m2  ON m.UIDVALIDADOR =m2.UIDVALIDADOR 
WHERE m.UIDVALIDADOR IN ('');
 
 SELECT 
m.UIDVALIDADOR ,m2.UIDVALIDADOR , m.SVALIDADOR 
FROM PREP_CATALOGOS.VALIDADORES  m 
LEFT JOIN PREP_OPENLOOP.VALIDADORES  m2  ON m.UIDVALIDADOR =m2.UIDVALIDADOR 
WHERE m.UIDVALIDADOR IN ('');
 
-- PREP_CATALOGOS.Rutas.creacion 
--PREP_CATALOGOS.Rutas.actualización 
--PREP_CATALOGOS.Rutas.BORRADO 


 SELECT 
m.UIDRUTA ,m2.UIDRUTA , m.SRUTA ,m2.SRUTA
FROM PREP_CATALOGOS.RUTAS  m 
LEFT JOIN PREP_SINCRONIZADOR.RUTAS  m2  ON m.UIDRUTA =m2.UIDRUTA 
WHERE m.UIDRUTA IN ('');


 SELECT 
m.UIDRUTA ,m2.UIDRUTA , m.SRUTA ,m2.SRUTA
FROM PREP_CATALOGOS.RUTAS  m 
LEFT JOIN PREP_OPENLOOP.RUTAS  m2  ON m.UIDRUTA =m2.UIDRUTA 
WHERE m.UIDRUTA IN ('');

--PREP_CATALOGOS.autobus.Creacion  
--PREP_CATALOGOS.Autobus.ACTUALIZADO
--PREP_CATALOGOS.Autobus.borrado 

SELECT 
m.UIDAUTOBUS ,m2.UIDAUTOBUS , m.SNUMECO , m2.SNUMECO ,m.SPLACAS,m2.SPLACAS
FROM PREP_CATALOGOS.AUTOBUSES  m 
LEFT JOIN PREP_SINCRONIZADOR.AUTOBUSES  m2  ON m.UIDAUTOBUS =m2.UIDAUTOBUS 
WHERE m.UIDAUTOBUS IN ('');


-- PREP_CATALOGOS.Autobus.RutaChofer,creado 
--PREP_CATALOGOS.Autobus.RutaChofer,Actualizado 
--PREP_CATALOGOS.Autobus.RutaChofer,BORRADO 

SELECT 
m.UIDAUTOBUS ,m2.UIDAUTOBUS , m.UIDCHOFER , m2.UIDCHOFER ,m.UIDRUTA,m2.UIDRUTA
 FROM PREP_CATALOGOS.autobusrutachofer  m 
LEFT JOIN PREP_SINCRONIZADOR.autobusrutachofer  m2  ON
m.UIDAUTOBUS  = m2.UIDAUTOBUS AND 
m.UIDCHOFER = m2.UIDCHOFER AND
m.UIDRUTA =m2.UIDRUTA 
WHERE m.UIDAUTOBUS IN ('');

-- PREP_CATALOGOS.autobusvalidador.Creacion 
--PREP_CATALOGOS.AutobusValidador.Borrar 
--PREP_CATALOGOS.AutobusValidador.Reasignación 

 
  SELECT 
m.UIDAUTOBUS ,m2.UIDAUTOBUS , m.UIDVALIDADOR , m2.UIDVALIDADOR
FROM PREP_CATALOGOS.autobusvalidador  m 
LEFT JOIN PREP_SINCRONIZADOR.autobusvalidador  m2  ON
m.UIDAUTOBUS  = m2.UIDAUTOBUS AND 
m.UIDVALIDADOR = m2.UIDVALIDADOR
WHERE m.UIDAUTOBUS IN ('');


--PREP_CATALOGOS.ConfiguracionTarifas 

