--RUTAS
SELECT *
FROM PREP_CATALOGOS.RUTAS P
WHERE UIDRUTA NOT IN (
    SELECT UIDRUTA
    FROM PREP_OPENLOOP.RUTAS
) AND P.BACTIVO = 1; 

Select * from PREP_OPENLOOP.RUTAS 
WHERE SRUTA = '';

--Validadores
SELECT *
FROM PREP_CATALOGOS.VALIDADORES P
WHERE UIDVALIDADOR NOT IN (
    SELECT UIDVALIDADOR
    FROM PREP_OPENLOOP.VALIDADORES
) AND P.BACTIVO = 1;

Select * from PREP_OPENLOOP.VALIDADORES 
WHERE SNUMEROSERIE = '';

--VSAM
SELECT *
FROM PREP_CATALOGOS.VSAM P
WHERE UIDVSAM NOT IN (
    SELECT UIDVSAM
    FROM PREP_OPENLOOP.VSAM
) AND P.BACTIVO = 1;

Select * from PREP_OPENLOOP.VSAM 
WHERE SCSN = '';

--VSAM
SELECT *
FROM PREP_CATALOGOS.VSAM P
WHERE UIDVSAM NOT IN (
    SELECT UIDVSAM
    FROM PREP_OPENLOOP.VSAM
) AND P.BACTIVO = 1;

Select * from PREP_OPENLOOP.VSAM 
WHERE SCSN = '';

--VALIDADORVSAM
SELECT *
FROM PREP_CATALOGOS.VALIDADORVSAM P
WHERE UIDVALIDADORVSAM NOT IN (
    SELECT UIDVALIDADORVSAM
    FROM PREP_OPENLOOP.VALIDADORVSAM
) AND P.BACTIVO = 1;

Select * from PREP_OPENLOOP.VALIDADORVSAM 
WHERE UIDVALIDADORVSAM = '';

--Autobuses
SELECT *
FROM PREP_CATALOGOS.AUTOBUSES P
WHERE UIDAUTOBUS NOT IN (
    SELECT UIDAUTOBUS
    FROM PREP_OPENLOOP.AUTOBUSES
) AND P.BACTIVO = 1;

Select * from PREP_OPENLOOP.AUTOBUSES 
WHERE SNUMECO = '';

--AutobusesValidador
SELECT *
FROM PREP_CATALOGOS.AUTOBUSVALIDADOR P
WHERE UIDAUTOBUS NOT IN (
    SELECT UIDAUTOBUS
    FROM PREP_OPENLOOP.AUTOBUSVALIDADOR
) AND P.BACTIVO = 1;

Select * from PREP_OPENLOOP.AUTOBUSVALIDADOR 
WHERE UIDAUTOBUS = '';