
---Credencializacion.Tarjetas.Creada

	Por rango :
	
	SELECT M.DTFECHACREACION ,M.INUMEROMONEDERO,M.INUMEROTARJETA,M.SPANHASH,M.UIDMONEDERO,M.UIDTIPOTARIFA , m.BACTIVO,m.BBAJA ,m.SESTATUSMONEDERO  FROM  
	SINCRONIZADOR.MONEDERO m WHERE m.INUMEROTARJETA IN (
		'5000000000980340','5000000000980341','5000000000980342','5000000000980343',
		'5000000000980344','5000000000980345','5000000000980346','5000000000980347',
		'5000000000980348','5000000000980349','5000000000980350','5000000000980351','5000000000980352',
		'5000000000980353','5000000000980354','5000000000980355','5000000000980356','5000000000980357',
		'5000000000980358','5000000000980359'
	)
	ORDER BY m.DTFECHACREACION DESC;

---Credencializacion.App.Creada
	SELECT * FROM PREP_SINCRONIZADOR.CAMBIOSMONEDERO c WHERE c.STARJETA  ='1000000001100412' ORDER BY c.DTFECHACREACION DESC;


---Validador.VentaSaldo

	SELECT COUNT(*) FROM PREP_SINCRONIZADOR.CAMBIOSMONEDERO c WHERE c.STARJETA='9899982186677318' ORDER BY c.DTFECHACREACION DESC;

	SELECT COUNT(*) FROM PREP_SINCRONIZADOR.CAMBIOSMONEDERO c WHERE c .STARJETA ='9899982186677319' ORDER BY c.DTFECHACREACION DESC;

--*Cuadre para saber saldos y debitaciones de SINCRONIZADOR y los demas esquemas

	SELECT 
	 U4.INUMMONEDERO ,
	U2.DSALDO AS TICKETS,U2.SESTATUS  ,
	U3.DSALDO AS MONEDERO,U3.SESTATUS,
	U4.DSALDO  AS MQ_SALDO,
	U5.DSALDO  AS MC_SALDO,
	u6.DSALDO  AS PAGOS,
	U3.UIDESTATUS AS UIESTATUSCUENTA_MONEDERO,U1.UIDESTADODECUENTA
	FROM  PREP_APP.ESTADODECUENTA U1
	INNER JOIN PREP_APPTICKETS.ESTADODECUENTA U2 ON U1.UIDESTADODECUENTA=U2.UIDESTADODECUENTA 
	INNER JOIN PREP_MONEDEROCONSULTAS.ESTADODECUENTA U3 ON U1.UIDESTADODECUENTA =U3.UIDESTADODECUENTA
	INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA U4 ON U1.UIDESTADODECUENTA =U4.UIDESTADODECUENTA
	INNER JOIN PREP_APPMONEDEROCOMMAND.ESTADODECUENTA U5 ON U1.UIDESTADODECUENTA =U5.UIDESTADODECUENTA
	INNER JOIN PREP_PAGOS.ESTADODECUENTA U6 ON U1.UIDESTADODECUENTA =U6.UIDESTADODECUENTA
	WHERE U1.UIDMONEDERO IN ( SELECT  M.UIDMONEDERO FROM  PREP_SINCRONIZADOR.MONEDERO m WHERE m.INUMEROTARJETA IN ('9899982186677318','9899982186677319'))
	ORDER  BY U1.DTFECHAULTIMAOPERACION DESC

*Movimientos de las tarjetas

	SELECT c.DTFECHACREACION ,c.* FROM PREP_SINCRONIZADOR.CAMBIOSMONEDERO c
	INNER JOIN PREP_SINCRONIZADOR.MONEDERO m ON c.STARJETA =m.INUMEROTARJETA
	WHERE m.UIDMONEDERO IN 
	(
		SELECT  M.UIDMONEDERO FROM  PREP_SINCRONIZADOR.MONEDERO m WHERE m.INUMEROTARJETA IN ('9899982186677318','9899982186677319')
	)
	AND
	c.DTFECHACREACION >TO_DATE('15-06-2025 00:00:00', 'DD-MM-YYYY HH24:MI:SS') 
	AND    
	c.DTFECHACREACION <TO_DATE('15-07-2025 23:59:59', 'DD-MM-YYYY HH24:MI:SS')
	ORDER BY m.INUMEROTARJETA ,c.DTFECHACREACION DESC



---Catalogos.Motivos.Creacion , Catalogos.Motivos.Creacion.200 , Catalogos.Motivos.Actualizacion.200 , Catalogos.Motivos.Actualizacion.500

	SELECT m.BACTIVO ,m.BBAJA ,m.* FROM PREP_APPTICKETS.MOTIVOS m WHERE m.SMOTIVO IN ('QAReplicasMOn200' ,'QAReplicaCreden500')
	
	SELECT m.SMOTIVO , m.UIDMOTIVO ,m2.UIDMOTIVO  FROM PREP_CATALOGOS.MOTIVOS m 
	LEFT JOIN PREP_APPTICKETS.MOTIVOS m2  ON m.UIDMOTIVO =m2.UIDMOTIVO 
	WHERE m.SMOTIVO IN ('QAReplicasMOn200' ,'QAReplicaCreden500')


--- Catalogos.TipoTarifas.Actualizacion

	SELECT t.DTFECHAULTMOD ,t.* FROM PREP_SINCRONIZADOR.TIPOTARIFAS  t WHERE t.STIPOTARIFA ='Héroe Ciudadano  REP'
	SELECT t.* FROM PREP_APPTICKETS.TIPOSTARIFA   t WHERE t.STIPOTARIFA ='Héroe Ciudadano  REP'

	SELECT m.STIPOTARIFA , m.UIDTIPOTARIFA ,m2.UIDTIPOTARIFA  FROM PREP_CATALOGOS.TIPOTARIFAS  m 
	LEFT JOIN PREP_APPTICKETS.TIPOSTARIFA m2  ON m.UIDTIPOTARIFA =m2.UIDTIPOTARIFA 
	WHERE m.STIPOTARIFA IN ('Héroe Ciudadano  REP')

    SELECT m.STIPOTARIFA , m.UIDTIPOTARIFA ,m2.UIDTIPOTARIFA  FROM PREP_CATALOGOS.TIPOTARIFAS  m 
	LEFT JOIN PREP_SINCRONIZADOR.TIPOTARIFAS  m2  ON m.UIDTIPOTARIFA =m2.UIDTIPOTARIFA 
	WHERE m.STIPOTARIFA IN ('Héroe Ciudadano  REP')


---Catalogos.Vsam.Creacion	, Catalogos.Vsam.Actualizacion	
	
	SELECT  v.SCSN , v.UIDVSAM , v2.UIDVSAM  FROM PREP_CATALOGOS.VSAM v LEFT JOIN 
	PREP_SINCRONIZADOR.VSAM v2  ON v.UIDVSAM = v2.UIDVSAM 
	ORDER BY v.DTFECHACREACION DESC

---Catalogos.Validador.Creacion	, Catalogos.Validador.Actualizacion	

	SELECT v.SCLAVE , v.UIDVALIDADOR , v2.UIDVALIDADOR  FROM PREP_CATALOGOS.VALIDADORES v LEFT JOIN 
	PREP_SINCRONIZADOR.VALIDADORES v2  ON v.UIDVALIDADOR = v2.UIDVALIDADOR 
	ORDER BY v.DTFECHACREACION DESC


---- Catalogos.ValidadorVsam
	
	SELECT val.SCLAVE  , vsam.SCSN,val.SCLAVE,val.SNUMEROSERIE,val.SVALIDADOR,vvsam2.BACTIVO,vvsam2.BBAJA,vvsam2.ISLOT ,vvsam2.DTFECHACREACION ,vvsam2.DTFECHAULTMOD ,vvsam2.DTFECHABAJA 
	FROM PREP_SINCRONIZADOR.VALIDADORES val 
	INNER JOIN PREP_SINCRONIZADOR.VALIDADORVSAM vvsam2 ON val.UIDVALIDADOR =vvsam2.UIDVALIDADOR 
	INNER  JOIN PREP_SINCRONIZADOR.VSAM vsam ON vsam.UIDVSAM =vvsam2.UIDVSAM 
	ORDER BY vvsam2.DTFECHACREACION DESC;
	

---- Catalogos.Rutas
	
	SELECT r.SCLAVERUTA,r.SDESCRIPCION,r.SRUTA,r.BACTIVO,r.BBAJA,r.* FROM PREP_SINCRONIZADOR.RUTAS r ORDER BY r.DTFECHACREACION DESC;



---- Catalogos.Autobuses

	SELECT a.DTFECHACREACION , a.BACTIVO , a.BBAJA ,a.DTFECHAULTMOD ,a.DTFECHABAJA ,a.* FROM PREP_SINCRONIZADOR.AUTOBUSES a ORDER BY a.DTFECHACREACION DESC;


---- Catalogos.AutobusRutaChofer 

	SELECT a.UIDAUTOBUSRUTACHOFER,a.UIDCHOFER ,a2.SPLACAS,r.SRUTA,a.BACTIVO,a.BBAJA ,a.* FROM PREP_SINCRONIZADOR.AUTOBUSRUTACHOFER a 
	LEFT JOIN PREP_SINCRONIZADOR.AUTOBUSES a2 ON a.UIDAUTOBUS =a2.UIDAUTOBUS 
	LEFT JOIN PREP_SINCRONIZADOR.RUTAS r ON a.UIDRUTA =r.UIDRUTA  
	ORDER BY a.DTFECHACREACION DESC;


---- Catalogos.AutobusValidador

	SELECT v.SCLAVE,v.SNUMEROSERIE,a2.SPLACAS,a2.SNUMECO ,a.UIDUSUARIOBAJA ,a.DTFECHABAJA,a.BACTIVO ,a.BBAJA ,v2.* ,a.*,v.*,a2.*,v3.* FROM PREP_SINCRONIZADOR.AUTOBUSVALIDADOR  a 
	LEFT JOIN PREP_SINCRONIZADOR.AUTOBUSES a2 ON a.UIDAUTOBUS =a2.UIDAUTOBUS 
	LEFT JOIN PREP_SINCRONIZADOR.VALIDADORES v ON a.UIDVALIDADOR =v.UIDVALIDADOR 
	LEFT JOIN PREP_SINCRONIZADOR.VALIDADORVSAM v2 ON v.UIDVALIDADOR =v2.UIDVALIDADOR 
	LEFT JOIN PREP_SINCRONIZADOR.VSAM v3  ON v2.UIDVSAM =v3.UIDVSAM 
	WHERE a.UIDAUTOBUS ='df2a6eae-4c51-4b2c-b0e4-6b4e3e4b6a7c'
	ORDER BY a.DTFECHACREACION DESC;





