
WITH BASE_ABONOS AS (select MOE.INUMMONEDERO,
XW.inumerotarjeta as num_tarjeta,
MOE.SESTATUS,
moe.STIPOTARIFA,
MOE.DSALDO AS SALDO_MONEDERO,
XW.SALDO as SALDO_TARJETA,
         CASE WHEN SM.ICONTADORRECARGA = SM.ICONTADORRECARGAAPLICADA THEN (MOE.DSALDO * -1) + SALDO
         ELSE ((MOE.DSALDO * -1) + (select SUM(DSALDOACTUAL) FROM SINCRONIZADOR.cambiosmonedero
         where 1=1
         AND ICONTADORRECARGA > SM.ICONTADORRECARGAAPLICADA
         AND ICONTADORRECARGA <= SM.ICONTADORRECARGA
         and STARJETA = SM.INUMEROTARJETA )) + SALDO END
         AS MONTO_ABONO,
MOE.DTFECHAULTIMAOPERACION AS ULT_DEBITACION,
MOE.DTFECHAULTIMOABONO as ULT_ABONO,
case  when XW.SALDO>0 then 'SI' else 'NO' end as CON_SALDO_TARJETA,
--CASE WHEN EXISTS (
--    SELECT 1
--    FROM APPMONEDEROCOMMAND.TARJETAUSUARIO
--    WHERE bactivo = 1 AND bbaja = 0 and XW.inumerotarjeta = SNUMEROTARJETA
--  ) THEN 'VINCULADO APP' ELSE 'SIN APP' END AS VINCULADO_APP,
CASE WHEN APT.SNUMEROTARJETA is null THEN 'SIN APP' ELSE 'VINCULADO APP' END AS VINCULADO_APP,
CASE
WHEN abs(MOE.DSALDO) >=0 and abs(MOE.DSALDO) <=100 THEN '0 - 100'
WHEN abs(MOE.DSALDO) >=101 and abs(MOE.DSALDO) <=300 THEN '101 - 300'
WHEN abs(MOE.DSALDO) >=301 and abs(MOE.DSALDO) <=500 THEN '301 - 500'
ELSE '501 O MAS'
END AS RANGO,
SM.ICONTADORRECARGA AS LTC_TOTALES,
SM.ICONTADORRECARGAAPLICADA AS LTC_APLICADO
from monederoconsultas.estadodecuenta MOE
LEFT JOIN sincronizador.monedero XX on MOE.UIDMONEDERO = XX.UIDMONEDERO
INNER JOIN (
select inumerotarjeta,
MAX(DTFECHAOPERACION) KEEP (DENSE_RANK LAST ORDER BY DTFECHAOPERACION) AS DTFECHAOPERACION
,MAX(DSALDO) KEEP (DENSE_RANK LAST ORDER BY DTFECHAOPERACION) AS SALDO
,MAX(IERROR) KEEP (DENSE_RANK LAST ORDER BY DTFECHAOPERACION) AS IERROR
,MAX(loadtranscounter) AS loadtranscounter2
FROM SINCRONIZADOR.DETALLESINCRONIZACIONTRANSACCIONESNFC
where 1=1
AND SINCIDENCIA not like 'DEB. PEND.%'
AND SINCIDENCIA not like 'SIM. DEB. PEND.%'-->CONDICION PARA EVITAR AGARRAR LOS QUE SEAN REPROCESOS

GROUP BY inumerotarjeta
) XW ON XW.inumerotarjeta = XX.inumerotarjeta
LEFT JOIN APPMONEDEROCOMMAND.TARJETAUSUARIO APT on APT.SNUMEROTARJETA = XW.inumerotarjeta and  APT.bactivo = 1 AND APT.bbaja = 0
JOIN SINCRONIZADOR.MONEDERO SM on XW.iNumeroTarjeta = SM.INUMEROTARJETA
LEFT JOIN monederoconsultas.movimientos MM on MM.UIDMONEDERO = SM.UIDMONEDERO AND sOperacion like 'REVERSA OXXO WAY'
where
MOE.sEstatus = 'ACTIVO'
--AND MOE.dSaldo < -12
and XW.inumerotarjeta !=0
and moe.UIDESTATUSTARJETA = '1f752e96-0ecc-4765-b163-259865bfabf0'
and moe.UIDESTATUS = '5e879806-6e1d-4d5b-9610-25f2a681b637'
--AND SM.ICONTADORRECARGA = SM.ICONTADORRECARGAAPLICADA
--and (
--MOE.DTFECHAULTIMAOPERACION >= sysdate - 60 or MOE.DTFECHAULTIMOABONO >= sysdate -60 --> validar que el ultimo abono o debitacion sea dentro de los ultimos 60 dias
--)
--AND (( -1 * MOE.DSALDO) + XW.SALDO) >0
)
SELECT INUMMONEDERO, NUM_TARJETA, SESTATUS, SALDO_MONEDERO, SALDO_TARJETA, MONTO_ABONO, ULT_DEBITACION, ULT_ABONO, CON_SALDO_TARJETA, VINCULADO_APP, RANGO,
CASE
WHEN MONTO_ABONO >=0 and MONTO_ABONO <=100 THEN '0 - 100'
WHEN MONTO_ABONO >=101 and MONTO_ABONO <=300 THEN '101 - 300'
WHEN MONTO_ABONO >=301 and MONTO_ABONO <=500 THEN '301 - 500'
ELSE '501 O MAS'
END AS RANGO_ABONOS,
LTC_TOTALES,
LTC_APLICADO
FROM BASE_ABONOS
WHERE
    1=1
    AND MONTO_ABONO>=1
 ;









---------------------------------VERSION DOS USADA PARA ALARMA

WITH BASE_ABONOS AS (select MOE.INUMMONEDERO,
XW.inumerotarjeta as num_tarjeta,
MOE.SESTATUS,
MOE.DSALDO AS SALDO_MONEDERO,
MOE.STIPOTARIFA,
XW.SALDO as SALDO_TARJETA,
         CASE WHEN SM.ICONTADORRECARGA = SM.ICONTADORRECARGAAPLICADA THEN (MOE.DSALDO * -1) + SALDO
         ELSE ((MOE.DSALDO * -1) + (select SUM(DSALDOACTUAL) FROM SINCRONIZADOR.cambiosmonedero
         where 1=1
         AND ICONTADORRECARGA > SM.ICONTADORRECARGAAPLICADA
         AND ICONTADORRECARGA <= SM.ICONTADORRECARGA
         and STARJETA = SM.INUMEROTARJETA )) + SALDO END
         AS MONTO_ABONO,

         CASE WHEN SM.ICONTADORRECARGA = SM.ICONTADORRECARGAAPLICADA THEN SALDO
         ELSE ((select SUM(DSALDOACTUAL) FROM SINCRONIZADOR.cambiosmonedero
         where 1=1
         AND ICONTADORRECARGA > SM.ICONTADORRECARGAAPLICADA
         AND ICONTADORRECARGA <= SM.ICONTADORRECARGA
         and STARJETA = SM.INUMEROTARJETA )) + SALDO END
             as SALDO_TARJETA_FINAL,
MOE.DTFECHAULTIMAOPERACION AS ULT_DEBITACION,
MOE.DTFECHAULTIMOABONO as ULT_ABONO,
case  when XW.SALDO>0 then 'SI' else 'NO' end as CON_SALDO_TARJETA,
--CASE WHEN EXISTS (
--    SELECT 1
--    FROM APPMONEDEROCOMMAND.TARJETAUSUARIO
--    WHERE bactivo = 1 AND bbaja = 0 and XW.inumerotarjeta = SNUMEROTARJETA
--  ) THEN 'VINCULADO APP' ELSE 'SIN APP' END AS VINCULADO_APP,
CASE WHEN APT.SNUMEROTARJETA is null THEN 'SIN APP' ELSE 'VINCULADO APP' END AS VINCULADO_APP,
CASE
WHEN abs(MOE.DSALDO) >=0 and abs(MOE.DSALDO) <=100 THEN '0 - 100'
WHEN abs(MOE.DSALDO) >=101 and abs(MOE.DSALDO) <=300 THEN '101 - 300'
WHEN abs(MOE.DSALDO) >=301 and abs(MOE.DSALDO) <=500 THEN '301 - 500'
ELSE '501 O MAS'
END AS RANGO,
SM.ICONTADORRECARGA AS LTC_TOTALES,
SM.ICONTADORRECARGAAPLICADA AS LTC_APLICADO
from monederoconsultas.estadodecuenta MOE
LEFT JOIN sincronizador.monedero XX on MOE.UIDMONEDERO = XX.UIDMONEDERO
INNER JOIN (
select inumerotarjeta,
MAX(DTFECHAOPERACION) KEEP (DENSE_RANK LAST ORDER BY DTFECHAOPERACION) AS DTFECHAOPERACION
,MAX(DSALDO) KEEP (DENSE_RANK LAST ORDER BY DTFECHAOPERACION) AS SALDO
,MAX(IERROR) KEEP (DENSE_RANK LAST ORDER BY DTFECHAOPERACION) AS IERROR
,MAX(loadtranscounter) AS loadtranscounter2
FROM SINCRONIZADOR.DETALLESINCRONIZACIONTRANSACCIONESNFC
where 1=1
AND SINCIDENCIA not like 'DEB. PEND.%'
AND SINCIDENCIA not like 'SIM. DEB. PEND.%'-->CONDICION PARA EVITAR AGARRAR LOS QUE SEAN REPROCESOS

GROUP BY inumerotarjeta
) XW ON XW.inumerotarjeta = XX.inumerotarjeta
LEFT JOIN APPMONEDEROCOMMAND.TARJETAUSUARIO APT on APT.SNUMEROTARJETA = XW.inumerotarjeta and  APT.bactivo = 1 AND APT.bbaja = 0
JOIN SINCRONIZADOR.MONEDERO SM on XW.iNumeroTarjeta = SM.INUMEROTARJETA
LEFT JOIN monederoconsultas.movimientos MM on MM.UIDMONEDERO = SM.UIDMONEDERO AND sOperacion like 'REVERSA OXXO WAY'
where
MOE.sEstatus = 'ACTIVO'
--AND MOE.dSaldo < -12
and XW.inumerotarjeta !=0
and moe.UIDESTATUSTARJETA = '1f752e96-0ecc-4765-b163-259865bfabf0'
and moe.UIDESTATUS = '5e879806-6e1d-4d5b-9610-25f2a681b637'
--AND SM.ICONTADORRECARGA = SM.ICONTADORRECARGAAPLICADA
  ---Se considera un GAP de 20 minutos de diferencia para ser considerado con error de saldo mayor en tarjeta que en monedero entre la hora actual y la diferencia entra la ultima debitacion o abono para evitar un tema que sean tarjetas que estan en proceso de abono o debitacion
and (
( (sysdate - 6/24) - MOE.DTFECHAULTIMAOPERACION) > NUMTODSINTERVAL(20, 'MINUTE')
    and
(  (sysdate -6/24) - MOE.DTFECHAULTIMOABONO ) > NUMTODSINTERVAL(20, 'MINUTE')
)
--AND (( -1 * MOE.DSALDO) + XW.SALDO) >0
)
SELECT
sysdate-6/24 FechaInsertado,
1 Vuelta,
--     INUMMONEDERO,
       NUM_TARJETA
--        ,STIPOTARIFA,SESTATUS,SALDO_MONEDERO,SALDO_TARJETA,SALDO_TARJETA_FINAL,MONTO_ABONO,ULT_DEBITACION,ULT_ABONO,CON_SALDO_TARJETA,VINCULADO_APP,RANGO,
--        CASE
-- WHEN MONTO_ABONO >=0 and MONTO_ABONO <=100 THEN '0 - 100'
-- WHEN MONTO_ABONO >=101 and MONTO_ABONO <=300 THEN '101 - 300'
-- WHEN MONTO_ABONO >=301 and MONTO_ABONO <=500 THEN '301 - 500'
-- ELSE '501 O MAS'
-- END AS RANGO_ABONOS,
--        LTC_TOTALES,
--        LTC_APLICADO
FROM BASE_ABONOS
WHERE
    1=1
    and (
        STIPOTARIFA= 'Tarifa General' and MONTO_ABONO>12 --> para tarifa generales detectar que ya tiene diferencia de 12 pesos a favor de tarjeta general
        or
        (STIPOTARIFA!='Tarifa General' and MONTO_ABONO>5)  --> para cualquiera menos tarifa generales detectar que ya tiene diferencia de 5 pesos a favor de tarjeta social
        )
and MONTO_ABONO <500





















