



10792	06/05/2025	5000000000223190	5000000000223190	EsperaRetro	Posible tema LTC	#N/D

define numBusqueda = 5000000000223190;
select DTFECHAOPERACION, INUMEROTARJETA, DMONTOCOBRADO, BPROCESADO, IREINTENTOS, ICONTADORTRANSACCIONES, STIPOTARIFA, DTFECHACREACION, DTFECHAULTMOD,
DTFECHABAJA, ITRANSBORDO, DSALDO, DSALDOANTERIOR, SINCIDENCIA, IDVALIDADOR,
TOKENTRANSACCION, LOADTRANSCOUNTER, IERROR, BDEBITADO, BFIRMADO, CERTIFICADO,
DATEHSM, TRANSVALUE, PANHASH FROM SINCRONIZADOR.DETALLESINCRONIZACIONTRANSACCIONESNFC nfc where inumerotarjeta =&numBusqueda and bdebitado = 1 order by dtfechaoperacion desc;
select DTFECHAOPERACION, INUMEROTARJETA, DMONTOCOBRADO, BPROCESADO, IREINTENTOS, ICONTADORTRANSACCIONES, STIPOTARIFA, DTFECHACREACION, DTFECHAULTMOD,
DTFECHABAJA, ITRANSBORDO, DSALDO, DSALDOANTERIOR, SINCIDENCIA, IDVALIDADOR,
TOKENTRANSACCION, LOADTRANSCOUNTER, IERROR, BDEBITADO, BFIRMADO, CERTIFICADO,
DATEHSM, TRANSVALUE, PANHASH  FROM SINCRONIZADOR.DETALLESINCRONIZACIONTRANSACCIONESNFC nfc where inumerotarjeta =&numBusqueda order by dtfechaoperacion desc;
select * from monederoconsultas.estadodecuenta where inumtarjeta =&numBusqueda;
select icontadorrecarga, icontadorrecargaaplicada FROM SINCRONIZADOR.monedero where inumerotarjeta =&numBusqueda;
select * FROM SINCRONIZADOR.cambiosmonedero where starjeta=&numBusqueda order by icontadorrecarga asc;


-- -- SIN ERROR
--
-- update SINCRONIZADOR.cambiosmonedero set uidlistacuentas = '00000000-0000-0000-0000-000000000000' where uidcambiosmonedero = 'ecd074a4-d1f4-4c9b-bc95-17d64678564b'; commit;

--misma tarjeta que el anterior


