



9253	23/04/2025	5000000000945505	5000000000945505	EsperaRetro	Posible tema LTC	#N/D


define numBusqueda = 5000000000945505;
select DTFECHAOPERACION, INUMEROTARJETA, DMONTOCOBRADO, BPROCESADO, ICONTADORTRANSACCIONES, DTFECHACREACION, DTFECHAULTMOD,
DTFECHABAJA, ITRANSBORDO, DSALDO, DSALDOANTERIOR, SINCIDENCIA, IDVALIDADOR,
TOKENTRANSACCION, LOADTRANSCOUNTER, IERROR, BDEBITADO, BFIRMADO, CERTIFICADO,
DATEHSM, TRANSVALUE, PANHASH FROM SINCRONIZADOR.DETALLESINCRONIZACIONTRANSACCIONESNFC nfc where inumerotarjeta =&numBusqueda and bdebitado = 1 order by dtfechaoperacion desc;
select DTFECHAOPERACION, INUMEROTARJETA, DMONTOCOBRADO, BPROCESADO, ICONTADORTRANSACCIONES, DTFECHACREACION, DTFECHAULTMOD,
DTFECHABAJA, ITRANSBORDO, DSALDO, DSALDOANTERIOR, SINCIDENCIA, IDVALIDADOR,
TOKENTRANSACCION, LOADTRANSCOUNTER, IERROR, BDEBITADO, BFIRMADO, CERTIFICADO,
DATEHSM, TRANSVALUE, PANHASH  FROM SINCRONIZADOR.DETALLESINCRONIZACIONTRANSACCIONESNFC nfc where inumerotarjeta =&numBusqueda order by dtfechaoperacion desc;
select * from monederoconsultas.estadodecuenta where inumtarjeta =&numBusqueda;
select icontadorrecarga, icontadorrecargaaplicada FROM SINCRONIZADOR.monedero where inumerotarjeta =&numBusqueda;
select * FROM SINCRONIZADOR.cambiosmonedero where starjeta=&numBusqueda order by icontadorrecarga asc;


-- -- SIN ERROR
-- --
update SINCRONIZADOR.cambiosmonedero set uidlistacuentas = '00000000-0000-0000-0000-000000000000' where uidcambiosmonedero = '7ff26fd6-6337-4da1-a32f-9cbf7751da80'; commit;

--misma tarjeta que el anterior


