*************************** PRELIBERACIÓN *****************************

ALTER TABLE PAGOS.ORDENES ADD SESTATUS VARCHAR2(50) NULL;
COMMENT ON COLUMN PAGOS.ORDENES.SESTATUS IS 'Estatus de la orden.';

ALTER TABLE PAGOS.ORDENES ADD SFOLIO VARCHAR2(50) NULL;
COMMENT ON COLUMN PAGOS.ORDENES.SFOLIO IS 'Folio de venta.';

ALTER TABLE PAGOS.ORDENES ADD DTFECHAOPERACION TIMESTAMP NULL;
COMMENT ON COLUMN PAGOS.ORDENES.DTFECHAOPERACION IS 'Fecha de operación.';