*************************** PRELIBERACIÓN *****************************

ALTER TABLE APPMONEDEROQUERY.MOVIMIENTOSOPERACIONES ADD UIDTIPOOPERACION VARCHAR2(36) NULL;
COMMENT ON COLUMN APPMONEDEROQUERY.MOVIMIENTOSOPERACIONES.UIDTIPOOPERACION IS 'Identificador de tipo de operación.'; 

ALTER TABLE APPMONEDEROQUERY.MOVIMIENTOSOPERACIONES ADD UIDTIPOMOVIMIENTO VARCHAR2(36) NULL;
COMMENT ON COLUMN APPMONEDEROQUERY.MOVIMIENTOSOPERACIONES.UIDTIPOMOVIMIENTO IS 'Identificador de tipo de movimiento.'; 

ALTER TABLE APPMONEDEROQUERY.MOVIMIENTOSOPERACIONES ADD INUMEROTARJETAORIGEN NUMBER(16) NULL;
COMMENT ON COLUMN APPMONEDEROQUERY.MOVIMIENTOSOPERACIONES.INUMEROTARJETAORIGEN IS 'Número de la tarjeta origen del traspaso.'; 

ALTER TABLE APPMONEDEROQUERY.MOVIMIENTOSOPERACIONES ADD INUMEROTARJETADESTINO NUMBER(16) NULL;
COMMENT ON COLUMN APPMONEDEROQUERY.MOVIMIENTOSOPERACIONES.INUMEROTARJETADESTINO IS 'Número de la tarjeta destino del traspaso.'; 


CREATE TABLE APPMONEDEROQUERY.TRASPASOS(
    UIDOPERACION VARCHAR2(36) NOT NULL,
    UIDMONEDEROORIGEN VARCHAR2(36) NOT NULL,
    UIDMONEDERODESTINO VARCHAR2(36) NOT NULL,
    INUMEROTARJETAORIGEN NUMBER(16,0) NOT NULL,
    INUMEROTARJETADESTINO NUMBER(16,0) NOT NULL,
    DMONTO NUMBER(18,2) NOT NULL,
    IFOLIOOPERACION NUMBER(16,0) NOT NULL,
    DTFECHAOPERACION TIMESTAMP NOT NULL,
    CONSTRAINT PK_TRASPASOS PRIMARY KEY (UIDOPERACION)
)
TABLESPACE DATA;

COMMENT ON COLUMN APPMONEDEROQUERY.TRASPASOS.UIDOPERACION IS 'IDENTIFICADOR ÚNICO DEL TRASPASO';
COMMENT ON COLUMN APPMONEDEROQUERY.TRASPASOS.UIDMONEDEROORIGEN IS 'IDENTIFICADOR DEL MONEDERO ORIGEN';
COMMENT ON COLUMN APPMONEDEROQUERY.TRASPASOS.UIDMONEDERODESTINO IS 'IDENTIFICADOR DEL MONEDERO DESTINO';
COMMENT ON COLUMN APPMONEDEROQUERY.TRASPASOS.INUMEROTARJETAORIGEN IS 'NÚMERO DE LA TARJETA ORIGEN';
COMMENT ON COLUMN APPMONEDEROQUERY.TRASPASOS.INUMEROTARJETADESTINO IS 'NÚMERO DE LA TARJETA DESTINO';
COMMENT ON COLUMN APPMONEDEROQUERY.TRASPASOS.DMONTO IS 'MONTO DE LA OPERACIÓN';
COMMENT ON COLUMN APPMONEDEROQUERY.TRASPASOS.IFOLIOOPERACION IS 'FOLIO DE LA OPERACIÓN';
COMMENT ON COLUMN APPMONEDEROQUERY.TRASPASOS.DTFECHAOPERACION IS 'FECHA DE LA OPERACIÓN DEL REGISTRO';


CREATE TABLE APPMONEDEROQUERY.TIPOSTARIFA(
    UIDTIPOTARIFA VARCHAR2(36) NOT NULL,
    STIPOTARIFA VARCHAR2(100) NULL,
    SCLAVETIPOTARIFA VARCHAR2(10) NULL,
    ITIPOTARJETA NUMBER DEFAULT 0,
    CONSTRAINT TARIFAS_PK PRIMARY KEY (UIDTIPOTARIFA)
)
TABLESPACE DATA;

COMMENT ON COLUMN APPMONEDEROQUERY.TIPOSTARIFA.UIDTIPOTARIFA IS 'IDENTIFICADOR ÚNICO DEL TIPO DE TARIFA';
COMMENT ON COLUMN APPMONEDEROQUERY.TIPOSTARIFA.STIPOTARIFA IS 'NOMBRE DEL TIPO DE TARIFA';
COMMENT ON COLUMN APPMONEDEROQUERY.TIPOSTARIFA.SCLAVETIPOTARIFA IS 'CLAVE DEL TIPO DE TARIFA';
COMMENT ON COLUMN APPMONEDEROQUERY.TIPOSTARIFA.ITIPOTARJETA IS 'INDICA EL TIPO DE TARJETA DE LA TARIFA';

MERGE INTO APPMONEDEROQUERY.TIPOSTARIFA D
USING CATALOGOS.TIPOTARIFAS O
ON (D.UIDTIPOTARIFA = O.UIDTIPOTARIFA)
WHEN MATCHED THEN
    UPDATE SET 
        D.STIPOTARIFA = O.STIPOTARIFA,
        D.SCLAVETIPOTARIFA = O.SCLAVETIPOTARIFA,
        D.ITIPOTARJETA = O.ITIPOTARJETA
WHEN NOT MATCHED THEN
    INSERT (UIDTIPOTARIFA, STIPOTARIFA, SCLAVETIPOTARIFA, ITIPOTARJETA)
    VALUES (O.UIDTIPOTARIFA, O.STIPOTARIFA, O.SCLAVETIPOTARIFA, O.ITIPOTARJETA);



*************************** LIBERACIÓN *****************************

MERGE INTO APPMONEDEROQUERY.MOVIMIENTOSOPERACIONES M USING (
--TRASPASO CARGOS
SELECT DISTINCT M.UIDMOVIMIENTOS,M.UIDTIPOOPERACION,M.UIDTIPOMOVIMIENTO,M.INUMMONEDERO MONORIGEN, E.INUMTARJETA MONDESTINO
FROM MONEDEROCONSULTAS.MOVIMIENTOS M INNER JOIN (
SELECT UIDMOVIMIENTOS,UIDOPERACION,UIDTIPOOPERACION,UIDMONEDERO,INUMMONEDERO,SOPERACION, IFOLIOMOVIMIENTO
FROM MONEDEROCONSULTAS.MOVIMIENTOS WHERE UPPER(SOPERACION) = 'TRASPASO'
AND UIDTIPOMOVIMIENTO = 'ef008eb7-ea41-46bb-814e-f94979913ceb'
) MM ON MM.UIDOPERACION = M.UIDOPERACION AND MM.IFOLIOMOVIMIENTO = M.IFOLIOMOVIMIENTO
INNER JOIN MONEDEROCONSULTAS.ESTADODECUENTA E ON E.INUMMONEDERO = MM.INUMMONEDERO
WHERE UPPER(M.SOPERACION) = 'TRASPASO'
AND M.UIDTIPOMOVIMIENTO = '58956590-095e-4ff5-b1b3-20b2892db778'
--AND M.UIDMONEDERO = '9162abc3-33c9-4608-bd2e-1acf4d3895c7'
UNION ALL
--TRASPASO ABONOS
SELECT DISTINCT M.UIDMOVIMIENTOS,M.UIDTIPOOPERACION,M.UIDTIPOMOVIMIENTO,MM.INUMMONEDERO MONORIGEN, E.INUMTARJETA MONDESTINO
FROM MONEDEROCONSULTAS.MOVIMIENTOS M INNER JOIN (
SELECT UIDMOVIMIENTOS,UIDOPERACION,UIDTIPOOPERACION,UIDMONEDERO,INUMMONEDERO,SOPERACION, IFOLIOMOVIMIENTO
FROM MONEDEROCONSULTAS.MOVIMIENTOS WHERE UPPER(SOPERACION) = 'TRASPASO'
AND UIDTIPOMOVIMIENTO = '58956590-095e-4ff5-b1b3-20b2892db778'
) MM ON MM.UIDOPERACION = M.UIDOPERACION AND MM.IFOLIOMOVIMIENTO = M.IFOLIOMOVIMIENTO
INNER JOIN MONEDEROCONSULTAS.ESTADODECUENTA E ON E.INUMMONEDERO = M.INUMMONEDERO
WHERE UPPER(M.SOPERACION) = 'TRASPASO'
AND M.UIDTIPOMOVIMIENTO = 'ef008eb7-ea41-46bb-814e-f94979913ceb'
--AND MM.UIDMONEDERO = '9162abc3-33c9-4608-bd2e-1acf4d3895c7'
) S ON (S.UIDMOVIMIENTOS = M.UIDMOVIMIENTOS)
WHEN MATCHED THEN UPDATE 
SET M.uidtipooperacion = S.uidtipooperacion,
    M.uidtipomovimiento=S.uidtipomovimiento,
    M.inumerotarjetaorigen = S.MONORIGEN,
    M.inumerotarjetadestino = S.MONDESTINO
WHERE S.UIDMOVIMIENTOS = M.UIDMOVIMIENTOS;
COMMIT;


*******************************************************

-- CONSULTA PARA VALIDAR DIFERENCIAS DE MONEDEROS EN SUS FECHAS DE VIGENCIA EN APPMONEDEROQUERY
SELECT --DISTINCT U.UIDMONEDEROAPP UIDMONEDERO, P.DTFECHAINICIOPERIODO , P.DTFECHAFINPERIODO
    COUNT(0) AS discrepancias
        FROM CREDENCIALIZACION.USUARIOSTARJETAS u
        INNER JOIN CREDENCIALIZACION.PERIODOSTARJETAS p ON p.UIDMONEDERO = U.UIDMONEDEROAPP AND p.BACTIVO = 1
        INNER JOIN APPMONEDEROQUERY.ESTADODECUENTA e ON e.UIDMONEDERO = U.UIDMONEDEROAPP
    WHERE U.BACTIVO = 1 AND U.BBAJA = 0 AND U.UIDTIPOTARIFA <> '24665f64-1ef6-4404-b59a-3fd3cd74a9be'
        AND p.BACTIVO = 1 AND p.BBAJA = 0
        AND (e.DTFECHAFINVIGENCIA is null OR e.DTFECHAFINVIGENCIA <> P.DTFECHAFINPERIODO)

-- DIFERENCIA DE FECHAS DE VIGENCIA EN MONEDEROS
MERGE INTO APPMONEDEROQUERY.ESTADODECUENTA EDOCUENTA
USING (
    SELECT DISTINCT U.UIDMONEDEROAPP UIDMONEDERO,  P.DTFECHAINICIOPERIODO ,  P.DTFECHAFINPERIODO
        FROM CREDENCIALIZACION.USUARIOSTARJETAS u
        INNER JOIN CREDENCIALIZACION.PERIODOSTARJETAS p ON p.UIDMONEDERO = U.UIDMONEDEROAPP AND p.BACTIVO = 1
        INNER JOIN APPMONEDEROQUERY.ESTADODECUENTA e ON e.UIDMONEDERO = U.UIDMONEDEROAPP
    WHERE U.BACTIVO = 1 AND U.BBAJA = 0 AND U.UIDTIPOTARIFA <> '24665f64-1ef6-4404-b59a-3fd3cd74a9be'
        AND p.BACTIVO = 1 AND p.BBAJA = 0
        AND (e.DTFECHAFINVIGENCIA is null OR e.DTFECHAFINVIGENCIA <> P.DTFECHAFINPERIODO)) MONEDEROS
ON (EDOCUENTA.UIDMONEDERO = MONEDEROS.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET EDOCUENTA.DTFECHAINICIOVIGENCIA = MONEDEROS.DTFECHAINICIOVIGENCIA,
     EDOCUENTA.DTFECHAINICIOPERIODO = MONEDEROS.DTFECHAFINPERIODO

*******************************************************

-- CONSULTA PARA VALIDAR DIFERENCIAS DE TARJETAS EN SUS FECHAS DE VIGENCIA EN APPMONEDEROQUERY
SELECT --DISTINCT t.UIDMONEDERO, p.DTFECHAINICIOPERIODO , p.DTFECHAFINPERIODO, e.DTFECHAINICIOVIGENCIA, e.DTFECHAFINVIGENCIA--, p.UIDTARJETA 
    COUNT(0) AS discrepancias
        FROM CREDENCIALIZACION.TARJETAS t
            INNER JOIN CREDENCIALIZACION.USUARIOSTARJETAS u ON u.UIDTARJETA = t.UIDTARJETA
            INNER JOIN CREDENCIALIZACION.PERIODOSTARJETAS p ON p.UIDTARJETA = t.UIDTARJETA AND p.BACTIVO = 1
            INNER JOIN APPMONEDEROQUERY.ESTADODECUENTA e ON e.UIDTARJETA = t.UIDTARJETA
    WHERE t.BACTIVO = 1 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.UIDTIPOTARIFA <> '24665f64-1ef6-4404-b59a-3fd3cd74a9be' AND p.BACTIVO = 1
        AND e.DTFECHAFINVIGENCIA is null OR e.DTFECHAFINVIGENCIA <> P.DTFECHAFINPERIODO

-- DIFERENCIA DE FECHAS DE VIGENCIA EN TARJETAS
MERGE INTO APPMONEDEROQUERY.ESTADODECUENTA EDOCUENTA
USING (
    SELECT DISTINCT t.UIDMONEDERO, p.DTFECHAINICIOPERIODO , p.DTFECHAFINPERIODO
        FROM CREDENCIALIZACION.TARJETAS t
            INNER JOIN CREDENCIALIZACION.USUARIOSTARJETAS u ON u.UIDTARJETA = t.UIDTARJETA
            INNER JOIN CREDENCIALIZACION.PERIODOSTARJETAS p ON p.UIDTARJETA = t.UIDTARJETA AND p.BACTIVO = 1
            INNER JOIN APPMONEDEROQUERY.ESTADODECUENTA e ON e.UIDTARJETA = t.UIDTARJETA
    WHERE t.BACTIVO = 1 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.UIDTIPOTARIFA <> '24665f64-1ef6-4404-b59a-3fd3cd74a9be'
        AND e.DTFECHAFINVIGENCIA is null OR e.DTFECHAFINVIGENCIA <> P.DTFECHAFINPERIODO) TARJETAS
ON (EDOCUENTA.UIDMONEDERO = TARJETAS.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET EDOCUENTA.DTFECHAINICIOVIGENCIA = TARJETAS.DTFECHAINICIOPERIODO, EDOCUENTA.DTFECHAFINVIGENCIA = TARJETAS.DTFECHAFINPERIODO
