CREATE TABLE DISPOSITIVOS
(
  UIDDISPOSITIVOS VARCHAR2(36) NOT NULL 
, SNOMBRE VARCHAR2(100) NOT NULL 
, DTFECHACREACION TIMESTAMP NOT NULL
, DTFECHAMODIFICACION TIMESTAMP
, DTFECHABAJA TIMESTAMP
, BACTIVO NUMBER(1) DEFAULT 1 NOT NULL
, BBAJA NUMBER(1) DEFAULT 0 NOT NULL
, UIDUSUARIOCREACION VARCHAR2(36) NOT NULL 
, UIDUSUARIOMODIFICACION VARCHAR2(36)
, UIDUSUARIOBAJA VARCHAR2(36)
, CONSTRAINT DISPOSITIVOS_PK PRIMARY KEY 
  (
    UIDDISPOSITIVOS 
  )
  ENABLE 
)
TABLESPACE DATA;

COMMENT ON COLUMN DISPOSITIVOS.UIDDISPOSITIVOS IS 'IDENTIFICADOR DE LA TABLA';
COMMENT ON COLUMN DISPOSITIVOS.SNOMBRE IS 'NOMBRE DEL DISPOSITIVO';
COMMENT ON COLUMN DISPOSITIVOS.DTFECHACREACION IS 'FECHA DE CREACIÓN';
COMMENT ON COLUMN DISPOSITIVOS.DTFECHAMODIFICACION IS 'FECHA DE ÚLTIMA MODIFICACIÓN';
COMMENT ON COLUMN DISPOSITIVOS.DTFECHABAJA IS 'FECHA DE BAJA';
COMMENT ON COLUMN DISPOSITIVOS.BACTIVO IS 'INDICA SI ESTA ACTIVO';
COMMENT ON COLUMN DISPOSITIVOS.BBAJA IS 'INIDICA SI ESTA DADO DE BAJA';
COMMENT ON COLUMN DISPOSITIVOS.UIDUSUARIOCREACION IS 'IDENTIFICADOR DEL USUARIO QUE LO CREO';
COMMENT ON COLUMN DISPOSITIVOS.UIDUSUARIOMODIFICACION IS 'IDENTIFICADOR DEL USUARIO QUE LO MODIFICO';
COMMENT ON COLUMN DISPOSITIVOS.UIDUSUARIOBAJA IS 'IDENTIFICADOR DEL USUARIO QUE LO ELIMINO';

INSERT INTO "CATALOGOS"."DISPOSITIVOS" (UIDDISPOSITIVOS, SNOMBRE, DTFECHACREACION, BACTIVO, BBAJA, UIDUSUARIOCREACION) 
VALUES ('fe8c0355-63e8-4df4-9865-d989740a0ac5', 'Cajero', TO_TIMESTAMP('2025-08-21 23:00:00.420665300', 'YYYY-MM-DD HH24:MI:SS.FF'), '1', '0', '00000000-0000-0000-0000-000000000000');

CREATE TABLE ESTATUSVSAM 
(
  UIDESTATUSEMV VARCHAR2(36) NOT NULL 
, SNOMBRE VARCHAR2(100) NOT NULL 
, DTFECHACREACION TIMESTAMP NOT NULL
, DTFECHAMODIFICACION TIMESTAMP
, DTFECHABAJA TIMESTAMP
, BACTIVO NUMBER(1) DEFAULT 1 NOT NULL
, BBAJA NUMBER(1) DEFAULT 0 NOT NULL
, UIDUSUARIOCREACION VARCHAR2(36) NOT NULL 
, UIDUSUARIOMODIFICACION VARCHAR2(36)
, UIDUSUARIOBAJA VARCHAR2(36)
, CONSTRAINT ESTATUSVSAM_PK PRIMARY KEY 
  (
    UIDESTATUSEMV 
  )
  ENABLE 
) 
TABLESPACE DATA;

COMMENT ON COLUMN ESTATUSVSAM.UIDESTATUSEMV IS 'IDENTIFICADOR DE LA TABLA';
COMMENT ON COLUMN ESTATUSVSAM.SNOMBRE IS 'NOMBRE DEL ESTATUS VSAM';
COMMENT ON COLUMN ESTATUSVSAM.DTFECHACREACION IS 'FECHA DE CREACIÓN';
COMMENT ON COLUMN ESTATUSVSAM.DTFECHAMODIFICACION IS 'FECHA DE ÚLTIMA MODIFICACIÓN';
COMMENT ON COLUMN ESTATUSVSAM.DTFECHABAJA IS 'FECHA DE BAJA';
COMMENT ON COLUMN ESTATUSVSAM.BACTIVO IS 'INDICA SI ESTA ACTIVO';
COMMENT ON COLUMN ESTATUSVSAM.BBAJA IS 'INIDICA SI ESTA DADO DE BAJA';
COMMENT ON COLUMN ESTATUSVSAM.UIDUSUARIOCREACION IS 'IDENTIFICADOR DEL USUARIO QUE LO CREO';
COMMENT ON COLUMN ESTATUSVSAM.UIDUSUARIOMODIFICACION IS 'IDENTIFICADOR DEL USUARIO QUE LO MODIFICO';
COMMENT ON COLUMN ESTATUSVSAM.UIDUSUARIOBAJA IS 'IDENTIFICADOR DEL USUARIO QUE LO ELIMINO';

INSERT INTO "CATALOGOS"."ESTATUSVSAM" (UIDESTATUSEMV, SNOMBRE, DTFECHACREACION, BACTIVO, BBAJA, UIDUSUARIOCREACION) 
VALUES ('af428bd5-1971-4c66-9739-494eb69b0e15', 'Dañada', TO_TIMESTAMP('2025-08-21 23:00:00.249053900', 'YYYY-MM-DD HH24:MI:SS.FF'), '1', '0', '00000000-0000-0000-0000-000000000000');

--VSAM
ALTER TABLE VSAM 
ADD (UIDDISPOSITIVOS VARCHAR2(36));

ALTER TABLE VSAM 
ADD (UIDESTATUSEMV VARCHAR2(36));

COMMENT ON COLUMN VSAM.UIDDISPOSITIVOS IS 'IDENTIFICADOR DE LA RELACION CON EL DISPOSITIVO';

COMMENT ON COLUMN VSAM.UIDESTATUSEMV IS 'IDENTIFICADOR DE LA RELACION CON EL ESTATUSVSAM';

--LEYENDAS
ALTER TABLE CATALOGOS.PRODUCTOS ADD (SLEYENDA1 VARCHAR2(250));
COMMENT ON COLUMN CATALOGOS.PRODUCTOS.SLEYENDA1 IS 'Primera leyenda para los productos';
ALTER TABLE CATALOGOS.PRODUCTOS ADD (SLEYENDA2 VARCHAR2(250));
COMMENT ON COLUMN CATALOGOS.PRODUCTOS.SLEYENDA2 IS 'Segunda leyenda para los productos';



