--DIDIER

CREATE TABLE CATALOGOS.DISPOSITIVOS
(
    UIDDISPOSITIVOS        VARCHAR2(36)        NOT NULL,
    SNOMBRE                VARCHAR2(100)       NOT NULL,
    DTFECHACREACION        TIMESTAMP           NOT NULL,
    DTFECHAMODIFICACION    TIMESTAMP,
    DTFECHABAJA            TIMESTAMP,
    BACTIVO                NUMBER(1) DEFAULT 1 NOT NULL,
    BBAJA                  NUMBER(1) DEFAULT 0 NOT NULL,
    UIDUSUARIOCREACION     VARCHAR2(36)        NOT NULL,
    UIDUSUARIOMODIFICACION VARCHAR2(36),
    UIDUSUARIOBAJA         VARCHAR2(36),
    CONSTRAINT DISPOSITIVOS_PK PRIMARY KEY
        (
         UIDDISPOSITIVOS
            )
        ENABLE
)
    TABLESPACE DATA;

COMMENT ON COLUMN CATALOGOS.DISPOSITIVOS.UIDDISPOSITIVOS IS 'IDENTIFICADOR DE LA TABLA';
COMMENT ON COLUMN CATALOGOS.DISPOSITIVOS.SNOMBRE IS 'NOMBRE DEL DISPOSITIVO';
COMMENT ON COLUMN CATALOGOS.DISPOSITIVOS.DTFECHACREACION IS 'FECHA DE CREACIÓN';
COMMENT ON COLUMN CATALOGOS.DISPOSITIVOS.DTFECHAMODIFICACION IS 'FECHA DE ÚLTIMA MODIFICACIÓN';
COMMENT ON COLUMN CATALOGOS.DISPOSITIVOS.DTFECHABAJA IS 'FECHA DE BAJA';
COMMENT ON COLUMN CATALOGOS.DISPOSITIVOS.BACTIVO IS 'INDICA SI ESTA ACTIVO';
COMMENT ON COLUMN CATALOGOS.DISPOSITIVOS.BBAJA IS 'INIDICA SI ESTA DADO DE BAJA';
COMMENT ON COLUMN CATALOGOS.DISPOSITIVOS.UIDUSUARIOCREACION IS 'IDENTIFICADOR DEL USUARIO QUE LO CREO';
COMMENT ON COLUMN CATALOGOS.DISPOSITIVOS.UIDUSUARIOMODIFICACION IS 'IDENTIFICADOR DEL USUARIO QUE LO MODIFICO';
COMMENT ON COLUMN CATALOGOS.DISPOSITIVOS.UIDUSUARIOBAJA IS 'IDENTIFICADOR DEL USUARIO QUE LO ELIMINO';

INSERT INTO "CATALOGOS"."DISPOSITIVOS" (UIDDISPOSITIVOS, SNOMBRE, DTFECHACREACION, BACTIVO, BBAJA, UIDUSUARIOCREACION)
VALUES ('fe8c0355-63e8-4df4-9865-d989740a0ac5', 'Cajero',
        TO_TIMESTAMP('2025-08-28 23:00:00.420665300', 'YYYY-MM-DD HH24:MI:SS.FF'), '1', '0',
        '00000000-0000-0000-0000-000000000000');

INSERT INTO "CATALOGOS"."DISPOSITIVOS" (UIDDISPOSITIVOS, SNOMBRE, DTFECHACREACION, BACTIVO, BBAJA, UIDUSUARIOCREACION)
VALUES ('2d0a7f44-c364-40b1-b119-8277e2ad6279', 'HSM',
        TO_TIMESTAMP('2025-08-28 23:00:00.420665300', 'YYYY-MM-DD HH24:MI:SS.FF'), '1', '0',
        '00000000-0000-0000-0000-000000000000');

INSERT INTO "CATALOGOS"."DISPOSITIVOS" (UIDDISPOSITIVOS, SNOMBRE, DTFECHACREACION, BACTIVO, BBAJA, UIDUSUARIOCREACION)
VALUES ('0be979d3-377b-497f-a989-64c0eaebf506', 'Validador',
        TO_TIMESTAMP('2025-08-28 23:00:00.420665300', 'YYYY-MM-DD HH24:MI:SS.FF'), '1', '0',
        '00000000-0000-0000-0000-000000000000');

CREATE TABLE CATALOGOS.ESTATUSVSAM
(
    UIDESTATUSEMV          VARCHAR2(36)        NOT NULL,
    SNOMBRE                VARCHAR2(100)       NOT NULL,
    DTFECHACREACION        TIMESTAMP           NOT NULL,
    DTFECHAMODIFICACION    TIMESTAMP,
    DTFECHABAJA            TIMESTAMP,
    BACTIVO                NUMBER(1) DEFAULT 1 NOT NULL,
    BBAJA                  NUMBER(1) DEFAULT 0 NOT NULL,
    UIDUSUARIOCREACION     VARCHAR2(36)        NOT NULL,
    UIDUSUARIOMODIFICACION VARCHAR2(36),
    UIDUSUARIOBAJA         VARCHAR2(36),
    CONSTRAINT ESTATUSVSAM_PK PRIMARY KEY
        (
         UIDESTATUSEMV
            )
        ENABLE
)
    TABLESPACE DATA;

COMMENT ON COLUMN CATALOGOS.ESTATUSVSAM.UIDESTATUSEMV IS 'IDENTIFICADOR DE LA TABLA';
COMMENT ON COLUMN CATALOGOS.ESTATUSVSAM.SNOMBRE IS 'NOMBRE DEL ESTATUS VSAM';
COMMENT ON COLUMN CATALOGOS.ESTATUSVSAM.DTFECHACREACION IS 'FECHA DE CREACIÓN';
COMMENT ON COLUMN CATALOGOS.ESTATUSVSAM.DTFECHAMODIFICACION IS 'FECHA DE ÚLTIMA MODIFICACIÓN';
COMMENT ON COLUMN CATALOGOS.ESTATUSVSAM.DTFECHABAJA IS 'FECHA DE BAJA';
COMMENT ON COLUMN CATALOGOS.ESTATUSVSAM.BACTIVO IS 'INDICA SI ESTA ACTIVO';
COMMENT ON COLUMN CATALOGOS.ESTATUSVSAM.BBAJA IS 'INIDICA SI ESTA DADO DE BAJA';
COMMENT ON COLUMN CATALOGOS.ESTATUSVSAM.UIDUSUARIOCREACION IS 'IDENTIFICADOR DEL USUARIO QUE LO CREO';
COMMENT ON COLUMN CATALOGOS.ESTATUSVSAM.UIDUSUARIOMODIFICACION IS 'IDENTIFICADOR DEL USUARIO QUE LO MODIFICO';
COMMENT ON COLUMN CATALOGOS.ESTATUSVSAM.UIDUSUARIOBAJA IS 'IDENTIFICADOR DEL USUARIO QUE LO ELIMINO';

INSERT INTO "CATALOGOS"."ESTATUSVSAM" (UIDESTATUSEMV, SNOMBRE, DTFECHACREACION, BACTIVO, BBAJA, UIDUSUARIOCREACION)
VALUES ('af428bd5-1971-4c66-9739-494eb69b0e15', 'Dañada',
        TO_TIMESTAMP('2025-08-28 23:00:00.249053900', 'YYYY-MM-DD HH24:MI:SS.FF'), '1', '0',
        '00000000-0000-0000-0000-000000000000');

INSERT INTO "CATALOGOS"."ESTATUSVSAM" (UIDESTATUSEMV, SNOMBRE, DTFECHACREACION, BACTIVO, BBAJA, UIDUSUARIOCREACION)
VALUES ('ee3c6b36-7eb5-4129-9a94-c042e997d63b', 'Garantía',
        TO_TIMESTAMP('2025-08-28 23:00:00.249053900', 'YYYY-MM-DD HH24:MI:SS.FF'), '1', '0',
        '00000000-0000-0000-0000-000000000000');

INSERT INTO "CATALOGOS"."ESTATUSVSAM" (UIDESTATUSEMV, SNOMBRE, DTFECHACREACION, BACTIVO, BBAJA, UIDUSUARIOCREACION)
VALUES ('d6b2c273-e092-4c1a-9316-9607add341d7', 'En almacen',
        TO_TIMESTAMP('2025-08-28 23:00:00.249053900', 'YYYY-MM-DD HH24:MI:SS.FF'), '1', '0',
        '00000000-0000-0000-0000-000000000000');

--VSAM

ALTER TABLE CATALOGOS.VSAM
    ADD (UIDDISPOSITIVOS VARCHAR2(36));

ALTER TABLE CATALOGOS.VSAM
    ADD (UIDESTATUSEMV VARCHAR2(36));

COMMENT ON COLUMN CATALOGOS.VSAM.UIDDISPOSITIVOS IS 'IDENTIFICADOR DE LA RELACION CON EL DISPOSITIVO';

COMMENT ON COLUMN CATALOGOS.VSAM.UIDESTATUSEMV IS 'IDENTIFICADOR DE LA RELACION CON EL ESTATUSVSAM';
--
-- --CORRER SOLO SI SE REVIERTE LA PUBLICACIÓN
-- DROP TABLE ESTATUSVSAM;
-- DROP TABLE DISPOSITIVOS;
--
-- ALTER TABLE VSAM DROP (UIDDISPOSITIVOS, UIDESTATUSEMV);
--


--------------------LUIS


--LEYENDAS

ALTER TABLE CATALOGOS.PRODUCTOS
    ADD (SLEYENDA1 VARCHAR2(250));
COMMENT ON COLUMN CATALOGOS.PRODUCTOS.SLEYENDA1 IS 'Primera leyenda para los productos';
ALTER TABLE CATALOGOS.PRODUCTOS
    ADD (SLEYENDA2 VARCHAR2(250));
COMMENT ON COLUMN CATALOGOS.PRODUCTOS.SLEYENDA2 IS 'Segunda leyenda para los productos';


-------------------------FELIPE

ALTER TABLE APP.USUARIO
    MODIFY (SIMAGEPATH VARCHAR2(130 BYTE));
---> ANTERIORMENTE TENIA 100 BYTE


----DIDIER


UPDATE CATALOGOS.ESTATUSVSAM
SET SNOMBRE = 'En almacén'
WHERE UIDESTATUSEMV = 'd6b2c273-e092-4c1a-9316-9607add341d7';





---------------LUIS


ALTER TABLE CATALOGOS.PRODUCTOS
  MODIFY (
    SLEYENDA1 VARCHAR2(250 CHAR),
    SLEYENDA2 VARCHAR2(250 CHAR)
  );

