
ALTER TABLE CATALOGOS.PRODUCTOS ADD (SLEYENDA1 VARCHAR2(250 CHAR));  
COMMENT ON COLUMN CATALOGOS.PRODUCTOS.SLEYENDA1 IS 'Primera leyenda para los productos';  

ALTER TABLE CATALOGOS.PRODUCTOS ADD (SLEYENDA2 VARCHAR2(250 CHAR));  
COMMENT ON COLUMN CATALOGOS.PRODUCTOS.SLEYENDA2 IS 'Segunda leyenda para los productos';  

COMMIT;

