ALTER TABLE COMERCIO.PRODUCTOS ADD (SLEYENDA1 VARCHAR2(250 CHAR));  
COMMENT ON COLUMN COMERCIO.PRODUCTOS.SLEYENDA1 IS 'Primera leyenda para los productos';  

ALTER TABLE COMERCIO.PRODUCTOS ADD (SLEYENDA2 VARCHAR2(250 CHAR));  
COMMENT ON COLUMN COMERCIO.PRODUCTOS.SLEYENDA2 IS 'Segunda leyenda para los productos';  

-- COMMIT;