INSERT INTO SINCRONIZADOR.DENEGADOS (SPANHASH, SESTATUS, DTFECHACREACION, UIDUSUARIOMODIFICACION, UIDUSUARIOBAJA,
                                     UIDUSUARIOCREACION)
Select SPANHASH,
       'D' SESTATUS,
       SYSDATE,
       '00000000-0000-0000-0000-000000000000',
       '00000000-0000-0000-0000-000000000000',
       '00000000-0000-0000-0000-000000000000'
from monederoconsultas.estadodecuenta mce
where INUMTARJETA in (
    5000000000323533
);


-------SACAR SOLO LAS TARJETAS QUE ESTAN SIENDO DENEGADAS EN EL MES CUANDO SON DE TARIFA GENERAL
select nfc.INUMEROTARJETA||',' as tarjetas_denegadas_activas
from SINCRONIZADOR.DETALLESINCRONIZACIONTRANSACCIONESNFC nfc
         join MONEDEROCONSULTAS.ESTADODECUENTA MCE on nfc.INUMEROTARJETA = mce.INUMTARJETA
         join sincronizador.VALIDADORES SVM on nfc.UIDVALIDADOR = svm.UIDVALIDADOR
where 1 = 1
  and nfc.IERROR = 3
  and mce.SESTATUS = 'ACTIVO'
  AND nfc.STIPOTARIFA = 'Tarifa General'
  and trunc(nfc.DTFECHAOPERACION, 'MM') >= trunc(sysdate - 6 / 24, 'MM')
group by nfc.INUMEROTARJETA;


---SACAR VALIDADORES QUE ESTAN DENEGANDO TARJETAS ACTIVAS Y ENLISTARLAS POR VALIDADOR
select nfc.UIDVALIDADOR,
       svm.SCLAVE,
       LISTAGG(nfc.INUMEROTARJETA, ', ') WITHIN GROUP (ORDER BY nfc.INUMEROTARJETA) as tarjetas_denegadas_activas
from SINCRONIZADOR.DETALLESINCRONIZACIONTRANSACCIONESNFC nfc
         join MONEDEROCONSULTAS.ESTADODECUENTA MCE on nfc.INUMEROTARJETA = mce.INUMTARJETA
         join sincronizador.VALIDADORES SVM on nfc.UIDVALIDADOR = svm.UIDVALIDADOR
where 1 = 1
  and nfc.IERROR = 3
  and mce.SESTATUS = 'ACTIVO'
  AND nfc.STIPOTARIFA = 'Tarifa General'
  and trunc(nfc.DTFECHAOPERACION, 'MM') >= trunc(sysdate - 6 / 24, 'MM')
group by nfc.UIDVALIDADOR, svm.SCLAVE;




WITH base AS (
  SELECT DISTINCT
         nfc.UIDVALIDADOR,
         svm.SCLAVE,
         TO_CHAR(nfc.INUMEROTARJETA) AS tarjeta
  FROM SINCRONIZADOR.DETALLESINCRONIZACIONTRANSACCIONESNFC nfc
  JOIN MONEDEROCONSULTAS.ESTADODECUENTA mce
    ON nfc.INUMEROTARJETA = mce.INUMTARJETA
  JOIN SINCRONIZADOR.VALIDADORES svm
    ON nfc.UIDVALIDADOR = svm.UIDVALIDADOR
  WHERE nfc.IERROR = 3
    AND mce.SESTATUS = 'ACTIVO'
    AND nfc.STIPOTARIFA = 'Tarifa General'
    AND TRUNC(nfc.DTFECHAOPERACION, 'MM') >= TRUNC(SYSDATE - 6/24, 'MM')
)
SELECT
  UIDVALIDADOR,
  SCLAVE,
  LISTAGG(tarjeta, ', ') WITHIN GROUP (ORDER BY tarjeta)
    /* opcional para evitar ORA-01489 en listas largas: */
    AS tarjetas_denegadas_activas,
  COUNT(*) AS total_tarjetas_unicas
FROM base B
GROUP BY UIDVALIDADOR, SCLAVE;


