SELECT FECHA, COUNT(0)
FROM (SELECT INUMTARJETA, trunc(c.DTFECHACREACION) FECHA, COUNT(0) tarjetas_Por_Abonar
      FROM MONEDEROCONSULTAS.ESTADODECUENTA e
               INNER JOIN SINCRONIZADOR.CAMBIOSMONEDERO c ON c.STARJETA = e.INUMTARJETA
               INNER JOIN SINCRONIZADOR.MONEDERO m ON m.UIDMONEDERO = e.UIDMONEDERO
      WHERE trunc(c.DTFECHACREACION) >= trunc(to_date('14/09/25', 'dd/mm/yy'))
        AND e.INUMTARJETA > 0
        AND m.ICONTADORRECARGAAPLICADA > 0
      GROUP BY INUMTARJETA, trunc(c.DTFECHACREACION)
      HAVING MAX(c.ICONTADORRECARGA) - MAX(m.ICONTADORRECARGAAPLICADA) > 3) DUAL
--INNER JOIN SINCRONIZADOR.DETALLESINCRONIZACIONTRANSACCIONESNFC t ON t.INUMEROTARJETA = INUMTARJETA
--WHERE t.DTFECHAOPERACION BETWEEN ((SYSDATE-6/24) - (120/1440)) AND (SYSDATE -6/24)
--AND t.IERROR = 2
GROUP BY FECHA
ORDER BY FECHA desc;