--EMV COMERCIO

SELECT
    'EMV' COMERCIO,
    'CARGO M.F' TIPO_TRANSACCION,
    TO_CHAR(OL.DTFECHACAMBIOESTADO, 'DD/MM/YYYY HH24:MM:SS') FECHA_OPERACION,
    'EMV' TIPO_MONEDERO,
    'Abono' TIPO_MOVIMIENTO,
    'EMV-BANCARIA' TIPO_TARIFA,
    C.DTARIFAMONTO MONTO
FROM openloop.transacciones OL
    INNER JOIN OPENLOOP.CARGOS C ON OL.UIDTRANSACCION = C.UIDTRANSACCION
WHERE
    OL.DTFECHACREACION>=TO_DATE('28-04-2025 00:00:00', 'DD-MM-YYYY HH24:MI:SS')
    AND OL.DTFECHACAMBIOESTADO>=TO_DATE('12-07-2025 00:00:00', 'DD-MM-YYYY HH24:MI:SS')
    AND OL.DTFECHACAMBIOESTADO< TO_DATE('13-07-2025 00:00:00', 'DD-MM-YYYY HH24:MI:SS')
    AND OL.SESTADOOPERACION='LIQUIDADO'

;
------------------------------------------


--------------------VERSION DE SEBAS

--EMV COMERCIO

SELECT
    ''EMV'' COMERCIO,
    ''CARGO M.F'' TIPO_TRANSACCION,
    TO_CHAR(OL.DTFECHACAMBIOESTADO, ''DD/MM/YYYY HH24:MM:SS'') FECHA_OPERACION,
    ''EMV'' TIPO_MONEDERO,
    ''Abono'' TIPO_MOVIMIENTO,
    ''EMV-BANCARIA'' TIPO_TARIFA,
    C.DTARIFAMONTO MONTO
FROM openloop.transacciones OL
    INNER JOIN OPENLOOP.CARGOS C ON OL.UIDTRANSACCION = C.UIDTRANSACCION
WHERE
    OL.DTFECHACREACION>=TO_DATE(''28-04-2025 00:00:00'', ''DD-MM-YYYY HH24:MI:SS'')
    AND OL.DTFECHACAMBIOESTADO>=TRUNC(SYSDATE - 1)
    AND OL.DTFECHACAMBIOESTADO< TRUNC(SYSDATE)
    AND OL.SESTADOOPERACION=''LIQUIDADO''
    ;
------------------------------------------






-- VERSION 2.0 ABIE


SELECT
'EMV' COMERCIO,
'CARGO M.F' TIPO_TRANSACCION,
TO_CHAR(OL.DTFECHACAMBIOESTADO, 'DD/MM/YYYY HH24:MM:SS') FECHA_OPERACION,
'EMV' TIPO_MONEDERO,
'Abono' TIPO_MOVIMIENTO,
'EMV-BANCARIA' TIPO_TARIFA,
SEMVCARDBRAND TIPOTARJETA,
SEMVCARDBIN FIRST6D,
SEMVCARDLAST LAST4D,
C.DTARIFAMONTO MONTO
FROM openloop.transacciones OL
INNER JOIN OPENLOOP.CARGOS C ON OL.UIDTRANSACCION = C.UIDTRANSACCION
left join openloop.CONCILIACIONES CO ON CO.STOKENTRANSACTION = OL.STOKENTRANSACTION
WHERE
OL.DTFECHACREACION>=TO_DATE('28-04-2025 00:00:00', 'DD-MM-YYYY HH24:MI:SS')
AND OL.DTFECHACAMBIOESTADO>=TO_DATE('27-07-2025 00:00:00', 'DD-MM-YYYY HH24:MI:SS')
AND OL.DTFECHACAMBIOESTADO< TO_DATE('28-07-2025 00:00:00', 'DD-MM-YYYY HH24:MI:SS')
AND OL.SESTADOOPERACION='LIQUIDADO';



-- VERSION 2.0 SEBAS




SELECT
''EMV'' COMERCIO,
''CARGO M.F'' TIPO_TRANSACCION,
TO_CHAR(OL.DTFECHACAMBIOESTADO, ''DD/MM/YYYY HH24:MM:SS'') FECHA_OPERACION,
''EMV'' TIPO_MONEDERO,
''Abono'' TIPO_MOVIMIENTO,
''EMV-BANCARIA'' TIPO_TARIFA,
SEMVCARDBRAND TIPOTARJETA,
SEMVCARDBIN FIRST6D,
SEMVCARDLAST LAST4D,
C.DTARIFAMONTO MONTO
FROM openloop.transacciones OL
INNER JOIN OPENLOOP.CARGOS C ON OL.UIDTRANSACCION = C.UIDTRANSACCION
left join openloop.CONCILIACIONES CO ON CO.STOKENTRANSACTION = OL.STOKENTRANSACTION
WHERE
OL.DTFECHACREACION>=TO_DATE(''28-04-2025 00:00:00'', ''DD-MM-YYYY HH24:MI:SS'')
AND OL.DTFECHACAMBIOESTADO>=TRUNC(SYSDATE - 1)
AND OL.DTFECHACAMBIOESTADO< TRUNC(SYSDATE)
AND OL.SESTADOOPERACION=''LIQUIDADO''

;