--Regresar a negativo los montos del subtotal
UPDATE MONEDEROCONSULTAS.DETALLEMOVIMIENTOS
SET DMONTO = DMONTO * -1
WHERE UIDOPERACION IN (SELECT UIDOPERACION FROM MONEDEROCOMANDOS.MOVIMIENTOSESTADOSDECUENTA
WHERE UIDTIPOTRANSACCION = 'bce7d9cc-c82c-4c26-b11d-2ce5eb56c001' AND DMONTO < 0
);

UPDATE MONEDEROCOMANDOS.MOVIMIENTOSESTADOSDECUENTA
SET DMONTO = DMONTO * -1
WHERE UIDTIPOTRANSACCION = 'bce7d9cc-c82c-4c26-b11d-2ce5eb56c001' AND DMONTO < 0;