*************************** PRELIBERACIÓN *****************************

-- ALTER TABLE APPMONEDEROCOMMAND.TARJETAUSUARIO ADD DTFECHACREACION TIMESTAMP NULL;
-- COMMENT ON COLUMN APPMONEDEROCOMMAND.TARJETAUSUARIO.DTFECHACREACION IS 'Fecha de la creación del registro.'; 

-- ALTER TABLE APPMONEDEROCOMMAND.TARJETAUSUARIO ADD DTFECHABAJA TIMESTAMP NULL;
-- COMMENT ON COLUMN APPMONEDEROCOMMAND.TARJETAUSUARIO.DTFECHABAJA IS 'Fecha de baja del registro.';


-- CREATE TABLE APPMONEDEROCOMMAND.TRASPASOS(
--     UIDOPERACION VARCHAR2(36) NOT NULL,
--     UIDMONEDEROORIGEN VARCHAR2(36) NOT NULL,
--     UIDMONEDERODESTINO VARCHAR2(36) NOT NULL,
--     INUMEROTARJETAORIGEN NUMBER(16,0) NOT NULL,
--     INUMEROTARJETADESTINO NUMBER(16,0) NOT NULL,
--     DMONTO NUMBER(18,2) NOT NULL,
--     IFOLIOOPERACION NUMBER(16,0) NOT NULL,
--     DTFECHAOPERACION TIMESTAMP NOT NULL,
--     CONSTRAINT PK_TRASPASOS PRIMARY KEY (UIDOPERACION)
-- )
-- TABLESPACE DATA;

-- COMMENT ON COLUMN APPMONEDEROCOMMAND.TRASPASOS.UIDOPERACION IS 'IDENTIFICADOR ÚNICO DEL TRASPASO';
-- COMMENT ON COLUMN APPMONEDEROCOMMAND.TRASPASOS.UIDMONEDEROORIGEN IS 'IDENTIFICADOR DEL MONEDERO ORIGEN';
-- COMMENT ON COLUMN APPMONEDEROCOMMAND.TRASPASOS.UIDMONEDERODESTINO IS 'IDENTIFICADOR DEL MONEDERO DESTINO';
-- COMMENT ON COLUMN APPMONEDEROCOMMAND.TRASPASOS.INUMEROTARJETAORIGEN IS 'NÚMERO DE LA TARJETA ORIGEN';
-- COMMENT ON COLUMN APPMONEDEROCOMMAND.TRASPASOS.INUMEROTARJETADESTINO IS 'NÚMERO DE LA TARJETA DESTINO';
-- COMMENT ON COLUMN APPMONEDEROCOMMAND.TRASPASOS.DMONTO IS 'MONTO DE LA OPERACIÓN';
-- COMMENT ON COLUMN APPMONEDEROCOMMAND.TRASPASOS.IFOLIOOPERACION IS 'FOLIO DE LA OPERACIÓN';
-- COMMENT ON COLUMN APPMONEDEROCOMMAND.TRASPASOS.DTFECHAOPERACION IS 'FECHA DE LA OPERACIÓN DEL REGISTRO';


-- ALTER TABLE APPMONEDEROCOMMAND.ESTADODECUENTA ADD DTFECHAINICIOVIGENCIA TIMESTAMP NULL;
-- COMMENT ON COLUMN APPMONEDEROCOMMAND.ESTADODECUENTA.DTFECHAINICIOVIGENCIA IS 'Fecha inicio de la vigencia del periodo de la tarjeta.';

-- ALTER TABLE APPMONEDEROCOMMAND.ESTADODECUENTA ADD DTFECHAFINVIGENCIA TIMESTAMP NULL;
-- COMMENT ON COLUMN APPMONEDEROCOMMAND.ESTADODECUENTA.DTFECHAFINVIGENCIA IS 'Fecha fin de la vigencia del periodo de la tarjeta.';



*************************** LIBERACIÓN *****************************
-- UPDATE APPMONEDEROCOMMAND.TARJETAUSUARIO SET DTFECHACREACION = CURRENT_TIMESTAMP


-- MERGE INTO APPMONEDEROCOMMAND.ESTADODECUENTA EDOCUENTA
-- USING (
-- SELECT t2.UIDTARJETA, t2.INUMEROTARJETA, t1.DTFECHAINICIOVIGENCIA, t1.DTFECHAFINVIGENCIA
-- 	FROM CREDENCIALIZACION.USUARIOSTARJETAS t1
-- 	INNER JOIN APPMONEDEROCOMMAND.ESTADODECUENTA t2 ON t1.UIDTARJETA = t2.UIDTARJETA 
-- 	WHERE t1.UIDTIPOTARIFA IN ('5b95c756-1a97-4a76-8d63-8fb0f40b9d46','4fb9c75a-df93-4e1e-bab1-104e9f61c496') 
-- 	AND t1.BACTIVO = 1 AND t1.BBAJA = 0 
-- 	AND (t2.DTFECHAFINVIGENCIA IS NULL OR t1.DTFECHAFINVIGENCIA <> t2.DTFECHAFINVIGENCIA)
-- ) MONEDEROS
-- ON (EDOCUENTA.UIDTARJETA = MONEDEROS.UIDTARJETA)
-- WHEN MATCHED THEN
-- UPDATE SET EDOCUENTA.DTFECHAINICIOVIGENCIA = MONEDEROS.DTFECHAINICIOVIGENCIA, EDOCUENTA.DTFECHAFINVIGENCIA = MONEDEROS.DTFECHAFINVIGENCIA
-- WHERE EDOCUENTA.UIDTARJETA = MONEDEROS.UIDTARJETA AND EDOCUENTA.UIDTIPOTARIFA IN ('5b95c756-1a97-4a76-8d63-8fb0f40b9d46','4fb9c75a-df93-4e1e-bab1-104e9f61c496')


-- CONSULTA PARA VALIDAR DIFERENCIAS DE MONEDEROS EN SUS FECHAS DE VIGENCIA EN APPMONEDEROQUERY
SELECT --DISTINCT U.UIDMONEDEROAPP UIDMONEDERO, P.DTFECHAINICIOPERIODO , P.DTFECHAFINPERIODO
    COUNT(0) AS discrepancias
        FROM CREDENCIALIZACION.USUARIOSTARJETAS u
        INNER JOIN CREDENCIALIZACION.PERIODOSTARJETAS p ON p.UIDMONEDERO = U.UIDMONEDEROAPP AND p.BACTIVO = 1
        INNER JOIN APPMONEDEROCOMMAND.ESTADODECUENTA e ON e.UIDMONEDERO = U.UIDMONEDEROAPP
    WHERE U.BACTIVO = 1 AND U.BBAJA = 0 AND U.UIDTIPOTARIFA <> '24665f64-1ef6-4404-b59a-3fd3cd74a9be'
        AND p.BACTIVO = 1 AND p.BBAJA = 0
        AND (e.DTFECHAFINVIGENCIA is null OR e.DTFECHAFINVIGENCIA <> P.DTFECHAFINPERIODO)

-- DIFERENCIA DE FECHAS DE VIGENCIA EN MONEDEROS
MERGE INTO APPMONEDEROCOMMAND.ESTADODECUENTA EDOCUENTA
USING (
    SELECT DISTINCT U.UIDMONEDEROAPP UIDMONEDERO,  P.DTFECHAINICIOPERIODO ,  P.DTFECHAFINPERIODO
        FROM CREDENCIALIZACION.USUARIOSTARJETAS u
        INNER JOIN CREDENCIALIZACION.PERIODOSTARJETAS p ON p.UIDMONEDERO = U.UIDMONEDEROAPP AND p.BACTIVO = 1
        INNER JOIN APPMONEDEROCOMMAND.ESTADODECUENTA e ON e.UIDMONEDERO = U.UIDMONEDEROAPP
    WHERE U.BACTIVO = 1 AND U.BBAJA = 0 AND U.UIDTIPOTARIFA <> '24665f64-1ef6-4404-b59a-3fd3cd74a9be'
        AND p.BACTIVO = 1 AND p.BBAJA = 0
        AND (e.DTFECHAFINVIGENCIA is null OR e.DTFECHAFINVIGENCIA <> P.DTFECHAFINPERIODO)) MONEDEROS
ON (EDOCUENTA.UIDMONEDERO = MONEDEROS.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET EDOCUENTA.DTFECHAINICIOVIGENCIA = MONEDEROS.DTFECHAINICIOVIGENCIA, EDOCUENTA.DTFECHAINICIOPERIODO = MONEDEROS.DTFECHAFINPERIODO

----------------------

--SEBAS CORRECCION --TODO OCUPAR ESTE


-- MERGE INTO APPMONEDEROCOMMAND.ESTADODECUENTA EDOCUENTA
-- USING (

-- with base as (
--     SELECT DISTINCT 
--     U.UIDMONEDEROAPP UIDMONEDERO
--     ,  P.DTFECHAINICIOPERIODO 
--     ,  P.DTFECHAFINPERIODO
--     ,    ROW_NUMBER() OVER (PARTITION BY U.UIDMONEDEROAPP order by P.DTFECHAFINPERIODO desc) as rn

--         FROM CREDENCIALIZACION.USUARIOSTARJETAS u
--         INNER JOIN CREDENCIALIZACION.PERIODOSTARJETAS p ON p.UIDMONEDERO = U.UIDMONEDEROAPP AND p.BACTIVO = 1
--         INNER JOIN APPMONEDEROCOMMAND.ESTADODECUENTA e ON e.UIDMONEDERO = U.UIDMONEDEROAPP
--     WHERE U.BACTIVO = 1 AND U.BBAJA = 0 AND U.UIDTIPOTARIFA <> '24665f64-1ef6-4404-b59a-3fd3cd74a9be'
--         AND p.BACTIVO = 1 AND p.BBAJA = 0
--         AND (e.DTFECHAFINVIGENCIA is null OR e.DTFECHAFINVIGENCIA <> P.DTFECHAFINPERIODO)
--         ) select * from base where rn = 1
--         ) MONEDEROS
-- ON (EDOCUENTA.UIDMONEDERO = MONEDEROS.UIDMONEDERO)
-- WHEN MATCHED THEN
--     UPDATE SET 
--     EDOCUENTA.DTFECHAINICIOVIGENCIA = MONEDEROS.DTFECHAINICIOPERIODO
--     , EDOCUENTA.DTFECHAFINVIGENCIA = MONEDEROS.DTFECHAFINPERIODO


-------------------------







*******************************************************

-- CONSULTA PARA VALIDAR DIFERENCIAS DE TARJETAS EN SUS FECHAS DE VIGENCIA EN APPMONEDEROQUERY
SELECT --DISTINCT t.UIDMONEDERO, p.DTFECHAINICIOPERIODO , p.DTFECHAFINPERIODO, e.DTFECHAINICIOVIGENCIA, e.DTFECHAFINVIGENCIA--, p.UIDTARJETA 
    COUNT(0) AS discrepancias
        FROM CREDENCIALIZACION.TARJETAS t
            INNER JOIN CREDENCIALIZACION.USUARIOSTARJETAS u ON u.UIDTARJETA = t.UIDTARJETA
            INNER JOIN CREDENCIALIZACION.PERIODOSTARJETAS p ON p.UIDTARJETA = t.UIDTARJETA AND p.BACTIVO = 1
            INNER JOIN APPMONEDEROCOMMAND.ESTADODECUENTA e ON e.UIDTARJETA = t.UIDTARJETA
    WHERE t.BACTIVO = 1 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.UIDTIPOTARIFA <> '24665f64-1ef6-4404-b59a-3fd3cd74a9be' AND p.BACTIVO = 1
        AND e.DTFECHAFINVIGENCIA is null OR e.DTFECHAFINVIGENCIA <> P.DTFECHAFINPERIODO

-- DIFERENCIA DE FECHAS DE VIGENCIA EN TARJETAS
MERGE INTO APPMONEDEROCOMMAND.ESTADODECUENTA EDOCUENTA
USING (
    SELECT DISTINCT t.UIDMONEDERO, p.DTFECHAINICIOPERIODO , p.DTFECHAFINPERIODO
        FROM CREDENCIALIZACION.TARJETAS t
            INNER JOIN CREDENCIALIZACION.USUARIOSTARJETAS u ON u.UIDTARJETA = t.UIDTARJETA
            INNER JOIN CREDENCIALIZACION.PERIODOSTARJETAS p ON p.UIDTARJETA = t.UIDTARJETA AND p.BACTIVO = 1
            INNER JOIN APPMONEDEROCOMMAND.ESTADODECUENTA e ON e.UIDTARJETA = t.UIDTARJETA
    WHERE t.BACTIVO = 1 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.UIDTIPOTARIFA <> '24665f64-1ef6-4404-b59a-3fd3cd74a9be'
        AND e.DTFECHAFINVIGENCIA is null OR e.DTFECHAFINVIGENCIA <> P.DTFECHAFINPERIODO) TARJETAS
ON (EDOCUENTA.UIDMONEDERO = TARJETAS.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET EDOCUENTA.DTFECHAINICIOVIGENCIA = TARJETAS.DTFECHAINICIOPERIODO, EDOCUENTA.DTFECHAFINVIGENCIA = TARJETAS.DTFECHAFINPERIODO


    ---------------sebas correccion --TODO OCUPAR ESTE

MERGE INTO APPMONEDEROCOMMAND.ESTADODECUENTA EDOCUENTA
USING (
with base as (
    SELECT DISTINCT 
    t.UIDMONEDERO
    , p.DTFECHAINICIOPERIODO 
    , p.DTFECHAFINPERIODO
    , ROW_NUMBER() OVER (PARTITION BY U.UIDMONEDEROAPP order by P.DTFECHAFINPERIODO desc) as rn

        FROM CREDENCIALIZACION.TARJETAS t
            INNER JOIN CREDENCIALIZACION.USUARIOSTARJETAS u ON u.UIDTARJETA = t.UIDTARJETA
            INNER JOIN CREDENCIALIZACION.PERIODOSTARJETAS p ON p.UIDTARJETA = t.UIDTARJETA AND p.BACTIVO = 1
            INNER JOIN APPMONEDEROCOMMAND.ESTADODECUENTA e ON e.UIDTARJETA = t.UIDTARJETA
    WHERE t.BACTIVO = 1 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.UIDTIPOTARIFA <> '24665f64-1ef6-4404-b59a-3fd3cd74a9be'
        AND e.DTFECHAFINVIGENCIA is null OR e.DTFECHAFINVIGENCIA <> P.DTFECHAFINPERIODO)
        select * from base where rn = 1
        
        ) TARJETAS
ON (EDOCUENTA.UIDMONEDERO = TARJETAS.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET 
    EDOCUENTA.DTFECHAINICIOVIGENCIA = TARJETAS.DTFECHAINICIOPERIODO
    , EDOCUENTA.DTFECHAFINVIGENCIA = TARJETAS.DTFECHAFINPERIODO

    ------------
