*************************** PRELIBERACIÓN *****************************

ALTER TABLE PAGOS.ORDENES ADD SESTATUS VARCHAR2(50) NULL;
COMMENT ON COLUMN PAGOS.ORDENES.SESTATUS IS 'Estatus de la orden.';

ALTER TABLE PAGOS.ORDENES ADD SFOLIO VARCHAR2(50) NULL;
COMMENT ON COLUMN PAGOS.ORDENES.SFOLIO IS 'Folio de venta.';

ALTER TABLE PAGOS.ORDENES ADD DTFECHAOPERACION TIMESTAMP NULL;
COMMENT ON COLUMN PAGOS.ORDENES.DTFECHAOPERACION IS 'Fecha de operación.';




-- PAGOS CODI

CREATE TABLE PAGOS.ORDENESPENDIENTES(
UIDORDENPENDIENTE VARCHAR2(50) NOT NULL,
UIDORDEN VARCHAR2(50) NOT NULL,
SFOLIOCODI VARCHAR2(20) NULL,
SFOLIO VARCHAR2(20) NOT NULL,
BPAGADO NUMBER(1,0) NOT NULL,
BPUEDEABONAR NUMBER(1,0) NOT NULL,
DTFECHACREACION TIMESTAMP NOT NULL,
DTFECHAMODIFICACION TIMESTAMP NULL,
CONSTRAINT PK_TRASPASOS PRIMARY KEY (UIDORDENPENDIENTE)
)
TABLESPACE DATA;

COMMENT ON COLUMN PAGOS.ORDENESPENDIENTES.UIDORDENPENDIENTE IS 'IDENTIFICADOR ÚNICO DE LA ORDEN PENDIENTE';
COMMENT ON COLUMN PAGOS.ORDENESPENDIENTES.UIDORDEN IS 'IDENTIFICADOR DE LA ORDEN';
COMMENT ON COLUMN PAGOS.ORDENESPENDIENTES.SFOLIOCODI IS 'FOLIO ÚNICO DE LA OPERACIÓN DE CODI';
COMMENT ON COLUMN PAGOS.ORDENESPENDIENTES.SFOLIO IS 'FOLIO DE VENTA';
COMMENT ON COLUMN PAGOS.ORDENESPENDIENTES.BPAGADO IS 'INDICA SI LA ORDEN YA FUE PAGADA';
COMMENT ON COLUMN PAGOS.ORDENESPENDIENTES.BPUEDEABONAR IS 'INDICA SI SE PUEDE REALIZAR EL ABONO';
COMMENT ON COLUMN PAGOS.ORDENESPENDIENTES.DTFECHACREACION IS 'FECHA DE CREACIÓN DEL REGISTRO';
COMMENT ON COLUMN PAGOS.ORDENESPENDIENTES.DTFECHAMODIFICACION IS 'FECHA DE MODIFICACIÓN DEL REGISTRO';

-- MEJORA CODI
ALTER TABLE PAGOS.PAGOSCODI ADD DTFECHAOPERACION TIMESTAMP NULL;
COMMENT ON COLUMN PAGOS.PAGOSCODI.DTFECHAOPERACION IS 'Fecha de la operación del pago';

ALTER TABLE PAGOS.PAGOSCODI ADD SESTATUS VARCHAR2(50) NULL;
COMMENT ON COLUMN PAGOS.PAGOSCODI.SESTATUS IS 'Identifica el ultimo estatus del pago';

ALTER TABLE PAGOS.PAGOSCODI ADD BPAGADO NUMBER(1,0) NULL;
COMMENT ON COLUMN PAGOS.PAGOSCODI.BPAGADO IS 'Identifica si el registro ya se abono';

ALTER TABLE PAGOS.PAGOSCODI ADD SFOLIOVENTA VARCHAR2(50) NULL;
COMMENT ON COLUMN PAGOS.PAGOSCODI.SFOLIOVENTA IS 'Folio de venta del pago';

--todo esto no vaaaaaaa ALTER TABLE PAGOSCONSULTAS.ESTATUSORDEN ADD SFOLIO TIMESTAMP NULL;
--todo COMMENT ON COLUMN PAGOSCONSULTAS.ESTATUSORDEN.SFOLIO IS 'Folio de venta del pago';


ALTER TABLE PAGOSCONSULTAS.ESTATUSORDEN ADD SFOLIO VARCHAR2(50) NULL;
COMMENT ON COLUMN PAGOSCONSULTAS.ESTATUSORDEN.SFOLIO IS 'Folio de venta del pago';


ALTER TABLE PAGOSCONSULTAS.ESTATUSORDEN MODIFY SFOLIO VARCHAR2(50);
COMMENT ON COLUMN PAGOSCONSULTAS.ESTATUSORDEN.SFOLIO IS 'Folio de venta del pago';


-----------------------

ALTER TABLE PAGOSCONSULTAS.PAGOSCODI ADD DTFECHAOPERACION TIMESTAMP NULL;
COMMENT ON COLUMN PAGOSCONSULTAS.PAGOSCODI.DTFECHAOPERACION IS 'Fecha de la operación del pago';


ALTER TABLE PAGOSCONSULTAS.PAGOSCODI ADD SESTATUS VARCHAR2(50) NULL;
COMMENT ON COLUMN PAGOSCONSULTAS.PAGOSCODI.SESTATUS IS 'Identifica el ultimo estatus del pago';


ALTER TABLE PAGOSCONSULTAS.PAGOSCODI ADD BPAGADO NUMBER(1,0) NULL;
COMMENT ON COLUMN PAGOSCONSULTAS.PAGOSCODI.BPAGADO IS 'Identifica si el registro ya se abono';


ALTER TABLE PAGOSCONSULTAS.PAGOSCODI ADD SFOLIOVENTA VARCHAR2(50) NULL;
COMMENT ON COLUMN PAGOSCONSULTAS.PAGOSCODI.SFOLIOVENTA IS 'Folio de venta del pago';




-- POBLAR FOLIOS EN ESTATUSORDEN PARA ABONADOS
MERGE INTO PAGOSCONSULTAS.ESTATUSORDEN D
USING (
SELECT O.UIDORDEN, O.SFOLIO
FROM PAGOSCONSULTAS.ORDENES O
) ORDENES
ON (D.UIDORDEN = ORDENES.UIDORDEN)
WHEN MATCHED THEN
UPDATE SET D.SFOLIO = ORDENES.SFOLIO WHERE SESTATUS = 'ABONADO'