	
-------------------REPORTE 1
014.01 DATA REPORTE DE CONCESIONES MENSUALES ENERO ---> REPORTE -> FALTA AVERIGUAR LA CONSULTA QUE USA
VALIDADOR,RUTA,ORIGEN,FECHAOPERACION,HORAOPERACION,EMPRESA,MONEDERO,NUMTARJETA,MONTO,TRX,TRANSBORDO,TIPOTARIFA
CONSULTA
************************
SELECT VALIDADOR,
RUTA,
ORIGEN,
FECHAOPERACION,
HORAOPERACION,
EMPRESA,
SNUMEROMONEDERO AS MONEDERO,
SNOTARJETA AS NUMTARJETA
,MONTOCOBRADO AS MONTO
,NUMTRX AS TRX
,NUMTRANSBORDO  AS TRANSBORDO
,TIPOTARIFA AS TIPOTARIFA
FROM vwAbordos WITH (NOLOCK)
WHERE YEAR(FECHAOPERACION) = 2025 AND MONTH(FECHAOPERACION) = 6 AND EMPRESA IS NOT NULL AND RUTA IS NOT NULL
************************

-------------------REPORTE 2
014.02 DATA REPORTE DE PARADEROS  ENERO
VALIDADOR,RUTA,ORIGEN,FECHAOPERACION,HORAOPERACION,EMPRESA,MONEDERO,NUMTARJETA,MONTO,TRX,TRANSBORDO,TIPOTARIFA,PARADERO,LATITUD,LONGITUD,TIPODEBITACION
CONSULTA 
***********************
SELECT VALIDADOR,
RUTA,
ORIGEN,
FECHAOPERACION,
HORAOPERACION,
EMPRESA,
SNUMEROMONEDERO AS MONEDERO,
SNOTARJETA AS NUMTARJETA
,MONTOCOBRADO AS MONTO
,NUMTRX AS TRX
,NUMTRANSBORDO  AS TRANSBORDO
,TIPOTARIFA AS TIPOTARIFA,
PARADERO AS PARADERO
,SLATITUD AS LATITUD
, SLONGITUD AS LONGITUD
, TIPOTRANSACCION AS TIPODEBITACION
FROM vwAbordos
WHERE YEAR(FECHAOPERACION) = 2025 AND MONTH(FECHAOPERACION) = 6 AND EMPRESA IS NOT NULL AND RUTA IS NOT NULL
***********************



-------------------REPORTE 3

014.03 DATA REPORTE POR TIPO DE TARJETA ENERO

VALIDADOR,RUTA,ORIGEN,FECHAOPERACION,HORAOPERACION,EMPRESA,MONEDERO,NUMTARJETA,MONTO,TRX,TRANSBORDO,TIPOTARIFA
*********************************
SELECT VALIDADOR,
RUTA,
ORIGEN,
FECHAOPERACION,
HORAOPERACION,
EMPRESA,
SNUMEROMONEDERO AS MONEDERO,
SNOTARJETA AS NUMTARJETA
,MONTOCOBRADO AS MONTO
,NUMTRX AS TRX
,NUMTRANSBORDO  AS TRANSBORDO
,TIPOTARIFA AS TIPOTARIFA
FROM vwAbordos WITH (NOLOCK)
WHERE YEAR(FECHAOPERACION) = 2025 AND MONTH(FECHAOPERACION) = 6 AND EMPRESA IS NOT NULL AND RUTA IS NOT NULL
*********************************

-------------------REPORTE 4

014.04 DATA REPORTE DE RECAUDO DE RUTAS DIARIO - MENSUAL ENERO

VALIDADOR,RUTA,ORIGEN,FECHAOPERACION,HORAOPERACION,EMPRESA,MONEDERO,NUMTARJETA,MONTO,TRX,TRANSBORDO,TIPOTARIFA

***********************************++
SELECT VALIDADOR, RUTA,NUMCOMERCIAL, FECHAOPERACION,TIPOTARIFA,sum(MONTOCOBRADO)MONTOCOBRADO, sum(NUMTRX)NUMTRX
FROM vwAbordos
WHERE YEAR(FECHAOPERACION) = 2025 AND MONTH(FECHAOPERACION) = 6 AND EMPRESA IS NOT NULL AND RUTA IS NOT NULL
GROUP BY VALIDADOR, RUTA,NUMCOMERCIAL, FECHAOPERACION,TIPOTARIFA
*************************************


-------------------REPORTE 5

014.05 DATA REPORTE DE RECAUDO POR COMERCIO ENERO

TIPOCARGO,COMERCIO,FECHAOPERACION,HORAOPERACION,TIPOTARJETA,MONEDERO,FOLIOCOMERCIO,MONTO,TRX,DATA1

*********
select TIPOTRANSACCION AS TIPOCARGO
, GRUPOCOMERCIAL AS COMERCIO
, FECHA AS FECHAOPERACION
, HORA AS HORAOPERACION
, TIPOMONEDERO AS TIPOTARJETA
, INUMMONEDERO AS MONEDERO
, FOLIO AS FOLIOCOMERCIO
, MONTO AS MONTO
, NUMTRX AS TRX
, METODO AS DATA1
 from [dbo].[vwIngresosCargos]
where YEAR(fecha) = 2025 and month(fecha) = 6 and TIPOMOVIMIENTO = 'Cargo'

*******





-------------------REPORTE 6

014.06 DATA REPORTE DE SALDOS POR MONEDERO ENERO


TIPOTARJETA,TIPOMOVIMIENTO,ORIGENMOVIMIENTO,MONEDERO,NUMTARJETA,TIPOTARIFA,MONTO,TRX,FECHAOPERACION,LATITUD,LONGITUD,ORIGENCOMERCIO,SALDOMONEDERO


CONSULTA

*************************

SELECT TIPOMONEDERO as TIPOTARJETA
, TIPOMOVIMIENTO as TIPOMOVIMIENTO
, ORIGEN_MOVIMIENTO as ORIGENMOVIMIENTO
, INUMMONEDERO as MONEDERO
, NUMTARJETA as NUMTARJETA
, TIPOTARIFA as TIPOTARIFA
, MONTO as MONTO
, NUMTRX as TRX
, FECHA as FECHAOPERACION
, SLATITUD as LATITUD
, SLONGITUD as LONGITUD
, METODOPAGO as ORIGENCOMERCIO
, SALDO  as SALDOMONEDERO
FROM [dbo].[vwMovimientosEdoCuenta] WITH (NOLOCK)
WHERE SALDO > -12 AND YEAR(FECHA) = 2025 AND MONTH(FECHA) =6
********************************************************








-------------------REPORTE 7  SOLO POR SI ACASO

014.07 DATA REPORTE DE CONSULTA RAPIDA COMERCIOS ENERO

select TIPOTRANSACCION AS TIPOCARGO
, GRUPOCOMERCIAL AS COMERCIO
, FECHA AS FECHAOPERACION
, HORA AS HORAOPERACION
, TIPOMONEDERO AS TIPOTARJETA
, INUMMONEDERO AS MONEDERO
, FOLIO AS FOLIOCOMERCIO
, MONTO AS MONTO
, NUMTRX AS TRX
, METODO AS DATA1
 from [dbo].[vwIngresosCargos]
where YEAR(fecha) = 2025 and month(fecha) = 6 and TIPOMOVIMIENTO = 'Cargo'


-------------------REPORTE 8  SOLO POR SI ACASO

014.07 DATA REPORTE DE CONSULTA RAPIDA DEBITACIONES ENERO

VALIDADOR,RUTA,ORIGEN,FECHAOPERACION,HORAOPERACION,EMPRESA,MONEDERO,NUMTARJETA,MONTO,TRX,TRANSBORDO,TIPOTARIFA


CONSULTA

*****************************************
SELECT VALIDADOR,
RUTA,
ORIGEN,
FECHAOPERACION,
HORAOPERACION,
EMPRESA,
SNUMEROMONEDERO AS MONEDERO,
SNOTARJETA AS NUMTARJETA
,MONTOCOBRADO AS MONTO
,NUMTRX AS TRX
,NUMTRANSBORDO  AS TRANSBORDO
,TIPOTARIFA AS TIPOTARIFA
FROM vwAbordos WITH (NOLOCK)
WHERE YEAR(FECHAOPERACION) = 2025 AND MONTH(FECHAOPERACION) = 6 AND EMPRESA IS NOT NULL AND RUTA IS NOT NULL
*************************************


------  ----------------------------------*******************------------------------------ 











-- SELECT VALIDADOR, RUTA,ORIGEN, FECHAOPERACION, HORAOPERACION , EMPRESA, SNUMEROMONEDERO, SNOTARJETA, MONTOCOBRADO, NUMTRX, NUMTRANSBORDO, TIPOTARIFA, PARADERO, SLATITUD, SLONGITUD, TIPOTRANSACCION
-- FROM vwAbordos
-- WHERE YEAR(FECHAOPERACION) = 2025 AND MONTH(FECHAOPERACION) = 6 and DAY(FECHAOPERACION)= 18 AND EMPRESA IS NOT NULL AND RUTA IS NOT NULL
-- AND VALIDADOR = 'BV3-23120251';


-- ---------------------------------------
-- SELECT TIPOMONEDERO, TIPOMOVIMIENTO, ORIGEN_MOVIMIENTO, INUMMONEDERO, NUMTARJETA, TIPOTARIFA, MONTO, NUMTRX, FECHA, SLATITUD, SLONGITUD, METODOPAGO, SALDO 
-- FROM [dbo].[vwMovimientosEdoCuenta] WITH (NOLOCK) WHERE SALDO > -12 AND YEAR(FECHA) = 2025 AND MONTH(FECHA) =6 and DAY(FECHA)= 18

-- -----------------------------------------------
-- select TIPOTRANSACCION, GRUPOCOMERCIAL, FECHA, HORA, TIPOMONEDERO, INUMMONEDERO, FOLIO, MONTO, NUMTRX, METODO
--  from [dbo].[vwIngresosCargos]
-- where YEAR(fecha) = 2025 and month(fecha) = 5 and TIPOMOVIMIENTO = 'Cargo'

-- ----------------------------------------------



-- --ESTE ES EL REPORTE DE RUTAS
-- SELECT VALIDADOR, RUTA,NUMCOMERCIAL, FECHAOPERACION,TIPOTARIFA,sum(MONTOCOBRADO)MONTOCOBRADO, sum(NUMTRX)NUMTRX
-- FROM vwAbordos
-- WHERE YEAR(FECHAOPERACION) = 2025 AND MONTH(FECHAOPERACION) = 6 AND EMPRESA IS NOT NULL AND RUTA IS NOT NULL
-- GROUP BY VALIDADOR, RUTA,NUMCOMERCIAL, FECHAOPERACION,TIPOTARIFA


