

SELECT VALIDADOR, RUTA,ORIGEN, FECHAOPERACION, HORAOPERACION , EMPRESA, SNUMEROMONEDERO, SNOTARJETA, MONTOCOBRADO, NUMTRX, NUMTRANSBORDO, TIPOTARIFA, PARADERO, SLATITUD, SLONGITUD, TIPOTRANSACCION
FROM vwAbordos
WHERE YEAR(FECHAOPERACION) = 2025 AND MONTH(FECHAOPERACION) = 6 and DAY(FECHAOPERACION)= 18 AND EMPRESA IS NOT NULL AND RUTA IS NOT NULL
AND VALIDADOR = 'BV3-23120251';


---------------------------------------
SELECT TIPOMONEDERO, TIPOMOVIMIENTO, ORIGEN_MOVIMIENTO, INUMMONEDERO, NUMTARJETA, TIPOTARIFA, MONTO, NUMTRX, FECHA, SLATITUD, SLONGITUD, METODOPAGO, SALDO 
FROM [dbo].[vwMovimientosEdoCuenta] WITH (NOLOCK) WHERE SALDO > -12 AND YEAR(FECHA) = 2025 AND MONTH(FECHA) =6 and DAY(FECHA)= 18

-----------------------------------------------
select TIPOTRANSACCION, GRUPOCOMERCIAL, FECHA, HORA, TIPOMONEDERO, INUMMONEDERO, FOLIO, MONTO, NUMTRX, METODO
 from [dbo].[vwIngresosCargos]
where YEAR(fecha) = 2025 and month(fecha) = 5 and TIPOMOVIMIENTO = 'Cargo'

----------------------------------------------



--ESTE ES EL REPORTE DE RUTAS
SELECT VALIDADOR, RUTA,NUMCOMERCIAL, FECHAOPERACION,TIPOTARIFA,sum(MONTOCOBRADO)MONTOCOBRADO, sum(NUMTRX)NUMTRX
FROM vwAbordos
WHERE YEAR(FECHAOPERACION) = 2025 AND MONTH(FECHAOPERACION) = 6 AND EMPRESA IS NOT NULL AND RUTA IS NOT NULL
GROUP BY VALIDADOR, RUTA,NUMCOMERCIAL, FECHAOPERACION,TIPOTARIFA




