-- ACTUALIZACIÓN DE RÉPLICAS

-- CONSULTA PARA VALIDAR DIFERENCIAS
-- MONEDEROS NO REPLICADOS EN PREP_APPMONEDEROQUERY
SELECT --t1.dtfechacreacion,t1.uidmonedero, t2.uidmonedero
    'MONEDEROS no replicados (PREP_MONEDEROCOMANDOS vs PREP_APPMONEDEROQUERY)' AS fuente,
    COUNT(0) AS discrepancias
FROM  PREP_MONEDEROCOMANDOS.MONEDERO t1
LEFT JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO 
INNER JOIN PREP_MONEDEROCONSULTAS.ESTADODECUENTA e ON t1.UIDMONEDERO = e.UIDMONEDERO 
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t1.UIDTIPOSMONEDERO = '9be96cf8-4ee2-4762-9f77-7c817e851c03' AND t2.UIDMONEDERO IS NULL

-- CONSULTA PARA INSERTAR FALTANTES
-- CREAR MONEDEROS NO REPLICADOS EN PREP_APPMONEDEROQUERY
INSERT INTO PREP_APPMONEDEROQUERY.ESTADODECUENTA (
  UIDESTADODECUENTA, UIDMONEDERO, UIDTIPOTARIFA, UIDESTATUSMONEDERO, INUMMONEDERO, DSALDO, STIPOTARIFA, BACTIVOMONEDERO, BBAJAMONEDERO, UIDMOTIVOMONEDERO,
  UIDMOTIVOTARJETA, UIDTARJETA, INUMEROTARJETA, UIDESTATUSTARJETA, BACTIVOTARJETA, BBAJATARJETA, ITIPOTARJETA, DTFECHAINICIOVIGENCIA, DTFECHAFINVIGENCIA
)
SELECT
  e.UIDESTADODECUENTA, t1.UIDMONEDERO, t1.UIDTIPOTARIFA, e.UIDESTATUS, t1.INUMMONEDERO, e.DSALDO, e.STIPOTARIFA, e.BACTIVO, e.BBAJA, e.UIDMOTIVO,
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
FROM PREP_MONEDEROCOMANDOS.MONEDERO t1
INNER JOIN PREP_MONEDEROCONSULTAS.ESTADODECUENTA e ON t1.UIDMONEDERO = e.UIDMONEDERO 
LEFT JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA t2 
    ON t1.UIDMONEDERO = t2.UIDMONEDERO 
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t1.UIDTIPOSMONEDERO = '9be96cf8-4ee2-4762-9f77-7c817e851c03'AND t2.UIDMONEDERO IS NULL;

************************************************

************************************************
---TODO APLICAR EN LA NOCHE
-- CONSULTA PARA VALIDAR DIFERENCIAS DE SALDO (PREP_APPMONEDEROQUERY)
SELECT --t1.UIDMONEDERO,t1.DSALDO
    COUNT(0) AS discrepancias
        FROM PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
    WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND (t1.DSALDO <> t2.DSALDO)

-- ACTUALIZAR DIFERENCIA DE SALDO (PREP_MONEDEROCONSULTAS vs PREP_APPMONEDEROQUERY)
MERGE INTO PREP_APPMONEDEROQUERY.ESTADODECUENTA dest
USING (
    SELECT t1.UIDMONEDERO,t1.DSALDO
        FROM PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
    WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND (t1.DSALDO <> t2.DSALDO)
) src
ON (dest.UIDMONEDERO = src.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET dest.DSALDO = src.DSALDO;


-- CONSULTA PARA VALIDAR DIFERENCIAS DE ESTATUS
SELECT --t1.UIDMONEDERO, t1.UIDESTATUS
    COUNT(0) AS discrepancias
        FROM  PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO 
    WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND (t1.UIDESTATUS <> t2.UIDESTATUSMONEDERO)

-- 'MONEDEROS diferencia en campo UIDESTATUS (PREP_MONEDEROCONSULTAS vs PREP_APPMONEDEROQUERY)' 
MERGE INTO PREP_APPMONEDEROQUERY.ESTADODECUENTA dest
USING (
    SELECT t1.UIDMONEDERO, t1.UIDESTATUS
        FROM  PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO 
    WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND (t1.UIDESTATUS <> t2.UIDESTATUSMONEDERO)
) src
ON (dest.UIDMONEDERO = src.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET dest.UIDESTATUSMONEDERO = src.UIDESTATUS



************************************************

-- CONSULTA PARA VALIDAR DIFERENCIAS DE MONEDEROS ACTIVOS EN PREP_APPMONEDEROQUERY
SELECT --t1.UIDMONEDERO, t1.BACTIVO
    COUNT(0) AS discrepancias
        FROM PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
    WHERE t1.BACTIVO <> t2.BACTIVOMONEDERO

-- 'MONEDEROS diferencia en campo BACTIVOMONEDERO (PREP_MONEDEROCONSULTAS vs PREP_APPMONEDEROQUERY)'
MERGE INTO PREP_APPMONEDEROQUERY.ESTADODECUENTA dest
USING (
    SELECT t1.UIDMONEDERO, t1.BACTIVO
        FROM PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
    WHERE t1.BACTIVO <> t2.BACTIVOMONEDERO
) src
ON (dest.UIDMONEDERO = src.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET dest.BACTIVOMONEDERO = src.BACTIVO


************************************************

-- CONSULTA PARA VALIDAR DIFERENCIAS DE MONEDEROS NO ACTIVOS EN PREP_APPMONEDEROQUERY
SELECT --t1.UIDMONEDERO, t1.BBAJA
    COUNT(0) AS discrepancias
        FROM PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
    WHERE t1.BBAJA <> t2.BBAJAMONEDERO

-- 'MONEDEROS diferencia en campo BBAJAMONEDERO (PREP_MONEDEROCONSULTAS vs PREP_APPMONEDEROQUERY)'
MERGE INTO PREP_APPMONEDEROQUERY.ESTADODECUENTA dest
USING (
    SELECT t1.UIDMONEDERO, t1.BBAJA
        FROM PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
    WHERE t1.BBAJA <> t2.BBAJAMONEDERO
) src
ON (dest.UIDMONEDERO = src.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET dest.BBAJAMONEDERO = src.BBAJA

*******************************************************
---TODO APLICAR Y REVISAR ESTE DATO EN LA NOCHEXXXXX
-- CONSULTA PARA VALIDAR DIFERENCIAS DE MONEDEROS EN SUS FECHAS DE VIGENCIA EN PREP_APPMONEDEROQUERY
SELECT --DISTINCT U.UIDMONEDEROAPP UIDMONEDERO, P.DTFECHAINICIOPERIODO , P.DTFECHAFINPERIODO
    COUNT(0) AS discrepancias
        FROM PREP_CREDENCIALIZACION.USUARIOSTARJETAS u
        INNER JOIN PREP_CREDENCIALIZACION.PERIODOSTARJETAS p ON p.UIDMONEDERO = U.UIDMONEDEROAPP AND p.BACTIVO = 1
        INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA e ON e.UIDMONEDERO = U.UIDMONEDEROAPP
    WHERE U.BACTIVO = 1 AND U.BBAJA = 0 AND U.UIDTIPOTARIFA <> '24665f64-1ef6-4404-b59a-3fd3cd74a9be'
        AND p.BACTIVO = 1 AND p.BBAJA = 0
        AND (e.DTFECHAFINVIGENCIA is null OR e.DTFECHAFINVIGENCIA <> P.DTFECHAFINPERIODO)

-- DIFERENCIA DE FECHAS DE VIGENCIA EN MONEDEROS
MERGE INTO PREP_APPMONEDEROQUERY.ESTADODECUENTA EDOCUENTA
USING (
    SELECT DISTINCT U.UIDMONEDEROAPP UIDMONEDERO,  P.DTFECHAINICIOPERIODO ,  P.DTFECHAFINPERIODO
        FROM PREP_CREDENCIALIZACION.USUARIOSTARJETAS u
        INNER JOIN PREP_CREDENCIALIZACION.PERIODOSTARJETAS p ON p.UIDMONEDERO = U.UIDMONEDEROAPP AND p.BACTIVO = 1
        INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA e ON e.UIDMONEDERO = U.UIDMONEDEROAPP
    WHERE U.BACTIVO = 1 AND U.BBAJA = 0 AND U.UIDTIPOTARIFA <> '24665f64-1ef6-4404-b59a-3fd3cd74a9be'
        AND p.BACTIVO = 1 AND p.BBAJA = 0
        AND (e.DTFECHAFINVIGENCIA is null OR e.DTFECHAFINVIGENCIA <> P.DTFECHAFINPERIODO)) MONEDEROS
ON (EDOCUENTA.UIDMONEDERO = MONEDEROS.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET EDOCUENTA.DTFECHAINICIOVIGENCIA = MONEDEROS.DTFECHAINICIOVIGENCIA, EDOCUENTA.DTFECHAINICIOPERIODO = MONEDEROS.DTFECHAFINPERIODO

*******************************************************

-- CONSULTA PARA VALIDAR DIFERENCIAS DE TARJETAS EN SUS FECHAS DE VIGENCIA EN PREP_APPMONEDEROQUERY
SELECT --DISTINCT t.UIDMONEDERO, p.DTFECHAINICIOPERIODO , p.DTFECHAFINPERIODO, e.DTFECHAINICIOVIGENCIA, e.DTFECHAFINVIGENCIA--, p.UIDTARJETA 
    COUNT(0) AS discrepancias
        FROM PREP_CREDENCIALIZACION.TARJETAS t
            INNER JOIN PREP_CREDENCIALIZACION.USUARIOSTARJETAS u ON u.UIDTARJETA = t.UIDTARJETA
            INNER JOIN PREP_CREDENCIALIZACION.PERIODOSTARJETAS p ON p.UIDTARJETA = t.UIDTARJETA AND p.BACTIVO = 1
            INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA e ON e.UIDTARJETA = t.UIDTARJETA
    WHERE t.BACTIVO = 1 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.UIDTIPOTARIFA <> '24665f64-1ef6-4404-b59a-3fd3cd74a9be' AND p.BACTIVO = 1
        AND e.DTFECHAFINVIGENCIA is null OR e.DTFECHAFINVIGENCIA <> P.DTFECHAFINPERIODO

-- DIFERENCIA DE FECHAS DE VIGENCIA EN TARJETAS
MERGE INTO PREP_APPMONEDEROQUERY.ESTADODECUENTA EDOCUENTA
USING (
    SELECT DISTINCT t.UIDMONEDERO, p.DTFECHAINICIOPERIODO , p.DTFECHAFINPERIODO
        FROM PREP_CREDENCIALIZACION.TARJETAS t
            INNER JOIN PREP_CREDENCIALIZACION.USUARIOSTARJETAS u ON u.UIDTARJETA = t.UIDTARJETA
            INNER JOIN PREP_CREDENCIALIZACION.PERIODOSTARJETAS p ON p.UIDTARJETA = t.UIDTARJETA AND p.BACTIVO = 1
            INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA e ON e.UIDTARJETA = t.UIDTARJETA
    WHERE t.BACTIVO = 1 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.UIDTIPOTARIFA <> '24665f64-1ef6-4404-b59a-3fd3cd74a9be'
        AND e.DTFECHAFINVIGENCIA is null OR e.DTFECHAFINVIGENCIA <> P.DTFECHAFINPERIODO) TARJETAS
ON (EDOCUENTA.UIDMONEDERO = TARJETAS.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET EDOCUENTA.DTFECHAINICIOVIGENCIA = TARJETAS.DTFECHAINICIOPERIODO, EDOCUENTA.DTFECHAFINVIGENCIA = TARJETAS.DTFECHAFINPERIODO



*******************************************************

-- ESTADO DE CUENTA CON UIDTIPOTARIFA DIFERENTE
SELECT --t1.UIDTARJETA, t1.UIDMOTIVO, t2.UIDMOTIVOTARJETA
    COUNT(0) AS discrepancias
	FROM PREP_CREDENCIALIZACION.TARJETAS t1
	    INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA t2 ON t1.UIDTARJETA = t2.UIDTARJETA
    WHERE T1.BACTIVO = 1 AND T1.BBAJA = 0  AND T1.UIDTIPOTARIFA <> T2.UIDTIPOTARIFA


MERGE INTO PREP_APPMONEDEROQUERY.ESTADODECUENTA dest
USING (
    SELECT t1.UIDMONEDERO, t1.UIDTIPOTARIFA
        FROM PREP_CREDENCIALIZACION.TARJETAS t1
	    INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA t2 ON t1.UIDTARJETA = t2.UIDTARJETA
    WHERE T1.BACTIVO = 1 AND T1.BBAJA = 0  AND T1.UIDTIPOTARIFA <> T2.UIDTIPOTARIFA
) src
ON (dest.UIDMONEDERO = src.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET dest.UIDTIPOTARIFA = src.UIDTIPOTARIFA


*******************************************************

-- ESTADO DE CUENTA CON UIDMOTIVO DIFERENTE  // SIN DIFERENCIAS
SELECT --t1.UIDTARJETA, t1.UIDMOTIVO, t2.UIDMOTIVOTARJETA
    COUNT(0) AS discrepancias
	FROM PREP_CREDENCIALIZACION.TARJETAS t1
	    INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA t2 ON t1.UIDTARJETA = t2.UIDTARJETA
    WHERE T1.BACTIVO = 1 AND T1.BBAJA = 0 AND t1.uidmotivo IS NOT NULL AND (t2.UIDMOTIVOTARJETA IS NULL OR  t1.UIDMOTIVO <> t2.UIDMOTIVOTARJETA)


MERGE INTO PREP_APPMONEDEROQUERY.ESTADODECUENTA dest
USING (
    SELECT t1.UIDMONEDERO, t1.UIDMOTIVO
        FROM PREP_CREDENCIALIZACION.TARJETAS t1
	    INNER JOIN PREP_APPMONEDEROQUERY.ESTADODECUENTA t2 ON t1.UIDTARJETA = t2.UIDTARJETA
    WHERE T1.BACTIVO = 1 AND T1.BBAJA = 0 AND t1.UIDMOTIVO IS NOT NULL AND (t2.UIDMOTIVOTARJETA IS NULL OR  t1.UIDMOTIVO <> t2.UIDMOTIVOTARJETA)
) src
ON (dest.UIDMONEDERO = src.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET dest.UIDMOTIVOTARJETA = src.UIDMOTIVO



*******************************************************

--INICIO
SELECT --t.UIDTARJETA, e.UIDESTADODECUENTA, e.UIDTARJETA
    'TARJETAS no replicadas (PREP_CREDENCIALIZACION vs PREP_APPMONEDEROQUERY)' AS fuente,
    COUNT(0) AS discrepancias
FROM PREP_CREDENCIALIZACION.TARJETAS t
INNER JOIN  PREP_APPMONEDEROQUERY.ESTADODECUENTA e ON ( e.UIDMONEDERO = t.UIDMONEDERO ) 
WHERE t.BACTIVO = 1 AND t.BBAJA = 0 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.BASOCIADA = 1 AND e.UIDTARJETA IS NULL;

-- TARJETAS no replicadas (PREP_CREDENCIALIZACION vs PREP_APPMONEDEROQUERY)
MERGE INTO PREP_APPMONEDEROQUERY.ESTADODECUENTA REPLICA
USING (
	SELECT e.UIDMONEDERO, t.UIDMOTIVO, t.UIDTARJETA, t.INUMEROTARJETA, t.UIDESTATUSTARJETA, t.BACTIVO, t.BBAJA,	t.SCCV	
        FROM PREP_CREDENCIALIZACION.TARJETAS t
	    INNER JOIN  PREP_APPMONEDEROQUERY.ESTADODECUENTA e ON ( e.UIDMONEDERO = t.UIDMONEDERO ) 
	WHERE t.BACTIVO = 1 AND t.BBAJA = 0 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.BASOCIADA = 1 AND e.UIDTARJETA IS NULL
) ORIGEN
ON (REPLICA.UIDMONEDERO = ORIGEN.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET 
        REPLICA.UIDMOTIVOTARJETA = ORIGEN.UIDMOTIVO,
        REPLICA.UIDTARJETA = ORIGEN.UIDTARJETA,
        REPLICA.INUMEROTARJETA = ORIGEN.INUMEROTARJETA,
        REPLICA.UIDESTATUSTARJETA = ORIGEN.UIDESTATUSTARJETA,
        REPLICA.BACTIVOTARJETA = ORIGEN.BACTIVO,
        REPLICA.BBAJATARJETA = ORIGEN.BBAJA
--FIN

*******************************************************

--INICIO
SELECT 
    'TARJETAS diferencias de campo UIDESTATUSTARJETA (PREP_APPMONEDEROQUERY vs PREP_CREDENCIALIZACION)' AS fuente,
    COUNT(0) AS discrepancias
        FROM PREP_APPMONEDEROQUERY.ESTADODECUENTA e 
        INNER JOIN PREP_CREDENCIALIZACION.TARJETAS t ON (e.UIDMONEDERO = t.UIDMONEDERO) 
WHERE t.BACTIVO = 1 AND t.BBAJA = 0 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.BASOCIADA = 1 AND e.UIDTARJETA AND e.UIDESTATUSTARJETA <> t.UIDESTATUSTARJETA;

-- ACTUALIZAR EL UIDESATUSTARJETA PREP_APPMONEDEROQUERY
UPDATE PREP_APPMONEDEROQUERY.ESTADODECUENTA e 
	SET UIDESTATUSTARJETA = (
        SELECT t.UIDESTATUSTARJETA 
			FROM PREP_CREDENCIALIZACION.TARJETAS t
			WHERE e.UIDMONEDERO = t.UIDMONEDERO)
WHERE EXISTS (
	SELECT 1 FROM PREP_CREDENCIALIZACION.TARJETAS t
	WHERE e.UIDMONEDERO = t.UIDMONEDERO AND (e.UIDESTATUSTARJETA <> t.UIDESTATUSTARJETA OR E.UIDESTATUSTARJETA IS NULL)
);



---------------SEBAS

SELECT 
     t.UIDMONEDERO,t.UIDESTATUSTARJETA
        FROM PREP_APPMONEDEROQUERY.ESTADODECUENTA e 
        INNER JOIN PREP_CREDENCIALIZACION.TARJETAS t ON (e.UIDMONEDERO = t.UIDMONEDERO) 
WHERE t.BACTIVO = 1 AND t.BBAJA = 0 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.BASOCIADA = 1 AND e.UIDTARJETA=t.UIDTARJETA AND e.UIDESTATUSTARJETA <> t.UIDESTATUSTARJETA;

-- ACTUALIZAR EL UIDESATUSTARJETA PREP_APPMONEDEROQUERY
MERGE INTO PREP_APPMONEDEROQUERY.ESTADODECUENTA e
USING (
SELECT 
     t.UIDMONEDERO,t.UIDESTATUSTARJETA
        FROM PREP_APPMONEDEROQUERY.ESTADODECUENTA e 
        INNER JOIN PREP_CREDENCIALIZACION.TARJETAS t ON (e.UIDMONEDERO = t.UIDMONEDERO) 
WHERE t.BACTIVO = 1 AND t.BBAJA = 0 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.BASOCIADA = 1 AND e.UIDTARJETA=t.UIDTARJETA AND e.UIDESTATUSTARJETA <> t.UIDESTATUSTARJETA
) t
  ON (e.UIDMONEDERO = t.UIDMONEDERO)
WHEN MATCHED THEN
  UPDATE SET e.UIDESTATUSTARJETA = t.UIDESTATUSTARJETA
  WHERE e.UIDESTATUSTARJETA IS NULL 
     OR e.UIDESTATUSTARJETA <> t.UIDESTATUSTARJETA;


----------
--FIN

*******************************************************

-- CONSULTA PARA VALIDAR DIFERENCIAS TIPOS OPERACIONES EN PREP_APPMONEDEROQUERY
SELECT 
	'TIPOS OPERACIONES no replicados (PREP_CATALOGOS vs PREP_APPMONEDEROQUERY)' AS fuente,
	COUNT(0) AS discrepancias
FROM PREP_CATALOGOS.TIPOOPERACIONES t1
LEFT JOIN PREP_APPMONEDEROQUERY.TIPOOPERACIONES t2 ON t1.UIDTIPOOPERACION = t2.UIDTIPOOPERACION 
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t2.UIDTIPOOPERACION  IS NULL
---SEBAS ESTABA COMPLETAMENTE VACIO
-- TIPOS OPERACIONES no replicados (PREP_CATALOGOS vs PREP_APPMONEDEROQUERY) INSERT
INSERT INTO PREP_APPMONEDEROQUERY.TIPOOPERACIONES (
    UIDTIPOOPERACION, SNOMBRE, SCLAVE, IMODULO, BACTIVO, BBAJA
)
SELECT
    t1.UIDTIPOOPERACION, t1.SNOMBRE, t1.SCLAVE, t1.IMODULO, t1.BACTIVO, t1.BBAJA
FROM PREP_CATALOGOS.TIPOOPERACIONES t1
LEFT JOIN PREP_APPMONEDEROQUERY.TIPOOPERACIONES t2
       ON t1.UIDTIPOOPERACION = t2.UIDTIPOOPERACION
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t2.UIDTIPOOPERACION IS NULL;

************************************************


-- PARAMETROS NO REPLICADOS EN PREP_APPMONEDEROQUERY
-- CONSULTA PARA VALIDAR DIFERENCIAS DE PARÁMETROS EN PREP_APPMONEDEROQUERY
SELECT --t1.SNOMBRE 
    'PARAMETROS no replicados (PREP_APP vs PREP_APPMONEDEROQUERY)' AS fuente,
    COUNT(0) AS discrepancias
FROM PREP_APP.PARAMETROS t1
LEFT JOIN PREP_APPMONEDEROQUERY.PARAMETROS t2 ON t1.UIDPARAMETRO = t2.UIDPARAMETRO
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t2.UIDPARAMETRO IS NULL

-- 'PARAMETROS no replicados (PREP_APP vs PREP_APPMONEDEROQUERY)'
INSERT INTO PREP_APPMONEDEROQUERY.PARAMETROS (
    SNOMBRE, SVALOR, DTFECHACREACION, DTFECHAMODIFICACION, DTFECHABAJA, BACTIVO, BBAJA, 
    UIDUSUARIOCREACION, UIDUSUARIOBAJA, UIDPARAMETRO, UIDUSUARIOMODIFICACION, BENCRIPTADO, SDESCRIPCION
)
SELECT
    t1.SNOMBRE, t1.SVALOR, t1.DTFECHACREACION, t1.DTFECHAMODIFICACION, t1.DTFECHABAJA, t1.BACTIVO, t1.BBAJA,
    t1.UIDUSUARIOCREACION, t1.UIDUSUARIOBAJA, t1.UIDPARAMETRO, t1.UIDUSUARIOMODIFICACION, t1.BENCRIPTADO, t1.SDESCRIPCION
    FROM PREP_APP.PARAMETROS t1
        LEFT JOIN PREP_APPMONEDEROQUERY.PARAMETROS t2
ON t1.UIDPARAMETRO = t2.UIDPARAMETRO
    WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t2.UIDPARAMETRO IS NULL;


************************************************

-- CONSULTA PARA VALIDAR USUARIOS NO REPLICADOS (PREP_APPMONEDEROQUERY)
SELECT 
    'USUARIOS activos no replicados (PREP_APP vs PREP_APPMONEDEROQUERY)' AS fuente,
    COUNT(0) AS discrepancias
FROM PREP_APP.USUARIO t1
LEFT JOIN PREP_APPMONEDEROQUERY.USUARIO t2 ON t1.UIDUSUARIO = t2.UIDUSUARIO
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t2.UIDUSUARIO IS NULL
UNION ALL

INSERT INTO PREP_APPMONEDEROQUERY.USUARIO (
    UIDUSUARIO, SIDAPLICACION, IESTATUSCUENTA
)
SELECT t1.UIDUSUARIO, t1.SIDAPLICACION, t1.IESTATUSCUENTA
    FROM PREP_APP.USUARIO t1
        LEFT JOIN PREP_APPMONEDEROQUERY.USUARIO t2
ON t1.UIDUSUARIO = t2.UIDUSUARIO
    WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t2.UIDUSUARIO IS NULL;

************************************************

-- CONSULTA PARA VALIDAR DIFERENCIAS DE SIDAPLICAICON (PREP_APPMONEDEROQUERY)
SELECT 
    'USUARIOS diferencias en SIDAPLICACION (PREP_APP vs PREP_APPMONEDEROQUERY)' AS fuente,
    COUNT(0) AS discrepancias
FROM PREP_APP.USUARIO u
INNER JOIN PREP_APPMONEDEROQUERY.USUARIO um ON um.UIDUSUARIO = u.UIDUSUARIO
WHERE (u.SIDAPLICACION <> um.SIDAPLICACION OR um.SIDAPLICACION IS NULL) AND u.SIDAPLICACION IS NOT NULL

MERGE INTO PREP_APP.USUARIO tgt
USING (
    SELECT u.UIDUSUARIO, uq.SIDAPLICACION
    FROM PREP_APP.USUARIO u
        INNER JOIN PREP_APPMONEDEROQUERY.USUARIO uq 
ON uq.UIDUSUARIO = u.UIDUSUARIO
    WHERE (u.SIDAPLICACION <> uq.SIDAPLICACION OR uq.SIDAPLICACION IS NULL) AND u.SIDAPLICACION IS NOT NULL
) src
ON (tgt.UIDUSUARIO = src.UIDUSUARIO)
WHEN MATCHED THEN
  UPDATE SET tgt.SIDAPLICACION = src.SIDAPLICACION;

************************************************

-- CONSULTA PARA VALIDAR DIFERENCIAS DE IESTATUSCUENTA (PREP_APPMONEDEROQUERY)
SELECT 
    'USUARIOS diferencias en IESTATUSCUENTA (PREP_APP vs PREP_APPMONEDEROQUERY)' AS fuente,
    COUNT(0) AS discrepancias
FROM PREP_APP.USUARIO u
INNER JOIN PREP_APPMONEDEROQUERY.USUARIO um ON um.UIDUSUARIO = u.UIDUSUARIO
WHERE u.IESTATUSCUENTA <> um.IESTATUSCUENTA

MERGE INTO PREP_APP.USUARIO tgt
USING (
    SELECT u.UIDUSUARIO, uq.IESTATUSCUENTA
        FROM PREP_APP.USUARIO u
    INNER JOIN PREP_APPMONEDEROQUERY.USUARIO uq 
ON uq.UIDUSUARIO = u.UIDUSUARIO
    WHERE u.IESTATUSCUENTA <> uq.IESTATUSCUENTA
) src
ON (tgt.UIDUSUARIO = src.UIDUSUARIO)
WHEN MATCHED THEN
    UPDATE SET tgt.IESTATUSCUENTA = src.IESTATUSCUENTA;

************************************************
