






-- CONSULTA PARA VALIDAR DIFERENCIAS
-- MONEDEROS NO REPLICADOS EN PREP_APPMONEDEROCOMMAND
SELECT --t1.dtfechacreacion,t1.uidmonedero, t2.uidmonedero
    'MONEDEROS no replicados (PREP_MONEDEROCOMANDOS vs PREP_APPMONEDEROCOMMAND)' AS fuente,
    COUNT(0) AS discrepancias
FROM  PREP_MONEDEROCOMANDOS.MONEDERO t1
LEFT JOIN PREP_APPMONEDEROCOMMAND.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO 
INNER JOIN PREP_MONEDEROCONSULTAS.ESTADODECUENTA e ON t1.UIDMONEDERO = e.UIDMONEDERO 
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t1.UIDTIPOSMONEDERO = '9be96cf8-4ee2-4762-9f77-7c817e851c03' AND t2.UIDMONEDERO IS NULL

-- CONSULTA PARA INSERTAR FALTANTES
-- CREAR MONEDEROS NO REPLICADOS EN PREP_APPMONEDEROCOMMAND
INSERT INTO PREP_APPMONEDEROCOMMAND.ESTADODECUENTA (
  UIDESTADODECUENTA, UIDMONEDERO, UIDTIPOTARIFA, UIDESTATUSMONEDERO, INUMMONEDERO, DSALDO, STIPOTARIFA, BACTIVOMONEDERO, BBAJAMONEDERO, UIDMOTIVOMONEDERO,
  UIDMOTIVOTARJETA, UIDTARJETA, INUMEROTARJETA, UIDESTATUSTARJETA, BACTIVOTARJETA, BBAJATARJETA, ITIPOTARJETA, SCCV, DTFECHAVALIDEZ
)
SELECT
  e.UIDESTADODECUENTA, SRC.UIDMONEDERO, SRC.UIDTIPOTARIFA, e.UIDESTATUS, SRC.INUMMONEDERO, e.DSALDO, e.STIPOTARIFA, e.BACTIVO, e.BBAJA, e.UIDMOTIVO,
 null, NULL, null, null, null, null, null, null, null
FROM PREP_MONEDEROCOMANDOS.MONEDERO SRC
INNER JOIN PREP_MONEDEROCONSULTAS.ESTADODECUENTA e ON SRC.UIDMONEDERO = e.UIDMONEDERO 
LEFT JOIN PREP_APPMONEDEROCOMMAND.ESTADODECUENTA TGT
  ON SRC.UIDMONEDERO = TGT.UIDMONEDERO
WHERE  SRC.BACTIVO = 1 AND SRC.BBAJA = 0 AND SRC.UIDTIPOSMONEDERO = '9be96cf8-4ee2-4762-9f77-7c817e851c03' AND TGT.UIDMONEDERO IS NULL;

************************************************

-- CONSULTA PARA VALIDAR DIFERENCIAS DE SALDO (APPMINEDEROCOMMAND)
SELECT --t1.UIDMONEDERO, t1.DSALDO
    COUNT(0) AS discrepancias
        FROM PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROCOMMAND.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
    WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND (t1.DSALDO <> t2.DSALDO)

-- ACTUALIZAR DIFERENCIA DE SALDO (PREP_MONEDEROCONSULTAS vs PREP_APPMONEDEROCOMMAND)
MERGE INTO PREP_APPMONEDEROCOMMAND.ESTADODECUENTA dest
USING (
    SELECT t1.UIDMONEDERO, t1.DSALDO
        FROM PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROCOMMAND.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
    WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND (t1.DSALDO <> t2.DSALDO)
) src
ON (dest.UIDMONEDERO = src.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET dest.DSALDO = src.DSALDO

************************************************

-- CONSULTA PARA VALIDAR DIFERENCIAS DE ESTATUS
SELECT --t1.UIDMONEDERO, t1.UIDESTATUS
    COUNT(0) AS discrepancias
        FROM  PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROCOMMAND.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO 
    WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND (t1.UIDESTATUS <> t2.UIDESTATUSMONEDERO)

-- 'MONEDEROS diferencia en campo UIDESTATUS (PREP_MONEDEROCONSULTAS vs PREP_APPMONEDEROCOMMAND)'
MERGE INTO PREP_APPMONEDEROCOMMAND.ESTADODECUENTA dest
USING (
    SELECT t1.UIDMONEDERO, t1.UIDESTATUS
        FROM  PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROCOMMAND.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO 
    WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND (t1.UIDESTATUS <> t2.UIDESTATUSMONEDERO)
) src
ON (dest.UIDMONEDERO = src.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET dest.UIDESTATUSMONEDERO = src.UIDESTATUS

************************************************

-- CONSULTA PARA VALIDAR DIFERENCIAS DE MONEDEROS ACTIVOS EN PREP_APPMONEDEROCOMMAND
SELECT --t1.UIDMONEDERO, t1.BACTIVO
    COUNT(0) AS discrepancias
        FROM PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROCOMMAND.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
    WHERE t1.BACTIVO <> t2.BACTIVOMONEDERO

-- 'MONEDEROS diferencia en campo BACTIVOMONEDERO (PREP_MONEDEROCONSULTAS vs PREP_APPMONEDEROCOMMAND)'
MERGE INTO PREP_APPMONEDEROCOMMAND.ESTADODECUENTA dest
USING (
    SELECT t1.UIDMONEDERO, t1.BACTIVO
        FROM PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROCOMMAND.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
    WHERE t1.BACTIVO <> t2.BACTIVOMONEDERO
) src
ON (dest.UIDMONEDERO = src.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET dest.BACTIVOMONEDERO = src.BACTIVO

************************************************

-- CONSULTA PARA VALIDAR DIFERENCIAS DE MONEDEROS NO ACTIVOS EN PREP_APPMONEDEROCOMMAND
SELECT --t1.UIDMONEDERO, t1.BBAJA
    COUNT(0) AS discrepancias
        FROM PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROCOMMAND.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
    WHERE t1.BBAJA <> t2.BBAJAMONEDERO

-- 'MONEDEROS diferencia en campo BBAJAMONEDERO (PREP_MONEDEROCONSULTAS vs PREP_APPMONEDEROCOMMAND)'
MERGE INTO PREP_APPMONEDEROCOMMAND.ESTADODECUENTA dest
USING (
    SELECT t1.UIDMONEDERO, t1.BBAJA
        FROM PREP_MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN PREP_APPMONEDEROCOMMAND.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
    WHERE t1.BBAJA <> t2.BBAJAMONEDERO
) src
ON (dest.UIDMONEDERO = src.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET dest.BBAJAMONEDERO = src.BBAJA

*******************************************************

-- ESTADO DE CUENTA CON UIDTIPOTARIFA DIFERENTE
SELECT --t1.UIDTARJETA, t1.UIDTIPOTARIFA, t2.UIDTIPOTARIFA
    COUNT(0) AS discrepancias
	FROM PREP_CREDENCIALIZACION.TARJETAS t1
	    INNER JOIN PREP_APPMONEDEROCOMMAND.ESTADODECUENTA t2 ON t1.UIDTARJETA = t2.UIDTARJETA
    WHERE T1.BACTIVO = 1 AND T1.BBAJA = 0  AND T1.UIDTIPOTARIFA <> T2.UIDTIPOTARIFA

MERGE INTO PREP_APPMONEDEROCOMMAND.ESTADODECUENTA dest
USING (
    SELECT t1.UIDMONEDERO, t1.UIDTIPOTARIFA
        FROM PREP_CREDENCIALIZACION.TARJETAS t1
	    INNER JOIN PREP_APPMONEDEROCOMMAND.ESTADODECUENTA t2 ON t1.UIDTARJETA = t2.UIDTARJETA
    WHERE T1.BACTIVO = 1 AND T1.BBAJA = 0  AND T1.UIDTIPOTARIFA <> T2.UIDTIPOTARIFA
) src
ON (dest.UIDMONEDERO = src.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET dest.UIDTIPOTARIFA = src.UIDTIPOTARIFA

*******************************************************

-- ESTADO DE CUENTA CON UIDMOTIVO DIFERENTE
SELECT --t1.UIDTARJETA, t1.UIDMOTIVO, t2.UIDMOTIVOTARJETA
    COUNT(0) AS discrepancias
	FROM PREP_CREDENCIALIZACION.TARJETAS t1
	    INNER JOIN PREP_APPMONEDEROCOMMAND.ESTADODECUENTA t2 ON t1.UIDTARJETA = t2.UIDTARJETA
    WHERE T1.BACTIVO = 1 AND T1.BBAJA = 0 AND t1.uidmotivo IS NOT NULL AND (t2.UIDMOTIVOTARJETA IS NULL OR  t1.UIDMOTIVO <> t2.UIDMOTIVOTARJETA)

MERGE INTO PREP_APPMONEDEROCOMMAND.ESTADODECUENTA dest
USING (
    SELECT t1.UIDMONEDERO, t1.UIDMOTIVO
        FROM PREP_CREDENCIALIZACION.TARJETAS t1
	    INNER JOIN PREP_APPMONEDEROCOMMAND.ESTADODECUENTA t2 ON t1.UIDTARJETA = t2.UIDTARJETA
    WHERE T1.BACTIVO = 1 AND T1.BBAJA = 0 AND t1.UIDMOTIVO IS NOT NULL AND (t2.UIDMOTIVOTARJETA IS NULL OR  t1.UIDMOTIVO <> t2.UIDMOTIVOTARJETA)
) src
ON (dest.UIDMONEDERO = src.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET dest.UIDMOTIVOTARJETA = src.UIDMOTIVO

*******************************************************
 --TARJETAS
--INICIO
SELECT --t.UIDTARJETA, e.UIDESTADODECUENTA, e.UIDTARJETA
    'TARJETAS no replicadas (PREP_CREDENCIALIZACION vs PREP_APPMONEDEROCOMMAND)' AS fuente,
    COUNT(0) AS discrepancias
FROM PREP_CREDENCIALIZACION.TARJETAS t
INNER JOIN  PREP_APPMONEDEROCOMMAND.ESTADODECUENTA e ON ( e.UIDMONEDERO = t.UIDMONEDERO ) 
WHERE t.BACTIVO = 1 AND t.BBAJA = 0 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.BASOCIADA = 1 AND e.UIDTARJETA IS NULL;

-- TARJETAS no replicadas (PREP_CREDENCIALIZACION vs PREP_APPMONEDEROCOMMAND)
MERGE INTO PREP_APPMONEDEROCOMMAND.ESTADODECUENTA REPLICA
USING (
	SELECT e.UIDMONEDERO, t.UIDMOTIVO, t.UIDTARJETA, t.INUMEROTARJETA, t.UIDESTATUSTARJETA, t.BACTIVO, t.BBAJA,	t.SCCV	
        FROM PREP_CREDENCIALIZACION.TARJETAS t
	    INNER JOIN  PREP_APPMONEDEROCOMMAND.ESTADODECUENTA e ON ( e.UIDMONEDERO = t.UIDMONEDERO ) 
	WHERE t.BACTIVO = 1 AND t.BBAJA = 0 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.BASOCIADA = 1 AND e.UIDTARJETA IS NULL
) ORIGEN
ON (REPLICA.UIDMONEDERO = ORIGEN.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET 
        REPLICA.UIDMOTIVOTARJETA = ORIGEN.UIDMOTIVO,
        REPLICA.UIDTARJETA = ORIGEN.UIDTARJETA,
        REPLICA.INUMEROTARJETA = ORIGEN.INUMEROTARJETA,
        REPLICA.UIDESTATUSTARJETA = ORIGEN.UIDESTATUSTARJETA,
        REPLICA.BACTIVOTARJETA = ORIGEN.BACTIVO,
        REPLICA.BBAJATARJETA = ORIGEN.BBAJA,
        REPLICA.SCCV = ORIGEN.SCCV
--FIN

*******************************************************

--INICIO
SELECT 
    'TARJETAS diferencias de campo UIDESTATUSTARJETA (PREP_APPMONEDEROCOMMAND vs PREP_CREDENCIALIZACION)' AS fuente, 
    COUNT(0) AS discrepancias
FROM PREP_APPMONEDEROCOMMAND.ESTADODECUENTA e 
INNER JOIN PREP_CREDENCIALIZACION.TARJETAS t ON (e.UIDMONEDERO = t.UIDMONEDERO) 
WHERE t.BACTIVO = 1 AND t.BBAJA = 0 AND t.BVENDIDA = 1 AND t.BINICIALIZADA = 1 AND t.BASOCIADA = 1 AND e.UIDTARJETA AND e.UIDESTATUSTARJETA <> t.UIDESTATUSTARJETA;

-- ACTUALIZAR EL UIDESTATUS TARJETA PREP_APPMONEDEROCOMMAND
UPDATE PREP_APPMONEDEROCOMMAND.ESTADODECUENTA e 
	SET UIDESTATUSTARJETA = (
        SELECT t.UIDESTATUSTARJETA 
			FROM PREP_CREDENCIALIZACION.TARJETAS t
			WHERE e.UIDMONEDERO = t.UIDMONEDERO)
WHERE EXISTS (
	SELECT 1 FROM PREP_CREDENCIALIZACION.TARJETAS t
	WHERE e.UIDMONEDERO = t.UIDMONEDERO AND (e.UIDESTATUSTARJETA <> t.UIDESTATUSTARJETA OR E.UIDESTATUSTARJETA IS NULL)
);


----SEBAS

SELECT 
    'TARJETAS diferencias de campo UIDESTATUSTARJETA (PREP_APPMONEDEROCOMMAND vs PREP_CREDENCIALIZACION)' AS fuente, 
    COUNT(0) AS discrepancias
FROM PREP_APPMONEDEROCOMMAND.ESTADODECUENTA e 
INNER JOIN PREP_CREDENCIALIZACION.TARJETAS t ON (e.UIDMONEDERO = t.UIDMONEDERO) 
WHERE t.BACTIVO = 1 AND t.BBAJA = 0 
AND t.BVENDIDA = 1 
AND t.BINICIALIZADA = 1 
AND t.BASOCIADA = 1 
AND e.UIDTARJETA = t.UIDTARJETA 
AND e.UIDESTATUSTARJETA <> t.UIDESTATUSTARJETA;
----
MERGE INTO PREP_APPMONEDEROCOMMAND.ESTADODECUENTA e
USING (
SELECT 
    t.UIDMONEDERO,t.UIDESTATUSTARJETA
FROM PREP_APPMONEDEROCOMMAND.ESTADODECUENTA e 
INNER JOIN PREP_CREDENCIALIZACION.TARJETAS t ON (e.UIDMONEDERO = t.UIDMONEDERO) 
WHERE t.BACTIVO = 1 AND t.BBAJA = 0 
AND t.BVENDIDA = 1 
AND t.BINICIALIZADA = 1 
AND t.BASOCIADA = 1 
AND e.UIDTARJETA = t.UIDTARJETA 
AND e.UIDESTATUSTARJETA <> t.UIDESTATUSTARJETA
) t
  ON (e.UIDMONEDERO = t.UIDMONEDERO)
WHEN MATCHED THEN
  UPDATE SET e.UIDESTATUSTARJETA = t.UIDESTATUSTARJETA
  WHERE e.UIDESTATUSTARJETA IS NULL 
     OR e.UIDESTATUSTARJETA <> t.UIDESTATUSTARJETA;
---------
--FIN

*******************************************************

-- TIPOS OPERACIONES
-- CONSULTA PARA VALIDAR DIFERENCIAS TIPOS OPERACIONES EN PREP_APPMONEDEROCOMMAND
SELECT 
	'TIPOS OPERACIONES no replicados (PREP_CATALOGOS vs PREP_APPMONEDEROCOMMAND)' AS fuente,
	COUNT(0) AS discrepancias
FROM PREP_CATALOGOS.TIPOOPERACIONES t1
LEFT JOIN PREP_APPMONEDEROCOMMAND.TIPOOPERACIONES t2 ON t1.UIDTIPOOPERACION = t2.UIDTIPOOPERACION 
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t2.UIDTIPOOPERACION  IS NULL

-- TIPOS OPERACIONES no replicados (PREP_CATALOGOS vs PREP_APPMONEDEROCOMMAND) INSERT
INSERT INTO PREP_APPMONEDEROCOMMAND.TIPOOPERACIONES (
    UIDTIPOOPERACION, SNOMBRE, SCLAVE, IMODULO, BACTIVO, BBAJA
)
SELECT
    t1.UIDTIPOOPERACION, t1.SNOMBRE, t1.SCLAVE, t1.IMODULO, t1.BACTIVO, t1.BBAJA
FROM PREP_CATALOGOS.TIPOOPERACIONES t1
LEFT JOIN PREP_APPMONEDEROCOMMAND.TIPOOPERACIONES t2
       ON t1.UIDTIPOOPERACION = t2.UIDTIPOOPERACION
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t2.UIDTIPOOPERACION IS NULL;

*******************************************************


--TIPOS TARIFAS
-- CONSULTA PARA VALIDAR DIFERENCIAS TIPOS TARIFAS EN PREP_APPMONEDEROCOMMAND
-- TIPOS TARIFAS no replicados (PREP_CATALOGOS vs PREP_APPMONEDEROCOMMAND) INSERT
SELECT --t1.SCLAVETIPOTARIFA, t2.SCLAVETIPOTARIFA
	'TIPOS TARIFAS no replicados (PREP_CATALOGOS vs PREP_APPMONEDEROCOMMAND)' AS fuente,
	COUNT(0) AS discrepancias
FROM PREP_CATALOGOS.TIPOTARIFAS t1
LEFT JOIN PREP_APPMONEDEROCOMMAND.TIPOSTARIFA t2 ON t1.UIDTIPOTARIFA = t2.UIDTIPOTARIFA 
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t2.UIDTIPOTARIFA IS NULL

-- TIPOS TARIFAS no replicados (PREP_CATALOGOS vs PREP_APPMONEDEROCOMMAND)
INSERT INTO PREP_APPMONEDEROCOMMAND.TIPOSTARIFA (
    UIDTIPOTARIFA, STIPOTARIFA, SCLAVETIPOTARIFA, ITIPOTARJETA
)
SELECT
    t1.UIDTIPOTARIFA, t1.STIPOTARIFA, t1.SCLAVETIPOTARIFA, t1.ITIPOTARJETA
FROM PREP_CATALOGOS.TIPOTARIFAS t1
LEFT JOIN PREP_APPMONEDEROCOMMAND.TIPOSTARIFA t2 
       ON t1.UIDTIPOTARIFA = t2.UIDTIPOTARIFA
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t2.UIDTIPOTARIFA IS NULL;

*************************************************

-- EN CASO DE DIFERENCIAS APLICAR
-- CONSULTA PARA VALIDAR DIFERENCIAS TIPOS TARIFAS EN APPMONEDEROQUERY
SELECT --t1.SCLAVETIPOTARIFA, t2.SCLAVETIPOTARIFA
	'TIPOS TARIFAS diferencia campos Tipos tarifas (PREP_CATALOGOS vs PREP_APPMONEDEROCOMMAND)' AS fuente,
	COUNT(0) AS discrepancias
FROM PREP_CATALOGOS.TIPOTARIFAS t1
INNER JOIN PREP_APPMONEDEROCOMMAND.TIPOSTARIFA t2 ON t1.UIDTIPOTARIFA = t2.UIDTIPOTARIFA 
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND 
(t1.STIPOTARIFA <> t2.STIPOTARIFA OR t1.SCLAVETIPOTARIFA <> t2.SCLAVETIPOTARIFA OR t1.ITIPOTARJETA <> t2.ITIPOTARJETA)

-- 'TIPOS TARIFAS diferencia campos Tipos tarifas (PREP_CATALOGOS vs PREP_APPMONEDEROCOMMAND)
MERGE INTO PREP_APPMONEDEROCOMMAND.TIPOSTARIFA tgt
USING (
    SELECT t1.UIDTIPOTARIFA, t1.STIPOTARIFA, t1.SCLAVETIPOTARIFA, t1.ITIPOTARJETA
        FROM PREP_CATALOGOS.TIPOTARIFAS t1
        INNER JOIN PREP_APPMONEDEROCOMMAND.TIPOSTARIFA t2 
ON t1.UIDTIPOTARIFA = t2.UIDTIPOTARIFA
    WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND (
        t1.STIPOTARIFA <> t2.STIPOTARIFA OR 
        t1.SCLAVETIPOTARIFA <> t2.SCLAVETIPOTARIFA OR 
        t1.ITIPOTARJETA <> t2.ITIPOTARJETA
    )
) src
ON (tgt.UIDTIPOTARIFA = src.UIDTIPOTARIFA)
WHEN MATCHED THEN
  UPDATE SET tgt.STIPOTARIFA = src.STIPOTARIFA, tgt.SCLAVETIPOTARIFA = src.SCLAVETIPOTARIFA, tgt.ITIPOTARJETA = src.ITIPOTARJETA;

************************************************

-- CONSULTA PARA VALIDAR USUARIOS NO REPLICADOS (PREP_APPMONEDEROCOMMAND)
SELECT 
    'USUARIOS activos no replicados (PREP_APP vs PREP_APPMONEDEROCOMMAND)' AS fuente,
    COUNT(0) AS discrepancias
FROM PREP_APP.USUARIO t1
LEFT JOIN PREP_APPMONEDEROCOMMAND.USUARIO t2 ON t1.UIDUSUARIO = t2.UIDUSUARIO
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t2.UIDUSUARIO IS NULL


INSERT INTO PREP_APPMONEDEROCOMMAND.USUARIO (
	SNOMBRE,
	SAPELLIDOPATERNO,
    SAPELLIDOMATERNO,
    STELEFONO,
    SCORREO,
    DTFECHACREACION,
    BACTIVO,
    BBAJA,
    UIDUSUARIO,
    SIDAPLICACION,
    IESTATUSCUENTA
)
SELECT
	t1.SNOMBRE,
	t1.SAPELLIDOPATERNO,
    t1.SAPELLIDOMATERNO,
    t1.STELEFONO,
    t1.SCORREO,
    t1.DTFECHACREACION,
    t1.BACTIVO,
    t1.BBAJA,
    t1.UIDUSUARIO,
    t1.SIDAPLICACION,
    t1.IESTATUSCUENTA
FROM PREP_APP.USUARIO t1
LEFT JOIN PREP_APPMONEDEROCOMMAND.USUARIO t2
       ON t1.UIDUSUARIO = t2.UIDUSUARIO
WHERE t1.BACTIVO = 1
  AND t1.BBAJA = 0
  AND t2.UIDUSUARIO IS NULL;

************************************************
--TODO REVISION DE ESTA PARTE MARCO DIFERENCIAS DEJAR PENDIENTE AUN ESTE
-- CONSULTA PARA VALIDAR DIFERENCIAS DE SIDAPLICAICON (PREP_APPMONEDEROCOMMAND)
SELECT 
    'USUARIOS diferencias en SIDAPLICACION (PREP_APP vs PREP_APPMONEDEROCOMMAND)' AS fuente,
    COUNT(0) AS discrepancias
FROM PREP_APP.USUARIO u
INNER JOIN PREP_APPMONEDEROCOMMAND.USUARIO um ON um.UIDUSUARIO = u.UIDUSUARIO
WHERE (u.SIDAPLICACION <> um.SIDAPLICACION OR um.SIDAPLICACION IS NULL) AND u.SIDAPLICACION IS NOT NULL

MERGE INTO PREP_APP.USUARIO tgt
USING (
    SELECT u.UIDUSUARIO, um.SIDAPLICACION
        FROM PREP_APP.USUARIO u
        INNER JOIN PREP_APPMONEDEROCOMMAND.USUARIO um 
ON um.UIDUSUARIO = u.UIDUSUARIO
    WHERE (u.SIDAPLICACION <> um.SIDAPLICACION OR um.SIDAPLICACION IS NULL) AND u.SIDAPLICACION IS NOT NULL
) src
ON (tgt.UIDUSUARIO = src.UIDUSUARIO)
WHEN MATCHED THEN
  UPDATE SET tgt.SIDAPLICACION = src.SIDAPLICACION;

************************************************
--todo diferencias
-- CONSULTA PARA VALIDAR DIFERENCIAS DE IESTATUSCUENTA (PREP_APPMONEDEROCOMMAND)
SELECT 
    'USUARIOS diferencias en IESTATUSCUENTA (PREP_APP vs PREP_APPMONEDEROCOMMAND)' AS fuente,
    COUNT(0) AS discrepancias
FROM PREP_APP.USUARIO u
INNER JOIN PREP_APPMONEDEROCOMMAND.USUARIO um ON um.UIDUSUARIO = u.UIDUSUARIO
WHERE u.IESTATUSCUENTA <> um.IESTATUSCUENTA

MERGE INTO PREP_APP.USUARIO tgt
USING (
  SELECT 
    u.UIDUSUARIO,
    um.IESTATUSCUENTA
  FROM PREP_APP.USUARIO u
  INNER JOIN PREP_APPMONEDEROCOMMAND.USUARIO um 
    ON um.UIDUSUARIO = u.UIDUSUARIO
  WHERE u.IESTATUSCUENTA <> um.IESTATUSCUENTA
) src
ON (tgt.UIDUSUARIO = src.UIDUSUARIO)
WHEN MATCHED THEN
  UPDATE SET
    tgt.IESTATUSCUENTA = src.IESTATUSCUENTA;