--Diferencias en registros
SELECT 
	'FIREBASETOKEN no replicados (PREP_APP vs PREP_NOTIFICACIONES)' AS fuente,
	COUNT(0) AS discrepancias
FROM  PREP_APP.FIREBASETOKEN t1
LEFT JOIN PREP_NOTIFICACIONES.FIREBASETOKEN t2 ON t1.UIDFIREBASETOKEN  = t2.UIDFIREBASETOKEN 
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t2.UIDFIREBASETOKEN  IS NULL
UNION ALL
--Diferencias en campos
SELECT 
	'FIREBASETOKEN diferencia entre el campo SFCMTOKEN (PREP_APP vs PREP_NOTIFICACIONES)' AS fuente,
	COUNT(0) AS discrepancias
FROM  PREP_APP.FIREBASETOKEN t1
INNER JOIN PREP_NOTIFICACIONES.FIREBASETOKEN t2 ON t1.UIDFIREBASETOKEN  = t2.UIDFIREBASETOKEN 
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND (t1.SFCMTOKEN <> t2.SFCMTOKEN)

UNION ALL

SELECT 
	'USUARIOS no replicados (PREP_APP vs PREP_NOTIFICACIONES)' AS fuente,
	COUNT(0) AS discrepancias
FROM  PREP_APP.USUARIO t1
LEFT JOIN PREP_NOTIFICACIONES.USUARIO t2 ON t1.UIDUSUARIO = t2.UIDUSUARIO
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t2.UIDUSUARIO IS NULL

UNION ALL

SELECT 
	'USUARIOS diferencias en campos (PREP_APP vs PREP_NOTIFICACIONES)' AS fuente,
	COUNT(0) AS discrepancias
FROM  PREP_APP.USUARIO t1
INNER JOIN PREP_NOTIFICACIONES.USUARIO t2 ON t1.UIDUSUARIO = t2.UIDUSUARIO
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND 
(
t1.SNOMBRE <> t2.SNOMBRE 
OR t1.SAPELLIDOPATERNO <> t2.SAPELLIDOPATERNO 
OR t1.SAPELLIDOMATERNO <> t2.SAPELLIDOMATERNO  
OR t1.STELEFONO <> t2.STELEFONO 
OR t1.SCORREO <> t2.SCORREO 
OR t1.UIDMONEDERO <> t2.UIDMONEDERO 
OR t1.SLADA <> t2.SLADA 
)
-------------------
-- SELECT 
-- t1.uidusuario,
-- t2.uidusuario,
-- t1.SNOMBRE,
-- t1.SAPELLIDOPATERNO,
-- t1.SAPELLIDOMATERNO,
-- t1.STELEFONO,
-- t1.SCORREO,
-- t1.UIDMONEDERO,
-- t1.SLADA
-- FROM  PREP_APP.USUARIO t1
-- INNER JOIN PREP_NOTIFICACIONES.USUARIO t2 ON t1.UIDUSUARIO = t2.UIDUSUARIO
-- WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND 
-- (
-- t1.SNOMBRE <> t2.SNOMBRE 
-- OR t1.SAPELLIDOPATERNO <> t2.SAPELLIDOPATERNO 
-- OR t1.SAPELLIDOMATERNO <> t2.SAPELLIDOMATERNO  
-- OR t1.STELEFONO <> t2.STELEFONO 
-- OR t1.SCORREO <> t2.SCORREO 
-- OR t1.UIDMONEDERO <> t2.UIDMONEDERO 
-- OR t1.SLADA <> t2.SLADA 
-- );


-- UPDATE

MERGE INTO PREP_NOTIFICACIONES.USUARIO REPLICA
USING (
SELECT 
t1.uidusuario,
t1.SNOMBRE,
t1.SAPELLIDOPATERNO,
t1.SAPELLIDOMATERNO,
t1.STELEFONO,
t1.SCORREO,
t1.UIDMONEDERO,
t1.SLADA
FROM  PREP_APP.USUARIO t1
INNER JOIN PREP_NOTIFICACIONES.USUARIO t2 ON t1.UIDUSUARIO = t2.UIDUSUARIO
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND 
(
t1.SNOMBRE <> t2.SNOMBRE 
OR t1.SAPELLIDOPATERNO <> t2.SAPELLIDOPATERNO 
OR t1.SAPELLIDOMATERNO <> t2.SAPELLIDOMATERNO  
OR t1.STELEFONO <> t2.STELEFONO 
OR t1.SCORREO <> t2.SCORREO 
OR t1.UIDMONEDERO <> t2.UIDMONEDERO 
OR t1.SLADA <> t2.SLADA 
)
) ORIGEN
ON (REPLICA.uidusuario = ORIGEN.uidusuario)
WHEN MATCHED THEN
UPDATE SET
  REPLICA.SNOMBRE = ORIGEN.SNOMBRE,
  REPLICA.SAPELLIDOPATERNO = ORIGEN.SAPELLIDOPATERNO,
  REPLICA.SAPELLIDOMATERNO = ORIGEN.SAPELLIDOMATERNO,
  REPLICA.STELEFONO= ORIGEN.STELEFONO,
  REPLICA.SCORREO= ORIGEN.SCORREO,
  REPLICA.UIDMONEDERO= ORIGEN.UIDMONEDERO,
  REPLICA.SLADA= ORIGEN.SLADA
  ;
--------------------

UNION ALL

SELECT  --t1.SIDAPLICACION, t2.SIDAPLICACION 
	'USUARIOS diferencia entre el campo SIDAPLICACION (PREP_APP vs PREP_NOTIFICACIONES)' AS fuente,
	COUNT(0) AS discrepancias
FROM  PREP_APP.USUARIO t1
INNER JOIN PREP_NOTIFICACIONES.USUARIO t2 ON t1.UIDUSUARIO = t2.UIDUSUARIO
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND (t1.SIDAPLICACION <> t2.SIDAPLICACION)

--  MERGE INTO PREP_NOTIFICACIONES.USUARIO REPLICA
--  USING (
-- SELECT  t1.uidusuario,t1.SIDAPLICACION
-- FROM  PREP_APP.USUARIO t1
-- INNER JOIN PREP_NOTIFICACIONES.USUARIO t2 ON t1.UIDUSUARIO = t2.UIDUSUARIO
-- WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND (t1.SIDAPLICACION <> t2.SIDAPLICACION)
-- ) ORIGEN
--  ON (REPLICA.uidusuario = ORIGEN.uidusuario)
--  WHEN MATCHED THEN
--  UPDATE SET
--    REPLICA.SIDAPLICACION = ORIGEN.SIDAPLICACION;

-- INSERTS / UPDATES


--Replica 
INSERT INTO PREP_NOTIFICACIONES.FIREBASETOKEN 
(UIDFIREBASETOKEN
,UIDUSUARIO
,SFCMTOKEN
,SNOMBRE
,SAPELLIDOPATERNO
,SAPELLIDOMATERNO
,SCORREO
,STELEFONO
,SIDAPLICACION
,DTFECHACREACION
,DTFECHAMODIFICACION
,UIDMONEDERO)
SELECT
t1.UIDFIREBASETOKEN
,t1.UIDUSUARIO
,t1.SFCMTOKEN
,u.SNOMBRE
,u.SAPELLIDOPATERNO
,u.SAPELLIDOMATERNO
,u.SCORREO
,u.STELEFONO
,t1.SIDAPLICACION
,t1.DTFECHACREACION
,t1.DTFECHAMODIFICACION
,u.UIDMONEDERO
FROM  PREP_APP.FIREBASETOKEN t1
INNER JOIN PREP_APP.USUARIO u ON t1.UIDUSUARIO = u.UIDUSUARIO 
LEFT JOIN PREP_NOTIFICACIONES.FIREBASETOKEN t2 ON t1.UIDFIREBASETOKEN  = t2.UIDFIREBASETOKEN 
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t2.UIDFIREBASETOKEN  IS NULL;


--Actualizacion de campo SFCMTOKEN
MERGE INTO PREP_NOTIFICACIONES.FIREBASETOKEN REPLICA
USING (
	SELECT t1.UIDFIREBASETOKEN, t1.SFCMTOKEN
	FROM  PREP_APP.FIREBASETOKEN t1
	INNER JOIN PREP_NOTIFICACIONES.FIREBASETOKEN t2 ON t1.UIDFIREBASETOKEN  = t2.UIDFIREBASETOKEN 
	WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND (t1.SFCMTOKEN <> t2.SFCMTOKEN)
) ORIGEN
ON REPLICA.UIDFIREBASETOKEN = ORIGEN.UIDFIREBASETOKEN
WHEN MATCHED THEN
UPDATE SET REPLICA.SFCMTOKEN = ORIGEN.SFCMTOKEN;


INSERT INTO PREP_NOTIFICACIONES.USUARIO
(UIDUSUARIO
,SNOMBRE
,SAPELLIDOPATERNO
,SAPELLIDOMATERNO
,STELEFONO
,SCORREO
,UIDMONEDERO
,SLADA
,SIDAPLICACION)
SELECT
t1.UIDUSUARIO
,t1.SNOMBRE
,t1.SAPELLIDOPATERNO
,t1.SAPELLIDOMATERNO
,t1.STELEFONO
,t1.SCORREO
,t1.UIDMONEDERO
,t1.SLADA
,t1.SIDAPLICACION
FROM  PREP_APP.USUARIO t1
LEFT JOIN PREP_NOTIFICACIONES.USUARIO t2 ON t1.UIDUSUARIO = t2.UIDUSUARIO
WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND t2.UIDUSUARIO IS NULL;