
-- Eventos Ladas
SELECT
    'LADAS activos no replicados (PREP_CATALOGOS vs PREP_PAGOSCONSULTAS)' AS fuente,
    COUNT(0) AS discrepancias
FROM PREP_CATALOGOS.LADAS t1
LEFT JOIN PREP_PAGOSCONSULTAS.LADAS t2 ON t1.UIDLADA = t2.UIDLADA
WHERE t2.UIDLADA IS NULL
UNION ALL
SELECT 
    'LADAS diferencias campos (PREP_PAGOSCONSULTAS vs PREP_CATALOGOS)' AS fuente,
    COUNT(0) AS discrepancias
    FROM PREP_CATALOGOS.LADAS t1
INNER JOIN PREP_PAGOSCONSULTAS.LADAS t2 ON t1.UIDLADA = t2.UIDLADA
WHERE t1.BACTIVO = 1 AND (t1.SPAIS <> t2.SPAIS OR t1.SCOUNTRY <> t2.SCOUNTRY
OR t1.SLADA <> t2.SLADA OR t1.STAG <> t2.STAG)

-- Eventos Paquetes
SELECT
    'PAQUETES activos no replicados (PREP_CATALOGOS vs PREP_PAGOSCONSULTAS)' AS fuente,
    COUNT(0) AS discrepancias
FROM PREP_CATALOGOS.PAQUETES t1
LEFT JOIN PREP_PAGOSCONSULTAS.PAQUETES t2 ON t1.UIDPAQUETE = t2.UIDPAQUETE
WHERE t2.UIDPAQUETE IS NULL
UNION ALL
SELECT 
    'PAQUETES diferencias campos (PREP_PAGOSCONSULTAS vs PREP_CATALOGOS)' AS fuente,
    COUNT(0) AS discrepancias
    FROM PREP_CATALOGOS.PAQUETES t1
INNER JOIN PREP_PAGOSCONSULTAS.PAQUETES t2 ON t1.UIDPAQUETE = t2.UIDPAQUETE
WHERE t1.BACTIVO = 1 AND (t1.SNOMBRE <> t2.SNOMBRE OR t1.IUNIDAD <> t2.IUNIDAD
OR t1.SDESCRIPCION <> t2.SDESCRIPCION)

-- Eventos Productos
SELECT 
    'Productos diferencias campos FPRECIOUNITARIO (PREP_PAGOSCONSULTAS vs PREP_CATALOGOS)' AS fuente,
    COUNT(0) AS discrepancias
    FROM PREP_CATALOGOS.PRODUCTOS t1
INNER JOIN PREP_PAGOSCONSULTAS.PAQUETES t2 ON t1.UIDPRODUCTO = t2.UIDPRODUCTO
WHERE t1.BACTIVO = 1 AND (t1.FPRECIOUNITARIO <> t2.FPRECIO )
UNION ALL
SELECT 
    'Productos dados de baja (PREP_PAGOSCONSULTAS vs PREP_CATALOGOS)' AS fuente,
    COUNT(0) AS discrepancias
    FROM PREP_CATALOGOS.PRODUCTOS t1
INNER JOIN PREP_PAGOSCONSULTAS.PAQUETES t2 ON t1.UIDPRODUCTO = t2.UIDPRODUCTO
WHERE t1.BACTIVO <> t2.BACTIVO OR t1.BBAJA <> t2.BBAJA

----------------------- INSERT / UPDATES -----------------------


-- LADAS activos no replicados (PREP_CATALOGOS vs PREP_PAGOSCONSULTAS)
INSERT INTO PREP_PAGOSCONSULTAS.LADAS (
  UIDLADA,
  SPAIS,
  SCOUNTRY,
  SLADA,
  BACTIVO,
  BBAJA,
  STAG
)
SELECT
  t1.UIDLADA,
  t1.SPAIS,
  t1.SCOUNTRY,
  t1.SLADA,
  t1.BACTIVO,
  t1.BBAJA,
  t1.STAG
FROM PREP_CATALOGOS.LADAS t1
LEFT JOIN PREP_PAGOSCONSULTAS.LADAS t2
  ON t1.UIDLADA = t2.UIDLADA
WHERE t2.UIDLADA IS NULL;

-- LADAS diferencias campos (PREP_PAGOSCONSULTAS vs PREP_CATALOGOS)
MERGE INTO PREP_PAGOSCONSULTAS.LADAS AS tgt
USING (
    SELECT
      t1.UIDLADA,
      t1.SPAIS,
      t1.SCOUNTRY,
      t1.SLADA,
      t1.STAG
    FROM PREP_CATALOGOS.LADAS t1
    INNER JOIN PREP_PAGOSCONSULTAS.LADAS t2
      ON t1.UIDLADA = t2.UIDLADA
    WHERE t1.BACTIVO = 1
      AND (
           t1.SPAIS    <> t2.SPAIS
        OR t1.SCOUNTRY <> t2.SCOUNTRY
        OR t1.SLADA     <> t2.SLADA
        OR t1.STAG      <> t2.STAG
      )
) AS src
ON (tgt.UIDLADA = src.UIDLADA)
WHEN MATCHED THEN
  UPDATE SET
    tgt.SPAIS     = src.SPAIS,
    tgt.SCOUNTRY  = src.SCOUNTRY,
    tgt.SLADA     = src.SLADA,
    tgt.STAG      = src.STAG;

-- PAQUETES activos no replicados (PREP_CATALOGOS vs PREP_PAGOSCONSULTAS)
INSERT INTO PREP_PAGOSCONSULTAS.PAQUETES (
  UIDPAQUETE,
  SNOMBRE,
  UIDPRODUCTO,
  BACTIVO,
  BBAJA,
  IUNIDAD,
  SDESCRIPCION,
  FPRECIO
)
SELECT
  t1.UIDPAQUETE,
  t1.SNOMBRE,
  t1.UIDPRODUCTO,
  t1.BACTIVO,
  t1.BBAJA,
  t1.IUNIDAD,
  t1.SDESCRIPCION,
  t1.FPRECIO
FROM PREP_CATALOGOS.PAQUETES t1
LEFT JOIN PREP_PAGOSCONSULTAS.PAQUETES t2
  ON t1.UIDPAQUETE = t2.UIDPAQUETE
WHERE t2.UIDPAQUETE IS NULL;
-----------SEBAS
INSERT INTO PREP_PAGOSCONSULTAS.PAQUETES (
  UIDPAQUETE,
  SNOMBRE,
  UIDPRODUCTO,
  BACTIVO,
  BBAJA,
  IUNIDAD,
  SDESCRIPCION,
  FPRECIO
)
SELECT
  t1.UIDPAQUETE,
  t1.SNOMBRE,
  t1.UIDPRODUCTO,
  t1.BACTIVO,
  t1.BBAJA,
  t1.IUNIDAD,
  t1.SDESCRIPCION,
  1
FROM PREP_CATALOGOS.PAQUETES t1
LEFT JOIN PREP_CATALOGOS.PAQUETES t2
  ON t1.UIDPAQUETE = t2.UIDPAQUETE
WHERE t2.UIDPAQUETE IS NULL;
----
-- PAQUETES diferencias campos (PREP_PAGOSCONSULTAS vs PREP_CATALOGOS)
MERGE INTO PREP_PAGOSCONSULTAS.PAQUETES AS tgt
USING (
    SELECT 
      t1.UIDPAQUETE,
      t1.SNOMBRE,
      t1.IUNIDAD,
      t1.SDESCRIPCION
    FROM PREP_CATALOGOS.PAQUETES t1
    INNER JOIN PREP_PAGOSCONSULTAS.PAQUETES t2
      ON t1.UIDPAQUETE = t2.UIDPAQUETE
    WHERE t1.BACTIVO = 1
      AND (
           t1.SNOMBRE     <> t2.SNOMBRE
        OR t1.IUNIDAD     <> t2.IUNIDAD
        OR t1.SDESCRIPCION <> t2.SDESCRIPCION
      )
) AS src
ON (tgt.UIDPAQUETE = src.UIDPAQUETE)
WHEN MATCHED THEN
  UPDATE SET
    tgt.SNOMBRE       = src.SNOMBRE,
    tgt.IUNIDAD       = src.IUNIDAD,
    tgt.SDESCRIPCION  = src.SDESCRIPCION;
------------- SEBAS
MERGE INTO PREP_PAGOSCONSULTAS.PAQUETES tgt
USING (
    SELECT 
      t1.UIDPAQUETE,
      t1.SNOMBRE,
      t1.IUNIDAD,
      t1.SDESCRIPCION
    FROM PREP_CATALOGOS.PAQUETES t1
    INNER JOIN PREP_PAGOSCONSULTAS.PAQUETES t2
      ON t1.UIDPAQUETE = t2.UIDPAQUETE
    WHERE t1.BACTIVO = 1
      AND (
           t1.SNOMBRE     <> t2.SNOMBRE
        OR t1.IUNIDAD     <> t2.IUNIDAD
        OR t1.SDESCRIPCION <> t2.SDESCRIPCION
      )
) src
ON (tgt.UIDPAQUETE = src.UIDPAQUETE)
WHEN MATCHED THEN
  UPDATE SET
    tgt.SNOMBRE       = src.SNOMBRE,
    tgt.IUNIDAD       = src.IUNIDAD,
    tgt.SDESCRIPCION  = src.SDESCRIPCION;
-----
-- Productos diferencias campos FPRECIOUNITARIO (PREP_PAGOSCONSULTAS vs PREP_CATALOGOS)
MERGE INTO PREP_PAGOSCONSULTAS.PAQUETES AS tgt
USING (
    SELECT
      p.UIDPRODUCTO,
      p.FPRECIOUNITARIO
    FROM PREP_CATALOGOS.PRODUCTOS p
    INNER JOIN PREP_PAGOSCONSULTAS.PAQUETES q
      ON p.UIDPRODUCTO = q.UIDPRODUCTO
    WHERE p.BACTIVO = 1
      AND (
        p.FPRECIOUNITARIO <> q.FPRECIO
        OR (p.FPRECIOUNITARIO IS NULL AND q.FPRECIO IS NOT NULL)
        OR (p.FPRECIOUNITARIO IS NOT NULL AND q.FPRECIO IS NULL)
      )
) AS src
ON tgt.UIDPRODUCTO = src.UIDPRODUCTO
WHEN MATCHED THEN
  UPDATE SET
    tgt.FPRECIO = src.FPRECIOUNITARIO;

-----SEBAS

 MERGE INTO PREP_PAGOSCONSULTAS.PAQUETES tgt
USING (
    SELECT
      p.UIDPRODUCTO,
      p.FPRECIOUNITARIO
    FROM PREP_CATALOGOS.PRODUCTOS p
    INNER JOIN PREP_PAGOSCONSULTAS.PAQUETES q
      ON p.UIDPRODUCTO = q.UIDPRODUCTO
    WHERE p.BACTIVO = 1
      AND (
        p.FPRECIOUNITARIO <> q.FPRECIO
        OR (p.FPRECIOUNITARIO IS NULL AND q.FPRECIO IS NOT NULL)
        OR (p.FPRECIOUNITARIO IS NOT NULL AND q.FPRECIO IS NULL))
              GROUP BY  p.UIDPRODUCTO,p.FPRECIOUNITARIO

) src
ON ( tgt.UIDPRODUCTO = src.UIDPRODUCTO)
WHEN MATCHED THEN
  UPDATE SET
    tgt.FPRECIO = src.FPRECIOUNITARIO;
------------

















