

ALTER USER APP IDENTIFIED BY "Ppa$2025$";
ALTER USER APPMONEDEROCOMMAND IDENTIFIED BY "Dnammocoredenomppa$2025$";
ALTER USER APPMONEDEROQUERY IDENTIFIED BY "Yreuqoredenomppa$2025$";
ALTER USER APPTICKETS IDENTIFIED BY "Stekcitppa$2025$";
ALTER USER APPUSUARIOQUERY IDENTIFIED BY "Yreuqoirausuppa$2025$";
ALTER USER CATALOGOS IDENTIFIED BY "Sogolatac$2025$";
ALTER USER COMERCIO IDENTIFIED BY "Oicremoc$2025$";
ALTER USER COMERCIOCOMANDOS IDENTIFIED BY "Sodnamocoicremoc$2025$";
ALTER USER COMERCIOCONSULTAS IDENTIFIED BY "Satlusnocoicremoc$2025$";
ALTER USER CREDENCIALIZACION IDENTIFIED BY "Noicazilaicnederc$2025$";
ALTER USER DBA_READER IDENTIFIED BY "Redaer_abd$2025$";
ALTER USER ESTATUSMONEDERO IDENTIFIED BY "Oredenomsutatse$2025$";
ALTER USER MONEDEROCOMANDOS IDENTIFIED BY "Sodnamocoredenom$2025$";
ALTER USER MONEDEROCONSULTAS IDENTIFIED BY "Satlusnocoredenom$2025$";
ALTER USER NOTIFICACIONES IDENTIFIED BY "Senoicacifiton$2025$";
ALTER USER OPENLOOP IDENTIFIED BY "Poolnepo$2025$";
ALTER USER PAGOS IDENTIFIED BY "Sogap$2025$";
ALTER USER PAGOSCONSULTAS IDENTIFIED BY "Satlusnocsogap$2025$";
ALTER USER RIDANGOSYNC IDENTIFIED BY "Cnysognadir$2025$";
ALTER USER SEGURIDAD IDENTIFIED BY "Dadiruges$2025$";
ALTER USER SIGNALRQUERY IDENTIFIED BY "Yreuqrlangis$2025$";
ALTER USER SINCRONIZADOR IDENTIFIED BY "Rodazinorcnis$2025$";
ALTER USER TARIFAS IDENTIFIED BY "Safirat$2025$";
ALTER USER TICKETS IDENTIFIED BY "Stekcit$2025$";


