



USE STG_TRANSPORTE
CREATE TABLE DBO.ATY_CATALOGOS_COMERCIOS (

    [ID_COMERCIO] VARCHAR(50) NOT NULL PRIMARY KEY,
[NOMBRE_COMERCIO] VARCHAR(50) NOT NULL,
[GRUPO_COMERCIAL] VARCHAR(50) NOT NULL,

);