--NUEVA TABLA
CREATE TABLE "RIDANGOSYNC"."RUTAS_HORARIO_INFORMACION" 
   (	"UIDINFORMACIONHORARIO" VARCHAR2(36 BYTE) COLLATE "USING_NLS_COMP", 
	"DTFECHACREACION" TIMESTAMP (6) NOT NULL ENABLE, 
	"DTFECHABAJA" TIMESTAMP (6), 
	"BACTIVO" NUMBER(1,0), 
	"BBAJA" NUMBER(1,0), 
	"IVERSIONCONSECUTIVO" NUMBER(38,0), 
	 CONSTRAINT "INFOHORARIO_PK" PRIMARY KEY ("UIDINFORMACIONHORARIO")
  ) TABLESPACE "DATA"   NO INMEMORY ;

   COMMENT ON COLUMN "RIDANGOSYNC"."RUTAS_HORARIO_INFORMACION"."UIDINFORMACIONHORARIO" IS 'Identificador único de la información.';
   COMMENT ON COLUMN "RIDANGOSYNC"."RUTAS_HORARIO_INFORMACION"."DTFECHACREACION" IS 'Fecha de creación del registro.';
   COMMENT ON COLUMN "RIDANGOSYNC"."RUTAS_HORARIO_INFORMACION"."DTFECHABAJA" IS 'Fecha de baja (si aplica).';
   COMMENT ON COLUMN "RIDANGOSYNC"."RUTAS_HORARIO_INFORMACION"."BACTIVO" IS 'Indicador de si el registro está activo.';
   COMMENT ON COLUMN "RIDANGOSYNC"."RUTAS_HORARIO_INFORMACION"."BBAJA" IS 'Indicador de baja (1=Sí, 0=No).';
   COMMENT ON COLUMN "RIDANGOSYNC"."RUTAS_HORARIO_INFORMACION"."IVERSIONCONSECUTIVO" IS 'Número consecutivo de versión interna de horarios de rutas.';

--SECUENCIADOR
CREATE SEQUENCE CONS_VERSION_HR
  MINVALUE 0
  START WITH 0
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

--Validar creación de secuenciador 
SELECT sequence_name, min_value, max_value, increment_by, last_number
FROM user_sequences;