
-- IDIRECCION TABLA RUTAS
ALTER TABLE RIDANGOSYNC.RUTAS ADD IDIRECCION NUMBER(5,0) NULL;
COMMENT ON COLUMN RIDANGOSYNC.RUTAS.IDIRECCION IS 'Dirección en la cual va el autobus';


-- RIDANGOSYNC.VIEW_RUTA_VERSION_R source

CREATE OR REPLACE FORCE EDITIONABLE VIEW "RIDANGOSYNC"."VIEW_RUTA_VERSION_R" ("VERSION", "SVARIANTE", "SCODE", "IIDRUTA", "SNOMBRE", "ID", "IDIRECCION") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT MAX(IVERSION) VERSION, SVARIANTE, SCODE, IDRUTA_MRP IIDRUTA, SNOMBRE, MAX(r.IIDRUTA) ID, IDIRECCION
FROM RUTAS r
WHERE BACTIVO = 1
GROUP BY SVARIANTE, SCODE, IDRUTA_MRP, SNOMBRE, IDIRECCION
;


-- SELECT MAX(IVERSION) VERSION, SVARIANTE, SCODE, IDRUTA_MRP IIDRUTA, SNOMBRE
-- FROM RUTAS r
-- WHERE BACTIVO = 1
-- GROUP BY SVARIANTE, SCODE, IDRUTA_MRP, SNOMBRE

-- RIDANGOSYNC.FORMAS_RUTAS definition

CREATE TABLE "RIDANGOSYNC"."FORMAS_RUTAS" 
   (	
    "UIDFORMA" VARCHAR2(36), 
	"SIDFORMA" VARCHAR2(20) NOT NULL ENABLE, 
	"SPUNTOLATITUD" VARCHAR2(20) NOT NULL ENABLE, 
	"SPUNTOLONGITUD" VARCHAR2(20) NOT NULL ENABLE, 
	"ISECUENCIA" NUMBER(38,0) NOT NULL ENABLE, 
	"SNOMBRERUTA" VARCHAR2(30), 
	"SIDSECUENCIA" VARCHAR2(20), 
	"DTFECHACREACION" DATE NOT NULL ENABLE, 
	"DTFECHAMODIFICACION" DATE, 
	"DTFECHABAJA" DATE, 
	"BACTIVO" NUMBER(1,0), 
	"BBAJA" NUMBER(1,0), 
	 CONSTRAINT "FORMAS_RIDANGO_PK" PRIMARY KEY ("UIDFORMA")
   )
  TABLESPACE "DATA";

COMMENT ON COLUMN RIDANGOSYNC.FORMAS_RUTAS.UIDFORMA IS 'Identificador único de la forma.';
COMMENT ON COLUMN RIDANGOSYNC.FORMAS_RUTAS.SIDFORMA IS 'Identificador numérico de la forma. Numero de Ruta';
COMMENT ON COLUMN RIDANGOSYNC.FORMAS_RUTAS.SPUNTOLATITUD IS 'Latitud del punto.';
COMMENT ON COLUMN RIDANGOSYNC.FORMAS_RUTAS.SPUNTOLONGITUD IS 'Longitud del punto.';
COMMENT ON COLUMN RIDANGOSYNC.FORMAS_RUTAS.ISECUENCIA IS 'Secuencia de orden del punto.';
COMMENT ON COLUMN RIDANGOSYNC.FORMAS_RUTAS.SNOMBRERUTA IS 'Nonbre corto de la ruta';
COMMENT ON COLUMN RIDANGOSYNC.FORMAS_RUTAS.SIDSECUENCIA IS 'Identificador compuesto de forma-secuencia (PK).';
COMMENT ON COLUMN RIDANGOSYNC.FORMAS_RUTAS.DTFECHACREACION IS 'Fecha de creación del registro.';
COMMENT ON COLUMN RIDANGOSYNC.FORMAS_RUTAS.DTFECHAMODIFICACION IS 'Fecha de última modificación.';
COMMENT ON COLUMN RIDANGOSYNC.FORMAS_RUTAS.DTFECHABAJA IS 'Fecha de baja del registro.';
COMMENT ON COLUMN RIDANGOSYNC.FORMAS_RUTAS.BACTIVO IS 'Indicador de si el registro está activo (1=Sí, 0=No).';
COMMENT ON COLUMN RIDANGOSYNC.FORMAS_RUTAS.BBAJA IS 'Indicador de baja (1=Sí, 0=No).';

-- RIDANGOSYNC.PARADEROS definition

CREATE TABLE "RIDANGOSYNC"."PARADEROS" 
   (
    	"UIDPARADA" VARCHAR2(36), 
	"SIDPARADA" VARCHAR2(20) NOT NULL ENABLE, 
	"SCODIGO" VARCHAR2(20), 
	"SNOMBRE" VARCHAR2(100), 
	"SDESCRIPCION" VARCHAR2(300), 
	"SLATITUD" VARCHAR2(50), 
	"SLONGITUD" VARCHAR2(50), 
	"SESTACIONID" VARCHAR2(50), 
	"SESTACIONCODIGO" VARCHAR2(50), 
	"SNUMDIRECTOPARADA" VARCHAR2(50), 
	"DTFECHACREACION" DATE NOT NULL ENABLE, 
	"DTFECHABAJA" DATE, 
	"BACTIVO" NUMBER(1,0), 
	"BBAJA" NUMBER(1,0), 
	"DTFECHAMODIFICACION" DATE, 
	 CONSTRAINT "PARADA_RIDANGO_PK" PRIMARY KEY ("UIDPARADA")
   )  
  TABLESPACE "DATA"  NO INMEMORY ;


COMMENT ON COLUMN RIDANGOSYNC.PARADEROS.UIDPARADA IS 'Identificador único de la parada.';
COMMENT ON COLUMN RIDANGOSYNC.PARADEROS.SIDPARADA IS 'Identificador numérico de la parada.';
COMMENT ON COLUMN RIDANGOSYNC.PARADEROS.SCODIGO IS 'Código único de la parada.';
COMMENT ON COLUMN RIDANGOSYNC.PARADEROS.SNOMBRE IS 'Nombre de la parada.';
COMMENT ON COLUMN RIDANGOSYNC.PARADEROS.SDESCRIPCION IS 'Descripción de la parada.';
COMMENT ON COLUMN RIDANGOSYNC.PARADEROS.SLATITUD IS 'Latitud de la ubicación de la parada.';
COMMENT ON COLUMN RIDANGOSYNC.PARADEROS.SLONGITUD IS 'Longitud de la ubicación de la parada.';
COMMENT ON COLUMN RIDANGOSYNC.PARADEROS.SESTACIONID IS 'Identificador de zona asociada.';
COMMENT ON COLUMN RIDANGOSYNC.PARADEROS.SESTACIONCODIGO IS 'Código de zona asociada';
COMMENT ON COLUMN RIDANGOSYNC.PARADEROS.SNUMDIRECTOPARADA IS 'Numero directo de la parada';
COMMENT ON COLUMN RIDANGOSYNC.PARADEROS.DTFECHACREACION IS 'Fecha de creación.';
COMMENT ON COLUMN RIDANGOSYNC.PARADEROS.DTFECHABAJA IS 'Fecha de baja.';
COMMENT ON COLUMN RIDANGOSYNC.PARADEROS.BACTIVO IS 'Indicador de si está activo.';
COMMENT ON COLUMN RIDANGOSYNC.PARADEROS.BBAJA IS 'Indicador de baja.';
COMMENT ON COLUMN RIDANGOSYNC.PARADEROS.DTFECHAMODIFICACION IS 'Fecha de última modificación.';







----------------------Saber cuantas tablas sobre las que se van a cargar


SELECT "v"."IIDRUTA" "iIdRuta", N'x' "sCode", "f"."SPUNTOLATITUD" "sPuntoLatitud", "f"."SPUNTOLONGITUD" "sPuntoLongitud", "f"."ISECUENCIA" "iSecuencia", COALESCE("v"."IDIRECCION", 0) "iDireccion"
FROM "RIDANGOSYNC.VIEW_RUTA_VERSION_R" "v"
INNER JOIN "FORMAS_RUTAS" "f" ON "v"."ID" = "f"."SIDFORMA"
WHERE "v"."IIDRUTA" = 1
GROUP BY "v"."IIDRUTA", "f"."SPUNTOLATITUD", "f"."SPUNTOLONGITUD", "f"."ISECUENCIA", "v"."IDIRECCION"
ORDER BY "v"."IDIRECCION", "f"."ISECUENCIA"



