insert into SINCRONIZADOR.RECARGAS_PENDIENTES (UIDOPERACION, UIDMONEDERO, INUMEROTARJETA, SPANHASH, DTFECHAOPERACION,
                                               DMONTO, BAPLICADA, BDUPLICADA)
SELECT distinct --trunc(m.dtfechacreacion),count(*)
                M.UIDOPERACION,
                M.UIDMONEDERO,
                T.INUMEROTARJETA,
                T.SPANHASH,
                M.dtfechacreacion,
                M.DMONTO,
                0 AS BAPLICADA,
                0 AS BDUPLICADA
FROM MONEDEROCOMANDOS.movimientosestadosdecuenta M
         INNER JOIN CREDENCIALIZACION.TARJETAS T ON T.UIDMONEDERO = M.UIDMONEDERO
         LEFT JOIN SINCRONIZADOR.CAMBIOSMONEDERO C ON C.IDOPERACION = M.UIDOPERACION
--C.STARJETA = T.INUMEROTARJETA AND TRUNC(C.dtfechacreacion) = TRUNC(M.dtfechacreacion) AND C.DSALDOACTUAL = M.DMONTO
--BY INUMEROTARJETA,IERROR)) XX ON XX.INUMEROTARJETA = T.INUMEROTARJETA AND XX.ID_ = 1
WHERE UIDTIPOSMONEDERO = 'e7f21096-73e4-4fe9-aed6-ee29947304b0'
  AND UIDTIPOMOVIMIENTO = 'ef008eb7-ea41-46bb-814e-f94979913ceb'
  AND UIDTIPOTRANSACCION = 'e350f3d3-c742-4a13-9674-edeafc171893'
--AND C.IDOPERACION IS NULL
  and M.UIDOPERACION NOT IN (SELECT IDOPERACION FROM SINCRONIZADOR.CAMBIOSMONEDERO)
--   and (
--     dtfechaoperacion >= TO_DATE('16-11-2025 11:00:00', 'DD-MM-YYYY HH24:MI:SS')
--         AND dtfechaoperacion < TO_DATE('16-11-2025 11:06:00', 'DD-MM-YYYY HH24:MI:SS')
--     )
  AND M.UIDOPERACION not in (SELECT UIDOPERACION FROM SINCRONIZADOR.RECARGAS_PENDIENTES)
--and t.inumerotarjeta IN (5000000000263189)
  and m.uidoperacion in ('4f19f95f-81f2-4db0-b201-baa446db7124')
--AND C.ITIPOBLOQUEADO = 0
--AND XX.IERROR = 2
--group by trunc(m.dtfechacreacion)
-- order by trunc(m.dtfechacreacion) asc;
--commit;


-- select * from SINCRONIZADOR.RECARGAS_PENDIENTES where BAPLICADA = 0 and BDUPLICADA = 0;

select * from SINCRONIZADOR.RECARGAS_PENDIENTES where UIDOPERACION in ('74903d6e-8d80-4b64-b0cc-3a246b907b09')












--------------------INCREMENTO DE TRASACCIONES DENEGADAS POR BLOQUEO
-----------------FECHAS 14/11/2025 AL 18/11/2025
----------------COMPARARLO FIN DE SEMANA CON FIN DE SEMANA


