
MERGE INTO APPMONEDEROCOMMAND.ESTADODECUENTA dest
USING (
    SELECT t1.UIDMONEDERO, t1.DSALDO
        FROM MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN APPMONEDEROCOMMAND.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
    WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND (t1.DSALDO <> t2.DSALDO)
) src
ON (dest.UIDMONEDERO = src.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET dest.DSALDO = src.DSALDO;
-- commit;

--------------------------------------------------------


MERGE INTO APPMONEDEROQUERY.ESTADODECUENTA dest
USING (
    SELECT t1.UIDMONEDERO,t1.DSALDO
        FROM MONEDEROCONSULTAS.ESTADODECUENTA t1
        INNER JOIN APPMONEDEROQUERY.ESTADODECUENTA t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
    WHERE t1.BACTIVO = 1 AND t1.BBAJA = 0 AND (t1.DSALDO <> t2.DSALDO)
) src
ON (dest.UIDMONEDERO = src.UIDMONEDERO)
WHEN MATCHED THEN
    UPDATE SET dest.DSALDO = src.DSALDO;
-- commit;


---------------------------------------------------------------


MERGE INTO APP.ESTADODECUENTA REPLICA
USING (
	SELECT t1.UIDMONEDERO, t1.DSALDO
	FROM MONEDEROCONSULTAS.ESTADODECUENTA t1
	INNER JOIN APP.ESTADODECUENTA  t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
	WHERE t1.DSALDO <> t2.DSALDO
) ORIGEN
ON (REPLICA.UIDMONEDERO = ORIGEN.UIDMONEDERO)
WHEN MATCHED THEN
UPDATE SET REPLICA.DSALDO = ORIGEN.DSALDO;
-- commit;


------------------------------------------------------------------
MERGE INTO pagos.estadodecuenta REPLICA
USING (
	SELECT t1.UIDMONEDERO, t1.DSALDO
	FROM MONEDEROCONSULTAS.ESTADODECUENTA t1
	INNER JOIN pagos.estadodecuenta  t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
	WHERE t1.DSALDO <> t2.DSALDO
) ORIGEN
ON (REPLICA.UIDMONEDERO = ORIGEN.UIDMONEDERO)
WHEN MATCHED THEN
UPDATE SET REPLICA.DSALDO = ORIGEN.DSALDO;
-- commit;
-------------------------------------------------------------
MERGE INTO apptickets.estadodecuenta REPLICA
USING (
	SELECT t1.UIDMONEDERO, t1.DSALDO
	FROM MONEDEROCONSULTAS.ESTADODECUENTA t1
	INNER JOIN apptickets.estadodecuenta  t2 ON t1.UIDMONEDERO = t2.UIDMONEDERO
	WHERE t1.DSALDO <> t2.DSALDO
) ORIGEN
ON (REPLICA.UIDMONEDERO = ORIGEN.UIDMONEDERO)
WHEN MATCHED THEN
UPDATE SET REPLICA.DSALDO = ORIGEN.DSALDO;
-- Commit;








--------------------- REPLICAS SALDOS MONEDEROCONSULTAS A COMERCIO MONEDERO TARJETAS
merge into Comercio.MonederosTarjetas mt
using (
    SELECT mt.UIDTARJETA,edc.DSALDO
FROM Comercio.MonederosTarjetas mt
LEFT JOIN MONEDEROCONSULTAS.EstadoDeCuenta edc
  ON mt.uidTarjeta = edc.uidTarjeta
WHERE (edc.uidTarjeta IS NULL OR mt.DSaldo != edc.DSaldo)
  AND mt.bActivo = 1
  AND mt.bBaja = 0
  AND mt.bVendida = 1
)
 ORIGEN on (ORIGEN.UIDTARJETA = MT.UIDTARJETA)
when matched then
    update set mt.DSALDO =ORIGEN.DSALDO;








