
-- TICKETS : 


		CREATE TABLE TICKETS.RUTAS (
			UIDRUTA VARCHAR2(36),
			SRUTA VARCHAR2(120),
			DTFECHACREACION TIMESTAMP,
			DTFECHAACTUALIZACION TIMESTAMP,
			SCLAVERUTA VARCHAR2(20),
			SDESCRIPCION VARCHAR2(200),
			SCLAVERIDANGO VARCHAR2(20),
			BAPLICATRANSBORDOS NUMBER(1,0),
			IORIGEN NUMBER(38,0) DEFAULT 1 ,
			BTRANSITORIO NUMBER(1,0) DEFAULT 1 ,
			CONSTRAINT PK_RUTAS PRIMARY KEY (UIDRUTA),
			CONSTRAINT SYS_C0032205 CHECK ("UIDRUTA" IS NOT NULL),
			CONSTRAINT SYS_C0032206 CHECK ("SRUTA" IS NOT NULL),
			CONSTRAINT SYS_C0032207 CHECK ("DTFECHACREACION" IS NOT NULL),
			CONSTRAINT SYS_C0032208 CHECK ("DTFECHAACTUALIZACION" IS NOT NULL),
			CONSTRAINT SYS_C0032209 CHECK ("IORIGEN" IS NOT NULL),
			CONSTRAINT SYS_C0032210 CHECK ("BTRANSITORIO" IS NOT NULL)
		);
		CREATE UNIQUE INDEX PK_RUTAS ON TICKETS.RUTAS (UIDRUTA);

		COMMENT ON COLUMN TICKETS.RUTAS.UIDRUTA IS 'IDENTIFICADOR DEL REGISTRO';
		COMMENT ON COLUMN TICKETS.RUTAS.SRUTA IS 'NOMBRE DE LA RUTA';
		COMMENT ON COLUMN TICKETS.RUTAS.DTFECHACREACION IS 'FECHA DE CREACION';
		COMMENT ON COLUMN TICKETS.RUTAS.DTFECHAACTUALIZACION IS 'FECHA DE ACTUALIZACION';
		COMMENT ON COLUMN TICKETS.RUTAS.SCLAVERUTA IS 'IDENTIFICADOR EN VALOR DEL REGISTRO';
		COMMENT ON COLUMN TICKETS.RUTAS.SDESCRIPCION IS 'DESCRIPCIÓN';
		COMMENT ON COLUMN TICKETS.RUTAS.SCLAVERIDANGO IS 'Identificador para ridango';
		COMMENT ON COLUMN TICKETS.RUTAS.BAPLICATRANSBORDOS IS 'Es para identificar si aplica todos los transboros y poderlos hacer masivo';
		COMMENT ON COLUMN TICKETS.RUTAS.IORIGEN IS 'Control interno de creacion 1:web 2:ridango';
		COMMENT ON COLUMN TICKETS.RUTAS.BTRANSITORIO IS 'Indica si la ruta es transitoria (1) o definitiva (0). Sirve para identificar si la ruta corresponde a un autobús o no';


		MERGE INTO TICKETS.RUTAS dest
		USING  TARIFAS.RUTAS  src
		ON (dest.UIDRUTA = src.UIDRUTA)
		WHEN NOT MATCHED THEN
			INSERT (
				UIDRUTA,
				SRUTA,
				DTFECHACREACION,
				DTFECHAACTUALIZACION,
				SCLAVERUTA,
				SDESCRIPCION,
				SCLAVERIDANGO,
				BAPLICATRANSBORDOS,
				IORIGEN,
				BTRANSITORIO
			) VALUES (
				src.UIDRUTA,
				src.SRUTA,
				src.DTFECHACREACION,
				src.DTFECHAACTUALIZACION,
				src.SCLAVERUTA,
				src.SDESCRIPCION,
				src.SCLAVERIDANGO,
				src.BAPLICATRANSBORDOS,
				src.IORIGEN,
				src.BTRANSITORIO
			);






------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- SINCRONIZADOR


ALTER TABLE SINCRONIZADOR.TARIFAS
ADD BTRANSITORIO NUMBER(1,0) DEFAULT 1 NOT NULL;
COMMENT ON COLUMN SINCRONIZADOR.TARIFAS.BTRANSITORIO IS 'Indica si la ruta es transitoria (1) o definitiva (0). Sirve para identificar si la ruta corresponde a un autobús o no';














