



9870	28/04/2025	5000000000697366	5000000000697366	EsperaRetro	Posible tema LTC	#N/D


define numBusqueda = 5000000000697366;
select DTFECHAOPERACION, INUMEROTARJETA, DMONTOCOBRADO, BPROCESADO, ICONTADORTRANSACCIONES, DTFECHACREACION, DTFECHAULTMOD,
DTFECHABAJA, ITRANSBORDO, DSALDO, DSALDOANTERIOR, SINCIDENCIA, IDVALIDADOR,
TOKENTRANSACCION, LOADTRANSCOUNTER, IERROR, BDEBITADO, BFIRMADO, CERTIFICADO,
DATEHSM, TRANSVALUE, PANHASH FROM SINCRONIZADOR.DETALLESINCRONIZACIONTRANSACCIONESNFC nfc where inumerotarjeta =&numBusqueda and bdebitado = 1 order by dtfechaoperacion desc;
select DTFECHAOPERACION, INUMEROTARJETA, DMONTOCOBRADO, BPROCESADO, ICONTADORTRANSACCIONES, DTFECHACREACION, DTFECHAULTMOD,
DTFECHABAJA, ITRANSBORDO, DSALDO, DSALDOANTERIOR, SINCIDENCIA, IDVALIDADOR,
TOKENTRANSACCION, LOADTRANSCOUNTER, IERROR, BDEBITADO, BFIRMADO, CERTIFICADO,
DATEHSM, TRANSVALUE, PANHASH  FROM SINCRONIZADOR.DETALLESINCRONIZACIONTRANSACCIONESNFC nfc where inumerotarjeta =&numBusqueda order by dtfechaoperacion desc;
select * from monederoconsultas.estadodecuenta where inumtarjeta =&numBusqueda;
select icontadorrecarga, icontadorrecargaaplicada FROM SINCRONIZADOR.monedero where inumerotarjeta =&numBusqueda;
select * FROM SINCRONIZADOR.cambiosmonedero where starjeta=&numBusqueda order by icontadorrecarga asc;


-- -- SIN ERROR
-- --
update SINCRONIZADOR.cambiosmonedero set uidlistacuentas = '00000000-0000-0000-0000-000000000000' where uidcambiosmonedero = 'ad388cad-576f-4b70-a84b-b08c058275e9'; commit;

--misma tarjeta que el anterior


