-- Transacciones Diarias SIN duplicados de Rechazadas V3
--select trunc(DTFECHAOPERACION), count(0) from (
SELECT /*+ PARALLEL(AUTO) FULL(NFC) FULL(M) FULL(R) FULL(V) FULL(AU) FULL(E) FULL(A) LEADING(NFC M) */
'Tarjeta Inteligente' TIPOTRANSACCION,
NFC.DTFECHAOPERACION,
NFC.DTFECHACREACION,
COALESCE (M.STIPOTARIFA,NFC.STIPOTARIFA) STIPOTARIFA,
COALESCE (TO_CHAR(M.INUMEROTARJETA),'0') INUMEROTARJETA,
NFC.TOKENTRANSACCION,
E.DSALDO AS SALDO_MONEDERO,
NVL(A.ABONOS,0) AS TOTAL_ABONOS,
NFC.DMONTOCOBRADO DMONTO,
--NFC.DSALDO DSALDO,
CASE(NFC.IERROR)
WHEN 0 THEN NFC.DSALDO + NFC.DMONTOCOBRADO
--WHEN NFC.IERROR= 5 and TOKENTRANSACCION != '00000000000000000000000000000000' THEN NFC.DSALDO + NFC.DMONTOCOBRADO
ELSE
NFC.DSALDO
END DSALDOANTERIOR,
NFC.ITRANSBORDO,
CASE
WHEN NFC.IERROR= 0 THEN 'Confirmada'
WHEN NFC.IERROR= 5 and TOKENTRANSACCION != '00000000000000000000000000000000' THEN 'Confirmada'
WHEN NFC.IERROR= 5 and TOKENTRANSACCION = '00000000000000000000000000000000' THEN 'Error en lectura'
WHEN NFC.IERROR= 1 THEN 'Tarjeta expirada'
--WHEN NFC.IERROR= 2 THEN 'Rechazada'
WHEN NFC.IERROR= 2 AND (E.DSALDO - NFC.DMONTOCOBRADO) <= 0 THEN 'Sin saldo'
WHEN NFC.IERROR= 2 AND (E.DSALDO - NFC.DMONTOCOBRADO) > 0 THEN 'Rechazada'
WHEN NFC.IERROR= 3 THEN 'Deny list'
WHEN NFC.IERROR= 4 THEN 'Tarjeta no soportada'
WHEN NFC.IERROR= 6 THEN 'Falta configurar tarifa'
WHEN NFC.IERROR= 7 THEN 'Error en recarga'
WHEN NFC.IERROR= 100 THEN 'Tarjeta recargada'
ELSE 'Otro'
END
ESTADOTRANSACCION,
CASE WHEN NFC.IERROR = 5 and TOKENTRANSACCION != '00000000000000000000000000000000' THEN 0 ELSE NFC.IERROR END IERROR,
CASE WHEN NFC.IERROR = 0 THEN 1
WHEN NFC.IERROR= 5 and TOKENTRANSACCION != '00000000000000000000000000000000' THEN 1
WHEN NFC.IERROR in (2,3,4,6,7) THEN
ROW_NUMBER() OVER(PARTITION BY NFC.INUMEROTARJETA,TRUNC(NFC.DTFECHAOPERACION), CASE WHEN NFC.IERROR = 0 THEN 1 ELSE 0 END ORDER BY NFC.DTFECHAOPERACION ASC) ELSE 1 END AS LIMITE,
CASE WHEN NFC.IERROR = 0 THEN 1
WHEN NFC.IERROR = 5 and TOKENTRANSACCION != '00000000000000000000000000000000' THEN 1
ELSE 0
END BEXITOSO,
R.SCLAVERUTA,
R.SRUTA,
v.SVALIDADOR,
v.SMODELO,
AU.SNUMECO,
NFC.BPROCESADO
FROM SINCRONIZADOR.DETALLESINCRONIZACIONTRANSACCIONESNFC NFC
INNER JOIN SINCRONIZADOR.MONEDERO m ON M.INUMEROTARJETA =NFC.INUMEROTARJETA and M.Inumerotarjeta>0
LEFT JOIN SINCRONIZADOR.RUTAS r ON R.SCLAVERUTA=NFC.IRUTA and M.Inumerotarjeta>0
LEFT JOIN SINCRONIZADOR.VALIDADORES v on v.UIDVALIDADOR = NFC.UIDVALIDADOR
LEFT JOIN CATALOGOS.AUTOBUSVALIDADOR AV ON AV.UIDVALIDADOR = v.UIDVALIDADOR AND AV.BACTIVO = 1
LEFT JOIN SINCRONIZADOR.AUTOBUSES AU ON AU.UIDAUTOBUS = AV.UIDAUTOBUS
INNER JOIN MONEDEROCONSULTAS.ESTADODECUENTA E ON E.UIDMONEDERO =M.UIDMONEDERO
LEFT JOIN (
SELECT SUBSTR(TO_CHAR(INUMEROTARJETA),1,16)INUMEROTARJETA,COUNT(*) AS ABONOS, SUM(DMONTO) MONTOABONO, M.UIDMONEDERO,MAX(M.DTFECHAOPERACION)DTFECHAOPERACION FROM MONEDEROCONSULTAS.MOVIMIENTOS M
INNER JOIN CREDENCIALIZACION.TARJETAS T ON T.UIDMONEDERO = M.UIDMONEDERO
WHERE 1=1
AND STIPOMOVIMIENTO = 'ABONO'
GROUP BY INUMEROTARJETA,M.UIDMONEDERO) A ON A.INUMEROTARJETA = NFC.INUMEROTARJETA
LEFT JOIN MONEDEROCOMANDOS.movimientosestadosdecuenta M ON M.UIDOPERACION = NFC.UIDSINCRONIZACION AND M.UIDTIPOSMONEDERO = 'e7f21096-73e4-4fe9-aed6-ee29947304b0'
AND M.UIDTIPOMOVIMIENTO = '58956590-095e-4ff5-b1b3-20b2892db778'
AND M.UIDTIPOTRANSACCION = 'e350f3d3-c742-4a13-9674-edeafc171893'
AND M.SEMISOR IS NULL
WHERE 1=1
--AND R.BACTIVO=1
AND (TRUNC(NFC.DTFECHAOPERACION) >= trunc(to_date(sysdate-1,'dd/mm/yy')) AND TRUNC(NFC.DTFECHAOPERACION) < trunc(to_date(sysdate,'dd/mm/yy')))
AND TRUNC(NFC.DTFECHACREACION) <= TRUNC(SYSDATE)
--) where limite = 1 group by trunc(DTFECHAOPERACION)